### ISSUE TITLE
exception in overviewer_core/files.py

### ISSUE THREAD

**Issue by troetnase** [overviewer/Minecraft-Overviewer#1081]
Funny thing: from time to time the overviewer raises an exception:

```
Process MultiprocessingDispatcherProcess-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/dispatcher.py", line 256, in run
    self.update_tilesets()
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/dispatcher.py", line 219, in update_tilesets
    self.tilesets, self.tileset_version = self.tileset_proxy._getvalue()
  File "/usr/lib64/python2.6/multiprocessing/managers.py", line 746, in _getvalue
    return self._callmethod('#GETVALUE')
  File "/usr/lib64/python2.6/multiprocessing/managers.py", line 726, in _callmethod
    kind, result = conn.recv()
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/tileset.py", line 384, in __setstate__
    self.__init__(*state)
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/tileset.py", line 361, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/files.py", line 27, in get_fs_caps
    "rename_works": does_rename_work(dir_to_test)
  File "/usr/local/gameserver/newagent/binaries/overviewer/overviewer_core/files.py", line 60, in does_rename_work
    open(f1.name, 'w').close()
  File "/usr/lib64/python2.6/tempfile.py", line 412, in __exit__
    self.close()
  File "/usr/lib64/python2.6/tempfile.py", line 403, in close
    self.unlink(self.name)
OSError: [Errno 2] No such file or directory: '/usr/local/gameserver/data/overview/xxx.xxx.xxx.xxx/yyyyyy/world-lighting/tmpDx2zBe'
```

commandline for this one is:
/usr/local/gameserver/newagent/binaries/overviewer/overviewer.py --verbose --simple-output --processes=20 --rendermodes=normal,lighting,night /usr/local/gameserver/data/write/saves/eeeee/dddd/ccc/bb/a/yyyyyy/world /usr/local/gameserver/data/overview/xxx.xxx.xxx.xxx/yyyyyy

Python is version 2.6.6 on CentOS 6.5.

**Comment by farhan4648gul** [comment]
Hey Guys! 

Did you find some solution to this problem? I have run into same problem while working on my android aosp project. It was working fine till last week, however, with an update to the system, the issue has appeared up.

**Comment by LeadMagnet** [comment]
I have no idea about running Overviewer on Linux, however with the 1.8.4 update, got serious errors on one of the 10 maps I render. Turns out it's a very, VERY old map. Originally generated in 1.6.

Overviewer gave a output of the region files throwing the errors (which do not look like your output). After deleting these files, the map rendered. Luckily for us, nobody had builds in these areas anyway and subsequent revisits (re-generate chunks ingame) to these chunks have rendered fine.

Is this happening on all your worlds? All dimensions? Have you tried rendering a brand new (un-explored) world?

/me grasping at straws!

:D

**Comment by CounterPillow** [comment]
@farhan4648gul Please provide the full output of overviewer, and your config file, and what operating system you're running it on.

**Comment by farhan4648gul** [comment]
Thanks guys for coming back to an old thread... I have got the issue fixed, it was because of invalid configuration... Now its working fine :)

**Comment by CounterPillow** [comment]
If it doesn't have the same symptoms as the initial issue, please don't hijack it. The initial report explicitly stated that this only happens from time to time.

Forgetting to install the optimisation programs (like @minetonight did) is not the same issue, and not providing configuration or even full output is not helping the case either.
