### ISSUE TITLE
Error after update to lazily fetch names from UUIDs

### ISSUE THREAD

**Issue by RickyThunell** [overviewer/Minecraft-Overviewer#1117]
```
2014-06-19 03:07:23 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 582, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 118, in main
    g.genPOI.main()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 350, in main
    result = filter_function(poi)
  File "3pconfig.py", line 9, in playerIcons
    poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 127, in __getitem__
    super(PlayerDict, self).__setitem__("EntityId", self.get_name_from_uuid())
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 139, in get_name_from_uuid
    logging.warning("Unable to get player name for UUID %s", playername)
NameError: global name 'playername' is not defined
```

**Comment by rugalash** [comment]
Just an FYI for anyone who stumbles on this via searching like I did.. you can use OFFLINE servers and get user names if you use anything with bukkit (which you probably do)
`def playerIcons(poi):
    if poi['id'] == 'Player':
        if 'bukkit' in poi:
            print(poi["bukkit"])
            name = poi['bukkit']['lastKnownName']
            poi['icon'] = "icons/player.png"
            return "Last known location for %s" % name`

Note the icon is a static player image, you can of course add a name list with their images but I just grabbed the default image for all the players.
more importantly the bukkit dictionary stores a "lastKnownName" which eliminates the need to query any other servers for names with your UUID etc.
