### ISSUE TITLE
POI Gen Error

### ISSUE THREAD

**Issue by Morketh** [overviewer/Minecraft-Overviewer#1130]
i have an automated render set up with a cron job and when i run it i get an error while doing the POI render i believe it has something to do with my TIME POI but im not exactly sure

This is the error that occurred:

``` python
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 587, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 118, in main
    g.genPOI.main()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 296, in main
    handlePlayers(rset, render, worldpath)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/aux_files/genPOI.py", line 152, in handlePlayers
    'DIM1': 1}[rset.get_type()]
KeyError: 'DIM7'
```

heres my config file:

``` python
import datetime

DIM_TW_FOR = "true"

worlds["Day"]   = "/opt/minecraft/CollectiveIndustries"
worlds["Night"] = "/opt/minecraft/CollectiveIndustries"

outputdir = "/opt/overview/WWW"
texturepath = "/opt/overview/lib/1.7.2.jar"


### POI Defs ###

def signFilter(poi):
    if poi["id"] == "Sign":
      if poi["Text1"] == "TIME":
        return "Render Time: ".datetime.datetime.now()
      else:
            return " \n".join([poi["Text1"], poi["Text2"], poi["Text3"], poi["Text4"]])

def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

## POI FILTER ##
PlayerPOS = {"name":         "Players",
             "filterFunction": playerIcons,
             }

SignPOS = {"name":  "Signs",
       "filterFunction": signFilter,
       }



POI_Filters = [PlayerPOS, SignPOS]

### "dimension": "overworld"  ###

##  upper-left ##
renders["survivalday"] = {
    "world": "Day",
    "title": "UL",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "markers": POI_Filters,
}
renders["survivalnight"] = {
    "world": "Night",
    "title": "UL",
    "rendermode": smooth_night,
    "dimension": "overworld",
    "markers": POI_Filters,
}
## upper-right ##

renders["survivalDayUR"] = {
    "world": "Day",
    "title": "UR",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "northdirection" : "upper-right",
    "markers": POI_Filters,
}
renders["survivalNightUR"] = {
    "world": "Night",
    "title": "UR",
    "rendermode": smooth_night,
    "dimension": "overworld",
    "northdirection" : "upper-right",
    "markers": POI_Filters,
}

## lower-left ##

renders["survivalDayLL"] = {
    "world": "Day",
    "title": "LL",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "northdirection" : "lower-left",
    "markers": POI_Filters,
}
renders["survivalNightLL"] = {
    "world": "Night",
    "title": "LL",
    "rendermode": smooth_night,
    "dimension": "overworld",
    "northdirection" : "lower-left",
    "markers": POI_Filters,
}

## lower-right ##
renders["survivalDayLR"] = {
    "world": "Day",
    "title": "LR",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "northdirection" : "lower-right",
    "markers": POI_Filters,
}
renders["survivalNightLR"] = {
    "world": "Night",
    "title": "LR",
    "rendermode": smooth_night,
    "dimension": "overworld",
    "northdirection" : "lower-right",
    "markers": POI_Filters,
}

## TWILIGHT DIM 7 ##

if DIM_TW_FOR == "true":
##  upper-left ##
    renders["survivalTWday"] = {
            "world": "Day",
            "title": "UL",
            "rendermode": smooth_lighting,
            "dimension": "DIM7",
            "markers": POI_Filters,
    }
    renders["survivalTWnight"] = {
            "world": "Night",
            "title": "UL",
            "rendermode": smooth_night,
            "dimension": "DIM7",
            "markers": POI_Filters,
    }
## upper-right ##

    renders["survivalTWDayUR"] = {
            "world": "Day",
            "title": "UR",
            "rendermode": smooth_lighting,
            "dimension": "DIM7",
            "northdirection" : "upper-right",
            "markers": POI_Filters,
    }
    renders["survivalTWNightUR"] = {
            "world": "Night",
            "title": "UR",
            "rendermode": smooth_night,
            "dimension": "DIM7",
            "northdirection" : "upper-right",
            "markers": POI_Filters,
    }

## lower-left ##

    renders["survivalTWDayLL"] = {
        "world": "Day",
            "title": "LL",
            "rendermode": smooth_lighting,
            "dimension": "DIM7",
            "northdirection" : "lower-left",
            "markers": POI_Filters,
    }
    renders["survivalTWNightLL"] = {
            "world": "Night",
            "title": "LL",
            "rendermode": smooth_night,
            "dimension": "DIM7",
            "northdirection" : "lower-left",
            "markers": POI_Filters,
    }

## lower-right ##
    renders["survivalTWDayLR"] = {
            "world": "Day",
            "title": "LR",
            "rendermode": smooth_lighting,
            "dimension": "DIM7",
            "northdirection" : "lower-right",
            "markers": POI_Filters,
    }
    renders["survivalTWNightLR"] = {
            "world": "Night",
            "title": "LR",
            "rendermode": smooth_night,
            "dimension": "DIM7",
            "northdirection" : "lower-right",
            "markers": POI_Filters,
    }
else:
    print "Rendering for DIM-7 disabled untill found. I will check the time we render"
```

**Comment by mide** [comment]
I've noticed a very similar issue that has led me to cram everything into the single filter function (nothing outside the function, including imports). You can see some past discussions about this [here](https://github.com/mide/minecraft-overviewer/pull/68#pullrequestreview-400452167). Not a blocker, just passing along context if it's useful.
