### ISSUE TITLE
Crash on updating map with newly explored area

### ISSUE THREAD

**Issue by Feronzed** [overviewer/Minecraft-Overviewer#1166]
A crash happens when I try to run overviewer with custom config (http://pastebin.com/Mkp0mmJa) and update already existing map with my world save being explored further and containing new, un-rendered chunks.

Here is the log:
#############################################################
2014-10-13 02:11:49 W Your map seems to have expanded beyond its previous bounds.
2014-10-13 02:11:49 W Doing some tile re-arrangements... just a sec...
2014-10-13 02:11:49 W Your map seems to have expanded beyond its previous bounds.
2014-10-13 02:11:49 W Doing some tile re-arrangements... just a sec...
2014-10-13 02:11:50 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 587, in <module>
  File "overviewer.py", line 522, in main
  File "overviewer_core\tileset.pyc", line 422, in do_preprocessing
  File "overviewer_core\tileset.pyc", line 671, in _rearrange_tiles
  File "overviewer_core\tileset.pyc", line 701, in _increase_depth
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\Damian\\Dropbox\\Public\\Server Map\\survivalcaves\\new3'
##############################################################

Further info:
System - Windows 8 64x
32GB RAM

Config file - http://pastebin.com/Mkp0mmJa

**Comment by agrif** [comment]
Months in the future, this fix has been merged. I'm closing this, but please let us know if it ever happens again.
