### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by CounterPillow** [overviewer/Minecraft-Overviewer#1195]
A user on IRC reported that Overviewer 0.12.20 fails with the following error:

```
2015-01-08 15:07:34  Welcome to Minecraft Overviewer!
2015-01-08 15:07:47  Generating textures...
2015-01-08 15:07:58  Generating textures...
2015-01-08 15:08:08  Generating textures...
2015-01-08 15:08:19  Generating textures...
2015-01-08 15:09:22  Generating textures...
2015-01-08 15:10:22 E An error has occurred. This may be a bug. Please let us kn
ow!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 597, in <module>
  File "overviewer.py", line 467, in main
  File "overviewer_core\world.pyc", line 97, in __init__
  File "overviewer_core\nbt.pyc", line 28, in wrapper
IOError: [Errno 24] Too many open files: 'Z:\\Minecraft Servers\\NB Community\\Minecraft\\world\\level.dat'
```

**Note:** Z: is a network drive. The operating system the user was using is Windows 8.1 x64.

The user's configuration is as follows:

``` python
# Worlds

worlds["Adrian & Friends"] = "Z:/Minecraft Servers/Adrian & Friends/Minecraft/world"
worlds["Adrian & Friends 2"] = "Z:/Minecraft Servers/Adrian & Friends 2/Minecraft/world"
worlds["Home"] = "Z:/Minecraft Servers/Home/Minecraft/world"
worlds["Legit"] = "Z:/Minecraft Servers/Legit/Minecraft/world"
worlds["NB Community"] = "Z:/Minecraft Servers/NB Community/Minecraft/world"
worlds["Space"] = "Z:/Minecraft Servers/Space/Minecraft/world"

# End Render

end_lighting = [Base(), EdgeLines(), Lighting(strength=0.5)]
end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]

# Progress bar

from observer import ProgressBarObserver
observer = ProgressBarObserver()

# Render Settings

imgquality = 100
processes = 8
outputdir = "Z:/Minecraft Maps"

# Adrian & Friends

renders["af_day_ul"] = {
"world": "Adrian & Friends",
"title": "Day - NW",
"rendermode": smooth_lighting,
"northdirection": "upper-left",
}

renders["af_day_ur"] = {
"world": "Adrian & Friends",
"title": "Day - NE",
"rendermode": smooth_lighting,
"northdirection": "upper-right",
}

renders["af_day_ll"] = {
"world": "Adrian & Friends",
"title": "Day - SW",
"rendermode": smooth_lighting,
"northdirection": "lower-left",
}

renders["af_day_lr"] = {
"world": "Adrian & Friends",
"title": "Day - SE",
"rendermode": smooth_lighting,
"northdirection": "lower-right",
}

renders["af_night_ul"] = {
"world": "Adrian & Friends",
"title": "Night - NW",
"rendermode": smooth_night,
"northdirection": "upper-left",
}

renders["af_night_ur"] = {
"world": "Adrian & Friends",
"title": "Night - NE",
"rendermode": smooth_night,
"northdirection": "upper-right",
}

renders["af_night_ll"] = {
"world": "Adrian & Friends",
"title": "Night - SW",
"rendermode": smooth_night,
"northdirection": "lower-left",
}

renders["af_night_lr"] = {
"world": "Adrian & Friends",
"title": "Night - SE",
"rendermode": smooth_night,
"northdirection": "lower-right",
}

renders["af_nether"] = {
"world": "Adrian & Friends",
"title": "Nether",
"rendermode": nether_smooth_lighting,
"dimension": "nether",
}

renders["af_end"] = {
"world": "Adrian & Friends",
"title": "End",
"rendermode": end_smooth_lighting,
"dimension": "end",
}

# Adrian & Friends 2

renders["af2_day"] = {
"world": "Adrian & Friends 2",
"title": "Day",
"rendermode": smooth_lighting,
}

renders["af2_night"] = {
"world": "Adrian & Friends 2",
"title": "Night",
"rendermode": smooth_night,
}

# Home

renders["h_day"] = {
"world": "Home",
"title": "Day",
"rendermode": smooth_lighting,
"texturepath" : "C:/Users/vilis_000/Desktop/1.8flowshd.zip",
}

renders["h_night"] = {
"world": "Home",
"title": "Night",
"rendermode": smooth_night,
"texturepath" : "C:/Users/vilis_000/Desktop/1.8flowshd.zip",
}

# Legit

renders["l_day"] = {
"world": "Legit",
"title": "Day",
"rendermode": smooth_lighting,
}

renders["l_night"] = {
"world": "Legit",
"title": "Night",
"rendermode": smooth_night,
}

renders["l_nether"] = {
"world": "Legit",
"title": "Nether",
"rendermode": nether_smooth_lighting,
"dimension": "nether",
}

# NB Community

renders["nb_day"] = {
"world": "NB Community",
"title": "Day",
"rendermode": smooth_lighting,
}

renders["nb_night"] = {
"world": "NB Community",
"title": "Night",
"rendermode": smooth_night,
}

renders["nb_nether"] = {
"world": "NB Community",
"title": "Nether",
"rendermode": nether_smooth_lighting,
"dimension": "nether",
}

# Space

renders["s_day"] = {
"world": "Space",
"title": "Day",
"rendermode": smooth_lighting,
}

renders["s_night"] = {
"world": "Space",
"title": "Night",
"rendermode": smooth_night,
}
```

The user attempted rebooting his computer and the NAS the files were stored on, without success. The error persisted.

The user was not running any unusual software at the time that could cause this.

The best lead we have so far is either many worlds + Windows, network drive or network drive + many worlds + Windows.

Either way, checking the code for unclosed filehandles might be a good idea anyway.

**Comment by fezzik02** [comment]
Please ask the user to check the [ulimit](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/) on the NAS machine.

**Comment by CounterPillow** [comment]
You mean the guy who I don't remember the name of and hasn't been on IRC in over 4 years? Yeah I'll go right ahead
