### ISSUE TITLE
genpoi: No JSON object could be decoded

### ISSUE THREAD

**Issue by PaulTGG** [overviewer/Minecraft-Overviewer#1231]
Hi, dealing with this error trying to run genpoi (on Linux).

```
This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
    ret = main()
  File "overviewer.py", line 130, in main
    g.genPOI.main()
  File "/home/paul/Minecraft-Overviewer/overviewer_core/aux_files/genPOI.py", line 496, in main
    PlayerDict.load_cache(destdir)
  File "/home/paul/Minecraft-Overviewer/overviewer_core/aux_files/genPOI.py", line 214, in load_cache
    cls.uuid_cache = json.load(gz)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

Here's my config:

```
def townFilter(poi):
    if poi['id'] == 'Town':
        return poi['name']

worlds['server'] = '/home/paul/minecraft/server'

renders['normalrender'] = {
    'world': 'server',
    'title': 'title',
    'rendermode': smooth_lighting,
    'manualpois' : [{'id':'mine', 'x':763, 'y':64, 'z':673, 'name':'Arena'} ,
             {'id':'ship', 'x':896, 'y':64, 'z': 1167, 'name':'Sub' },
             {'id':'town', 'x':-3419, 'y':64, 'z': 618, 'name':'Western Settlement' },
             {'id':'mine', 'x':800, 'y':64, 'z': 745, 'name':'Game Zone' },
             {'id':'town', 'x':2934, 'y':64, 'z': 1808, 'name':'Ice City' },
             {'id':'mine', 'x':896, 'y':64, 'z': 433, 'name':'House'},
             {'id':'mine', 'x':1391, 'y':64, 'z': 471, 'name':'Mountain House'},
             {'id':'mine', 'x':1675, 'y':64, 'z': 760, 'name':'Pagoda' },
             {'id':'mine', 'x':1543, 'y':64, 'z': 389, 'name':'Parthenon' },
             {'id':'ship', 'x':940, 'y':64, 'z': 210, 'name':'Submarine Bay' },
             {'id':'town', 'x':1694, 'y':64, 'z': 638, 'name':'Town' },
             {'id':'mine', 'x':669, 'y':64, 'z': 533, 'name':'Village' },
             {'id':'hoe', 'x':-5827, 'y':64, 'z': 2734, 'name':'Mooshroom Biome' },
             {'id':'hoe', 'x':2282, 'y':64, 'z': -968, 'name':'Flower Forest' }],
     'markers': [dict(name="towns", filterFunction=townFilter)],
}

outputdir = '/home/paul/webroot/overviewer'

```

I was originally getting an error about a missing uuidcache.dat file in the output folder, so I created an empty file to get past that error.  Also, this is being done on a world where the map hasn't been generated yet (although I have yet to get the POI to generate so far - various errors on both Linux and Windows).

**Comment by CounterPillow** [comment]
>I was originally getting an error about a missing uuidcache.dat file in the output folder, so I created an empty file to get past that error.

That's most likely not what you should've done.

Can you paste the error you were getting previously here?

**Comment by PaulTGG** [comment]
I tried doing a clean build, and everything is working now.  Closing this as I can't duplicate the error.
