### ISSUE TITLE
Bad zip file?

### ISSUE THREAD

**Issue by NYShung** [overviewer/Minecraft-Overviewer#1245]
Help! I'm stuck here and I don't know what to do!

Error Code:
```
C:\Users\Ng\Downloads\Compressed\overviewer-0.12.75>overviewer.exe "C:\Users\Ng\AppData\Roaming\.minecraft\saves\Redstone 1" E:\
2015-08-04 21:54:59  Welcome to Minecraft Overviewer!
2015-08-04 21:54:59  Generating textures...
2015-08-04 21:54:59 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 478, in main
  File "overviewer_core\textures.pyc", line 95, in generate
  File "overviewer_core\textures.pyc", line 319, in load_image_texture
  File "overviewer_core\textures.pyc", line 336, in load_image
  File "overviewer_core\textures.pyc", line 281, in find_file
  File "zipfile.pyc", line 714, in __init__
  File "zipfile.pyc", line 748, in _GetContents
  File "zipfile.pyc", line 763, in _RealGetContents
BadZipfile: File is not a zip file
```

Thanks for answering!

**Comment by CounterPillow** [comment]
Make sure your client's jar file isn't corrupted in any way. Redownload the client in the launcher if you have to. Delete the .jar files inside the latest version directory of `%APPDATA%\.minecraft\versions\` if you have to.

**Comment by eminence** [comment]
If you are still having problems, please re-open this github ticket.  Thanks!
