### ISSUE TITLE
Error running 0.12.87 with --genpoi

### ISSUE THREAD

**Issue by Bobcat00** [overviewer/Minecraft-Overviewer#1271]
Windows 8.1 64-bit overviewer-0.12.87.zip gets the following error with --genpoi:

```
C:\Users\Bob\Documents\Overviewer>overviewer.exe --config=worlds/config.py --genpoi --skip-scan
2016-01-17 21:29:25  Loaded UUID cache from 'C:\\users\\bob\\documents\\overviewer\\maps\\uuidcache.dat' with 0 entries
2016-01-17 21:29:26  Done handling POIs
2016-01-17 21:29:26  Writing out javascript files
2016-01-17 21:29:26  Wrote UUID cache with 0 entries
2016-01-17 21:29:26 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 130, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 533, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 241, in save_cache
  File "overviewer_core\files.pyc", line 164, in __exit__
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
```

The following is the output with version 0.12.82:

```
C:\Users\Bob\Documents\Overviewer>overviewer.exe --config=worlds/config.py --genpoi --skip-scan
2016-01-17 21:32:15  Loaded UUID cache from 'C:\\users\\bob\\documents\\overview
er\\maps\\uuidcache.dat' with 0 entries
2016-01-17 21:32:16  Done handling POIs
2016-01-17 21:32:16  Writing out javascript files
2016-01-17 21:32:16  Wrote UUID cache with 0 entries
2016-01-17 21:32:16  Done
```

**Comment by eminence** [comment]
Perhaps another instance of overviewer is running?  Something is holding open the yuid cache file

**Comment by Bobcat00** [comment]
Definitely only one instance running. And I immediately reverted to 0.12.82 and re-ran Overviewer in the same command window with no problems.  .82 to .87 involved changing the cache processing, so maybe that's where the problem lies.

**Comment by CounterPillow** [comment]
I just pushed a change which may fix this, let us know if the problem still persists.

Thanks for your bug report.

**Comment by Bobcat00** [comment]
Nope, running Win 64-bit 12.90 gets the following error:

```
C:\Users\Bob\Documents\Overviewer>overviewer.exe --config=worlds/config.py --genpoi --skip-scan
2016-01-30 16:12:15  Loaded UUID cache from 'C:\\users\\bob\\documents\\overviewer\\maps\\uuidcache.dat' with 0 entries
2016-01-30 16:12:16  Done handling POIs
2016-01-30 16:12:16  Writing out javascript files
2016-01-30 16:12:17  Wrote UUID cache with 0 entries
2016-01-30 16:12:17 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 130, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 535, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 243, in save_cache
  File "overviewer_core\files.pyc", line 164, in __exit__
WindowsError: [Error 183] Cannot create a file when that file already exists
```

**Comment by halfsight420** [comment]
Oh, here it is. I am getting this same script.
Windows 7 x64

OverViewer 0.12.93

Minecraft 1.9

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Shi>cd c:\Users\Shi\Desktop\overviewer

c:\Users\Shi\Desktop\overviewer>overviewer.exe --config=C:/Users/Shi/Desktop/ove
rviewer/config2.py --genpoi
2016-03-02 15:09:54 W Sorry, you requested dimension 'nether' for the render 're
nder9', but I couldn't find it
2016-03-02 15:09:54  Looking for entities in <RegionSet regiondir='x:\\world\\re
gion'>
2016-03-02 15:10:14  Done.
2016-03-02 15:10:14  Loaded UUID cache from 'M:\\minecraft.weenmebrown.com\\uuid
cache.dat' with 4 entries
2016-03-02 15:10:15  Done handling POIs
2016-03-02 15:10:15  Writing out javascript files
2016-03-02 15:10:15  Wrote UUID cache with 5 entries
2016-03-02 15:10:15 E An error has occurred. This may be a bug. Please let us kn
ow!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 130, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 536, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 244, in save_cache
  File "overviewer_core\files.pyc", line 164, in __exit__
WindowsError: [Error 183] Cannot create a file when that file already exists

c:\Users\Shi\Desktop\overviewer>

**Comment by matrixhacker** [comment]
I was having this problem as well. I resolved it by renaming uuidcache.dat. Unfortunately the file must be renamed/removed before each run or the error will still occur.

**Comment by CounterPillow** [comment]
It appears to be an issue with how Windows does atomic file renames, I'll try to look into it soon™.

**Comment by calebsander** [comment]
Still an issue in version 0.12.137.

**Comment by LeadMagnet** [comment]
I had the same problem on my server. IIS had changed the file permissions of several files to not allow overwrite. Since I didn't want to check hundreds of files, I deleted the entire output folder content and re-rendered the map. Solved my problem and subsequent passes.

**Comment by CounterPillow** [comment]
@LeadMagnet I'm fairly sure this is a different issue though, related to atomic file renames, and nothing to do with permissions.

**Comment by JRSofty** [comment]
With the [Error 183] can we get the name of the file/files that are causing the error, maybe we can delete them manually.

**Comment by calebsander** [comment]
It happens whenever you try to rename a file to another file which already exists, on Windows.

**Comment by CounterPillow** [comment]
The fix I just pushed should work, but since we currently don't have automatic Windows builds and I'm not feeling like getting my dev env set up on Windows again, I can't confirm that it works right now. If someone on Windows can build from git and show that it's still broken, I'll re-open.

**Comment by CounterPillow** [comment]
@eminence hooked me up with an up-to-date Windows build from the not-yet-finished new build infrastructure and I can confirm that this bug is indeed fixed now. Hooray!
