### ISSUE TITLE
IOError: decoder zip not available

### ISSUE THREAD

**Issue by Seedsy81** [overviewer/Minecraft-Overviewer#1272]
Hi, I am currently trying to run overviewer on OSX. I have installed PIL and built overviewer, but when I run it I am getting the following error:

2016-01-27 18:05:07 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

```
This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
    ret = main()
  File "overviewer.py", line 478, in main
    tex.generate()
  File "/Users/Sean/Desktop/overviewer/overviewer_core/textures.py", line 95, in generate
    self.biome_grass_texture = self.build_block(self.load_image_texture("assets/minecraft/textures/blocks/grass_top.png"), self.load_image_texture("assets/minecraft/textures/blocks/grass_side_overlay.png"))
  File "/Users/Sean/Desktop/overviewer/overviewer_core/textures.py", line 319, in load_image_texture
    img = self.load_image(filename)
  File "/Users/Sean/Desktop/overviewer/overviewer_core/textures.py", line 338, in load_image
    img = Image.open(buffer).convert("RGBA")
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 679, in convert
    self.load()
  File "/Library/Python/2.7/site-packages/PIL/ImageFile.py", line 189, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 385, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder zip not available
```

In an issue with the same error (1143), it was fixed by installing pillow using homebrew, which I have done, but I am unsure of how to get overviewer to run using pillow over PIL.

Thank you for your help, and apologies if this is a silly question.

**Comment by CounterPillow** [comment]
Uninstall PIL and it should use pillow, from what I know.

**Comment by Seedsy81** [comment]
Thank you, the issue was that pillow was unlinked.
