### ISSUE TITLE
multiprocessing\managers.pyc

### ISSUE THREAD

**Issue by RacinanteOpus** [overviewer/Minecraft-Overviewer#1274]
Windows 7  Overviewer version 12.87

2016-01-30 00:24:51  Welcome to Minecraft Overviewer!
2016-01-30 00:24:51  Generating textures...
2016-01-30 00:24:58  Preprocessing...
2016-01-30 00:24:58 W Your map seems to have shrunk. Did you delete some chunks? No problem. Re-arranging tiles, just a sec...
2016-01-30 00:25:43  There done. I'm switching to --check-tiles mode for this one render. This will make sure any old tiles that should no longer exist are deleted.
2016-01-30 00:25:45 W Your map seems to have shrunk. Did you delete some chunks? No problem. Re-arranging tiles, just a sec...
2016-01-30 00:26:13  There done. I'm switching to --check-tiles mode for this one render. This will make sure any old tiles that should no longer exist are deleted.
2016-01-30 00:26:24  Rendered 0 of 43690.  0% complete.  ETA: ------

2016-01-30 00:30:03  Rendered 4970 of 43690.  11% complete.  ETA: 00h 28m 25s
2016-01-30 00:30:04 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 551, in main
  File "overviewer_core\dispatcher.pyc", line 78, in render_all
  File "overviewer_core\util.pyc", line 117, in roundrobin
  File "overviewer_core\dispatcher.pyc", line 61, in <genexpr>
  File "overviewer_core\tileset.pyc", line 504, in iterate_work_items
  File "overviewer_core\tileset.pyc", line 1192, in _iterate_and_check_tiles
  File "overviewer_core\tileset.pyc", line 1192, in _iterate_and_check_tiles
  File "overviewer_core\tileset.pyc", line 1188, in _iterate_and_check_tiles
  File "overviewer_core\tileset.pyc", line 1257, in _nuke_path
  File "shutil.pyc", line 245, in rmtree
  File "shutil.pyc", line 254, in rmtree
  File "shutil.pyc", line 252, in rmtree
WindowsError: [Error 145] The directory is not empty: 'C:\\Users\\The Master\\Documents\\Games and Diversions\\Minecraft Stuff\\TerraNovaNew\\Overworld\\2\\3\\2\\0'
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-8:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-7:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-6:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-4:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-5:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed
Process MultiprocessingDispatcherProcess-9:
Traceback (most recent call last):
  File "multiprocessing\process.pyc", line 258, in _bootstrap
  File "overviewer_core\dispatcher.pyc", line 262, in run
  File "<string>", line 2, in put
  File "multiprocessing\managers.pyc", line 758, in _callmethod
IOError: [Errno 232] The pipe is being closed

**Comment by CounterPillow** [comment]
The error you're looking for is here:

>WindowsError: [Error 145] The directory is not empty: 'C:\Users\The Master\Documents\Games and Diversions\Minecraft Stuff\TerraNovaNew\Overworld\2\3\2\0'

I don't know how this happens, perhaps we're making a wrong assumption in the code. Deleting the output folder and rendering again should fix it though, since this likely comes from an aborted previous render.

I'll rename the issue accodingly.

**Comment by RacinanteOpus** [comment]
Thank you!------- Original Message -------On 1/30/2016  06:31 AM Nicolas F. wrote:The error you're looking for is here:>WindowsError: [Error 145] The directory is not empty: 'C:\Users\The Master\Documents\Games and Diversions\Minecraft Stuff\TerraNovaNew\Overworld\2\3\2\0'I don't know how this happens, perhaps we're making a wrong assumption in the code. Deleting the output folder and rendering again should fix it though, since this likely comes from an aborted previous render.I'll rename the issue accodingly.---Reply to this email directly or view it on GitHub:https://github.com/overviewer/Minecraft-Overviewer/issues/1274#issuecomment-177166160
