### ISSUE TITLE
KeyError: 'Items'

### ISSUE THREAD

**Issue by Offerel** [overviewer/Minecraft-Overviewer#1291]
I get a KeyError for Items, if i define a Marker for Chests. What is wrong with my Config?

Output on Windows:

```
d:\temp\Overviewer>overviewer.exe --config=config.cfg --genpoi
2016-03-26 12:56:12  Looking for entities in <RegionSet regiondir='z:\\minecraft\\Testwelt\\region'>
2016-03-26 12:56:12  Buckets has 2316 entries
2016-03-26 12:56:12  Buckets has 3068 entries
2016-03-26 12:56:13 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 605, in <module>
  File "overviewer.py", line 130, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 511, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 196, in handleEntities
  File "multiprocessing\pool.pyc", line 227, in map
  File "multiprocessing\pool.pyc", line 528, in get
KeyError: 'Items'
```

This is the relevant Part in the Config File:

```
def chestFilterThree(poi):
    if poi["id"] in  ["Chest", "Trap", "Furnace"]:
        info = "[%s] \n" % poi["id"]
        info += "%i slots \n" % len(poi["Items"])
        item_sum = 0
        for item in poi["Items"]:
            item_sum += item["Count"]
        info += "%i items \n" % item_sum
        itemText = ""
        for item in poi["Items"]:
            if item["id"] == 372:
                itemText += " %i Netherwarts " % item["Count"]
        info += itemText
        return info
```

d:\temp\Overviewer>overviewer.exe --version
Minecraft Overviewer 0.12.109 (a325820)
built on Sun Mar 06 07:33:53 2016

Server is a Minecraft 1.9 Server on a Raspberry Pi with Spigot(?)

**Comment by lebbe** [comment]
I ran into the same issue, but now I know what the problem is!

In minecraft 1.9 the inventory of chests aren't spawned/genereated before someone opens the chests. That means there exists chests in the map that doesn't have content yet. The solution would be to check if the key Items are in poi first, and only then start looking for Netherwarts etc (in your case).

**Comment by Offerel** [comment]
Can you please tell me, what i should change in my config?

**Comment by lebbe** [comment]
Try this, simply return if Items are not in poi:

```python
def chestFilterThree(poi):
    if not "Items" in poi:
        return None
    if poi["id"] in  ["Chest", "Trap", "Furnace"]:
        info = "[%s] \n" % poi["id"]
        info += "%i slots \n" % len(poi["Items"])
        item_sum = 0
        for item in poi["Items"]:
            item_sum += item["Count"]
        info += "%i items \n" % item_sum
        itemText = ""
        for item in poi["Items"]:
            if item["id"] == 372:
                itemText += " %i Netherwarts " % item["Count"]
        info += itemText
        return info
```

**Comment by Offerel** [comment]
Many thx. This does work! Could you please give me the right Code for MobSpawners where the POI gives the name of the Mob? If i use my Code, i get Key Error for EntityId. I fear they are empty to.

**Comment by lebbe** [comment]
This is from my config-file:

```python
def spawnerFilter(poi):
    if poi["id"] == "MobSpawner":
        if "EntityId" in poi:
	    monster = poi["EntityId"]
        elif "SpawnPotentials" in poi:
            monster = poi["SpawnPotentials"][0]["Entity"]["id"]
        else:
            return None
        info = "[MobSpawner] \n%s \n" % monster
        info += ", ".join(map(str, [poi["x"], poi["y"], poi["z"]]))
        return info
```

**Comment by Offerel** [comment]
Many thx. This works. I had a similar approach but run first in the same error as with your code. IndentationError: expected an indented block. Since this is my first Contact with writing python code miself i hadnt seen such a error (i come from PHP / Perl / C++). But afte rsom egoogling, i found and correct the problem. Many thx.
