### ISSUE TITLE
Error -3 : Invalid literal/lengths set

### ISSUE THREAD

**Issue by mckerrnel** [overviewer/Minecraft-Overviewer#1312]
This is being run against a 1.9.4 map.  I don't know what this error is...   I was running this fine several months ago against 1.8.9 map.  I did install the newest version of Overviewer.

2016-06-30 15:50:03  Welcome to Minecraft Overviewer!
2016-06-30 15:50:03  Forcerender mode activated. ALL tiles will be rendered
2016-06-30 15:50:03 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 608, in <module>
  File "overviewer.py", line 469, in main
  File "overviewer_core\world.pyc", line 97, in __init__
  File "overviewer_core\nbt.pyc", line 29, in wrapper
  File "overviewer_core\nbt.pyc", line 37, in load
  File "overviewer_core\nbt.pyc", line 183, in read_all
  File "gzip.pyc", line 256, in read
  File "gzip.pyc", line 307, in _read
error: Error -3 while decompressing: invalid literal/lengths set

D:\Overviewer>pause & exit
Press any key to continue . . .

**Comment by CounterPillow** [comment]
An early guess of mine without having looked at this deeper is that your level.dat is corrupt.

**Comment by CounterPillow** [comment]
Okay, yep, it's the level.dat. Line 469 in `overviewer.py` tries to load the world, which then leads to line 97 in `world.py` which tries to load the level.dat. Can you upload your level.dat to http://overviewer.org/uploader/ so we can take a look at it?
