### ISSUE TITLE
texturepath value specified in configuration file is ignored

### ISSUE THREAD

**Issue by Assimilater** [overviewer/Minecraft-Overviewer#1327]
I'm trying to setup a cron job on an ubuntu server.

To deal with the textures I've downloaded the 1.10.2 client jar and zipped the assets/minecraft/textures folder into a file textures.zip

I have the following configuration file

```
world = {
    "Title": "Isopre Vanilla",
    "Path" : "isopre",
}

end_lighting = [Base(), EdgeLines(), Lighting(strength=0.5)]
end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]

texturepath = "/mc/client/versions/1.10.2/textures.zip"
#texturepath = "/home/jfassett/.minecraft/versions/1.10.2/textures.zip"
print texturepath

#-----------------------------------+
# Actual Configuration              |
#-----------------------------------+

worlds[world["Title"]] = "/mc/server/" + world["Path"] + "/world"

renders["day"] = {
    "world": world["Title"],
    "title": "Daytime",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

renders["night"] = {
    "world": world["Title"],
    "title": "Nighttime",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

renders["nether"] = {
    "world": world["Title"],
    "title": "Nether",
    "rendermode": nether_smooth_lighting,
    "dimension": "nether",
}

renders["end"] = {
    "world": world["Title"],
    "title": "The End",
    "rendermode": end_smooth_lighting,
    "dimension": "end",
}

outputdir = "/mc/node/www/overviewer/" + world["Path"]

```
I run the following command: `overviewer.py --config=overviewer.cfg`
And get the following error:

```
jcall@u18876059:/mc$ overviewer.py --config=overviewer.cfg
/mc/client/versions/1.10.2/textures.zip
2016-08-27 18:23:03  Welcome to Minecraft Overviewer!
2016-08-27 18:23:03  Generating textures...
2016-08-27 18:23:03 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/grass_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```
I've specified texturepath but overviewer doesn't seem to recognize it.

**Comment by CounterPillow** [comment]
can you run with `--check-terrain`?

**Comment by Assimilater** [comment]
Ok so here is the output I get:

```
jcall@u18876059:/mc$ overviewer.py --config=overviewer.cfg --check-terrain -v
/mc/client/versions/1.10.2/textures.zip
overviewer.py:325  10502 2016-08-27 19:40:38 INFO     Looking for a few common texture files...
overviewer.py:327  10502 2016-08-27 19:40:38 INFO     Looking at render 'day'
textures.py:148    10502 2016-08-27 19:40:38 INFO     Starting search for assets/minecraft/textures/blocks/sandstone_top.png
textures.py:162    10502 2016-08-27 19:40:38 INFO     search_zip_paths: assets/minecraft/textures/blocks/sandstone_top.png, anim/assets/minecraft/textures/blocks/sandstone_top.png, misc/assets/minecraft/textures/blocks/sandstone_top.png, environment/assets/minecraft/textures/blocks/sandstone_top.png, item/assets/minecraft/textures/blocks/sandstone_top.png, item/chests/assets/minecraft/textures/blocks/sandstone_top.png, entity/assets/minecraft/textures/blocks/sandstone_top.png, entity/chest/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:200    10502 2016-08-27 19:40:38 INFO     Did not find the file in specified texture path
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/anim/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/misc/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/environment/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/item/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/item/chests/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/entity/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/entity/chest/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:216    10502 2016-08-27 19:40:38 INFO     Did not find the file in overviewer executable directory
textures.py:217    10502 2016-08-27 19:40:38 INFO     Looking for installed minecraft jar files...
textures.py:244    10502 2016-08-27 19:40:38 INFO     Looking in the following directory: "/home/jcall/.minecraft/versions"
textures.py:293    10502 2016-08-27 19:40:38 INFO     Did not find any non-snapshot minecraft jars >=1.8.0
textures.py:301    10502 2016-08-27 19:40:38 INFO     Looking for texture in overviewer_core/data/textures
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/anim/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/misc/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/environment/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/item/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/item/chests/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/entity/assets/minecraft/textures/blocks/sandstone_top.png
textures.py:157    10502 2016-08-27 19:40:38 INFO     filename: assets/minecraft/textures/blocks/sandstone_top.png ; path: /usr/lib/python2.7/dist-packages/overviewer_core/data/textures/entity/chest/assets/minecraft/textures/blocks/sandstone_top.png
overviewer.py:612  10502 2016-08-27 19:40:38 ERROR    Could not find the textures while searching for 'assets/minecraft/textures/blocks/sandstone_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

The first line printed is from my config file

So this line is concerning: `Did not find the file in specified texture path`

Glancing at the if statement in the source, though, this error message doesn't tell me if it didn't find the file or if the zip archive was in the wrong format. My friend said he got it working with the same .zip file, though.

I tried the following (copying from the first print statement in my config file) just to make sure the file existed and I had read access:

```
jcall@u18876059:/mc$ ls -la /mc/client/versions/1.10.2/textures.zip
-rwxrwxr-x 1 root admin 3113806 Aug 27 15:54 /mc/client/versions/1.10.2/textures.zip
jcall@u18876059:/mc$ groups
jcall sudo admin www
```

**Comment by CounterPillow** [comment]
Can you upload that exact texture zip file on your server to [the Overviewer uploader](http://overviewer.org/uploader/) so I can take a look at it?

**Comment by Assimilater** [comment]
So, I didn't realize I could connect with github until after I uploaded, but the md5 is: d93ea753ce43ceca2d5abc50a3c48fee

**Comment by CounterPillow** [comment]
Is this a custom resource pack that works in minecraft? Because it looks like it's just the "textures" folder zipped up. Normally, the structure inside the zip would contain "assets/minecraft/textures/" if I remember correctly.

**Comment by Assimilater** [comment]
It's the default resource pack downloaded from `https://s3.amazonaws.com/Minecraft.Download/versions/1.10.2/1.10.2.jar` with the textures extracted. I was under the impression all I needed was the textures in this zip archive.

**Comment by CounterPillow** [comment]
Don't extract the textures folder. Just use the default jar file.

**Comment by Assimilater** [comment]
That does indeed seem easier, now that you mention it. I thought texturepath had to be .zip extension for some reason but looking at the docs again I'm not sure where I got that idea.

Now that I got past that I do have some permission errors:

```
jcall@u18876059:/mc$ overviewer.py --config=overviewer.cfg
/mc/client/versions/1.10.2/1.10.2.jar
2016-08-28 12:11:32  Welcome to Minecraft Overviewer!
2016-08-28 12:11:32  Generating textures...
2016-08-28 12:12:00 W Sorry, you requested dimension 'end' for end, but I couldn't find it
2016-08-28 12:12:00  Preprocessing...
2016-08-28 12:12:03 W Your map seems to have expanded beyond its previous bounds.
2016-08-28 12:12:03 W Doing some tile re-arrangements... just a sec...
2016-08-28 12:12:03 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 608, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 546, in main
    assetMrg.initialize(tilesets)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 84, in initialize
    self._output_assets(tilesets, True)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 158, in _output_assets
    self.output_noconfig()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 167, in output_noconfig
    mirror_dir(global_assets, self.outputdir, capabilities=self.fs_caps)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/files.py", line 87, in mirror_dir
    shutil.copy(os.path.join(src, entry), os.path.join(dst, entry))
  File "/usr/lib/python2.7/shutil.py", line 120, in copy
    copymode(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 91, in copymode
    os.chmod(dst, mode)
OSError: [Errno 1] Operation not permitted: '/mc/node/www/overviewer/isopre/compass_lower-right.png'
```

My current permissions:
```
jcall@u18876059:/mc$ ls -la '/mc/node/www/overviewer/isopre/compass_lower-right.png'
-rwxrwxr-x 1 root www 3955 Aug 28 12:14 /mc/node/www/overviewer/isopre/compass_lower-right.png
```

I don't see in the docs where permissions are mentioned. Correct me if I'm wrong but this appears to be using chmod (which requires sudo iirc).

**Comment by CounterPillow** [comment]
This is likely caused because you ran The Overviewer with different permissions at some point, creating files that are now not writable by whatever user you're currently running it as.

Easiest is to delete the output directory and start anew.

>Correct me if I'm wrong but this appears to be using chmod (which requires sudo iirc).

You only require root permissions to modify file permissions if you're otherwise not permitted to modify them, such as if you're not the owner of the file. This is the case here; root is the owner (because you likely ran Overviewer as root in the past, which you should **not** do).

**Comment by Assimilater** [comment]
Actually, I never ran Overviewer as root. I tested it running as my local user but I wanted ownership of the output directory to be a group rather than a particular user (there's a couple of us maintaining the system) so I used `chown` to make `root:www` the owner. Example: If I make the owner jcall then jfassett might have problems.

**Comment by CounterPillow** [comment]
>Example: If I make the owner jcall then jfassett might have problems.

Not any more problems that they'd have if the owner was root.

>but I wanted ownership of the output directory to be a group rather than a particular user

There is always going to be a particular user owning the directory, together with a certain group owning it as well.

**Comment by Assimilater** [comment]
In any case I do believe this has now left this scope. I'll work something out for the permissions. :)
