### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Cocohaddock** [overviewer/Minecraft-Overviewer#1329]
Hello !
I have a problem with Overviewer : every time I try to do a render, Overviewer writes a crash report just after having wrote Generating textures...
Here is the full crash report : 
```
2016-09-02 17:09:02  Welcome to Minecraft Overviewer!
2016-09-02 17:09:02  Generating textures...
2016-09-02 17:09:03 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer.py", line 608, in <module>
    ret = main()
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer.py", line 478, in main
    tex.generate()
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 103, in generate
    tex = texgen(self, blockid, data)
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 854, in func_wrapper
    return func(texobj, blockid, data)
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 3389, in trapdoor
    texture = self.load_image_texture("assets/minecraft/textures/blocks/iron_trapdoor.png")
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 319, in load_image_texture
    img = self.load_image(filename)
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 336, in load_image
    fileobj = self.find_file(filename)
  File "/Users/Me/Downloads/overviewer-Minecraft-Overviewer-7a0930a/build/scripts-2.7/overviewer_core/textures.py", line 281, in find_file
    jar = zipfile.ZipFile(jarpath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

```

So, I'm on Mac 10.10.5. I was on Python 2.7.9 but I have updated to 2.7.12, and still the same error.
I have tried to download the .jar version with
`get https://s3.amazonaws.com/Minecraft.Download/versions/1.10/1.10.jar -P ~/.minecraft/versions/1.10/`, I have tried too with the .jar taken from the client (I play Minecraft from an other computer), and, also, I have tried a ressource pack with a config file, but there's still the same problem !
I have tried too to see if the .jar seems to be corrupted by transforming it to a .zip file and unzipping it with a software, and it worked.

Maybe helpfull, when I have compiled Overviewer, I had 3 folders on the "build" folder. Overviewer.py was on "scripts-2.7" but the overviewer_core was on the "lib.macosx-10.10-intel-2.7" folder, so I've moved it to make overviewer work (if not, I had the `ImportError No module named overviewer_core`)

Any idea ?
And too, I'm VERY new to Python, so maybe that's evident, so sorry in advance for it... .
(And sorry too for my bad english ^^).
Cocohaddock.

**Comment by LeadMagnet** [comment]
Not sure if this is related, but I've always had issues running OV on a machine where I did not run the Mojang launcher, config a profile for the version of MC I need, and click "Play".

I'm running OV on Server 2012R2 and MC will not run. However the MC installer does put all files exactly where OV can see them.

Can you try installing MC on your rendering machine, even if it is OSX (see now there's yer problem! :) ) and try again?

HTH

**Comment by Cocohaddock** [comment]
Thank you VERY MUCH, it was the problem... Now it works :-)
Cocohaddock.
