### ISSUE TITLE
Overviewer Fails with this error

### ISSUE THREAD

**Issue by ajax1515** [overviewer/Minecraft-Overviewer#1330]
This is the error that occurred:

~~~~
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 608, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 553, in main
    local_procs=config['processes'])
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 294, in __init__
    proc.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
Process MultiprocessingDispatcherProcess-7:
Process MultiprocessingDispatcherProcess-5:
Traceback (most recent call last):
    job = self.job_queue.get(True, timeout)
    self.run()
Traceback (most recent call last):
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process MultiprocessingDispatcherProcess-6:
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
    kind, result = conn.recv()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    kind, result = conn.recv()
EOFError
EOFError
Process MultiprocessingDispatcherProcess-8:
Process MultiprocessingDispatcherProcess-12:
Traceback (most recent call last):
Traceback (most recent call last):
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    job = self.job_queue.get(True, timeout)
Process MultiprocessingDispatcherProcess-10:
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    kind, result = conn.recv()
EOFError
Process MultiprocessingDispatcherProcess-9:
Traceback (most recent call last):
    kind, result = conn.recv()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
EOFError
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
Process MultiprocessingDispatcherProcess-11:
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultiprocessingDispatcherProcess-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
    kind, result = conn.recv()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
EOFError
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
Process MultiprocessingDispatcherProcess-15:
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
    self.run()
EOFError
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
    kind, result = conn.recv()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
EOFError
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
EOFError
Process MultiprocessingDispatcherProcess-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultiprocessingDispatcherProcess-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process MultiprocessingDispatcherProcess-19:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
EOFError
Process MultiprocessingDispatcherProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
EOFError
Process MultiprocessingDispatcherProcess-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process MultiprocessingDispatcherProcess-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 246, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
~~~~

**Comment by CounterPillow** [comment]
Can you please re-run with `-p1`?
Also, please tell us what version of overviewer you're running, and what the command was that you ran.

**Comment by ajax1515** [comment]
Thankyou for the fast response!

Minecraft-Overviewer 0.12.137 (7a0930a)
On Ubuntu Server 15.10

So rerunning with -p1 it now seems to be working... the render time is like 8 hours though, I guess it's a fairly large world so I won't know if it was truly successful until it's done.

Could you explain what the -p1 flag does so I can understand where the problem may have been coming from?

**Comment by agrif** [comment]
`-p1` forces Overviewer to run on only one CPU core. Mostly, for our purposes, it makes the errors easier to track because they don't write over each other.

Another side effect is that `-p1` forces Overiewer to use less memory, which is important because it looks like you were running out of memory:

    OSError: [Errno 12] Cannot allocate memory

You could try using numbers bigger than 1 there to reduce render times, at the expense of using more memory. It looks like you have a lot of cores: Overviewer defaults to using all of them, so you were using a *ton* of memory.

A side note: if you cancel and re-start a render, the ETA becomes wildly long. Don't trust it too much.

**Comment by ajax1515** [comment]
Ok, that makes sense, is there a command line argument that will limit memory usage?

**Comment by agrif** [comment]
Just `-p`, unfortunately. There's no way to tune CPU usage and memory usage seperately.

**Comment by ajax1515** [comment]
K, thanks for all your help guys
