### ISSUE TITLE
Centos 7.3 ValueError: unsupported resampling filter

### ISSUE THREAD

**Issue by Demivrga** [overviewer/Minecraft-Overviewer#1404]
Detected saves:
World       | Playtime | Modified         | Path
----------- | -------- | ---------------- | ----
EmberThorne | 48:34    | 2017-08-01 20:25 | ./EmberThorne
[demonly@ns542879 WORLDMAP]$ overviewer.py "EmberThorne" ./
2017-08-09 20:45:15  Welcome to Minecraft Overviewer!
2017-08-09 20:45:15  Generating textures...
2017-08-09 20:45:15 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 608, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 478, in main
    tex.generate()
  File "/usr/lib64/python2.7/site-packages/overviewer_core/textures.py", line 95, in generate
    self.biome_grass_texture = self.build_block(self.load_image_texture("assets/minecraft/textures/blocks/grass_top.png"), self.load_image_texture("assets/minecraft/textures/blocks/grass_side_overlay.png"))
  File "/usr/lib64/python2.7/site-packages/overviewer_core/textures.py", line 579, in build_block
    top = self.transform_image_top(top)
  File "/usr/lib64/python2.7/site-packages/overviewer_core/textures.py", line 475, in transform_image_top
    img = img.resize((17, 17), Image.ANTIALIAS)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1338, in resize
    raise ValueError("unsupported resampling filter")
ValueError: unsupported resampling filter

**Comment by agrif** [comment]
Resolved on IRC.

For posterity: the issue was a `pip` that happily overwrote the version of pillow installed by `yum`. No, I don't know either.
