### ISSUE TITLE
trouble with windows 10

### ISSUE THREAD

**Issue by pig8541** [overviewer/Minecraft-Overviewer#1409]
Maybe this has been answered before, but how can I run overviewer with windows 10? Here's what I've tried and the error I've gotten...

C:\Users\joshu\Desktop\overviewer-0.12.137>overviewer.exe "C:\Users\joshu\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sD0DAI69AQA=" "C:\Users\joshu\Desktop\Map"
2017-08-25 18:37:20  Welcome to Minecraft Overviewer!
2017-08-25 18:37:20 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 608, in <module>
  File "overviewer.py", line 469, in main
  File "overviewer_core\world.pyc", line 97, in __init__
  File "overviewer_core\nbt.pyc", line 29, in wrapper
  File "overviewer_core\nbt.pyc", line 37, in load
  File "overviewer_core\nbt.pyc", line 183, in read_all
  File "gzip.pyc", line 256, in read
  File "gzip.pyc", line 291, in _read
  File "gzip.pyc", line 185, in _read_gzip_header
IOError: Not a gzipped file 

I'm just trying to get this done for my 7 and 8 year old sons.  Not looking to get beat up for asking a question.  Any help would be appreciated.

**Comment by CounterPillow** [comment]
Minecraft Overviewer is not compatible with the Windows 10 edition of Minecraft, only the regular Java edition. The Windows 10 edition appears to be a port of the Minecraft Pocket codebase, and its map format is different from regular Minecraft.

**Comment by agrif** [comment]
To add on to this: supporting the Windows 10 (or Pocket Edition) would be *possible*, but unfortunately *a lot of work*, which none of us really have time to spare right now.

Our apologies! I hope you find a mapper that works for you.

**Comment by kecskemethy** [comment]
I would highlight in your docs main page that this mapper is only works for **Minecraft: Java Edition**.
As single title Minecraft is for all other editions in one including Win 10, Android and all that...
