### ISSUE TITLE
Error building on OSX

### ISSUE THREAD

**Issue by benjaminapetersen** [overviewer/Minecraft-Overviewer#1427]
I encountered the following error while attempting to build Overview on OSX.  At this point all I had done was fork the repo, pull, `pip2 install numpy` and then `python2 ./setup.py build`:

```
.framework/Versions/2.7/include/python2.7 -c overviewer_core/src/main.c -o build/temp.macosx-10.11-x86_64-2.7/overviewer_core/src/main.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
In file included from overviewer_core/src/main.c:18:
overviewer_core/src/overviewer.h:41:10: fatal error: 'Imaging.h' file not found
#include <Imaging.h>
         ^
1 error generated.
Traceback (most recent call last):
  File "./setup.py", line 273, in run
    build.run(self)
CompileError: command 'clang' failed with exit status 1

Failed to build Overviewer!
```

Perhaps instructions need an update?

**Comment by CounterPillow** [comment]
Please see the [OS X compilation instructions](http://docs.overviewer.org/en/latest/building/#osx).

Specifically, you need to get the PIL (or Pillow) source and set `PIL_INCLUDE_DIR`.

**Comment by benjaminapetersen** [comment]
Let me give it a retry. thanks!

**Comment by benjaminapetersen** [comment]
Gave it a spin, think we got close but ended up with this:

```
~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer.py 'all biome 2000' ~/Desktop/OverviewerOutput
2018-01-09 22:34:25  Welcome to Minecraft Overviewer!
2018-01-09 22:34:25  Generating textures...
2018-01-09 22:34:25 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer.py", line 624, in <module>
    ret = main()
  File "~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer.py", line 482, in main
    tex.generate()
  File "~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer_core/textures.py", line 95, in generate
    self.biome_grass_texture = self.build_block(self.load_image_texture("assets/minecraft/textures/blocks/grass_top.png"), self.load_image_texture("assets/minecraft/textures/blocks/grass_side_overlay.png"))
  File "~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer_core/textures.py", line 319, in load_image_texture
    img = self.load_image(filename)
  File "~/development/github/Minecraft-Overviewer/build/scripts-2.7/overviewer_core/textures.py", line 338, in load_image
    img = Image.open(buffer).convert("RGBA")
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 679, in convert
    self.load()
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 189, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 385, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder zip not available
```

Couple quick Qs/observations:
- #4 it took a second to understand:
  
    > Find the path to the libImaging directory in the PIL source tree.

just means to cd `/libImaging` and `pwd` and there you go. 

- #5 the sentence:

    > The following script (copied into your MCO source directory) should handle everything for you:

left me wondering... is this script already here (dug through various `.py` files)? Or do I copy/save this right now? 

 - Last, its a bit unclear, what is built?  The new `/build` directory exists, with three subdirectories.  I assumed initially `lib.macosx-....` is the correct one, but it wasn't clear what should run.  The [running the overviewer](http://docs.overviewer.org/en/latest/running/) page references `overviewer.py`, which exists in the `script-2.7` directory.  Ok.  So I did the following:

```
cd ~/path/to/minecraft/saves 
# and ran
/path/to/Minecraft-Overviewer/build/scripts-2.7/overviewer.py 'my world' ~/Desktop/overviewer_output
```
But it could not find the module `overviewer_core`.  So I gave it one more shot by copying the `lib.macosx-1.../overviewer_core` folder into `scripts-2.7/overviewer_core`, assuming this might get us a step further & got that gnarly error.

Thoughts?

**Comment by benjaminapetersen** [comment]
Also, @CounterPillow, your profile website, should we be concerned?

**Comment by CounterPillow** [comment]
>But it could not find the module overviewer_core. So I gave it one more shot by copying the lib.macosx-1.../overviewer_core folder into scripts-2.7/overviewer_core, assuming this might get us a step further & got that gnarly error.

Yikes, don't do that! Just running the overviewer.py in the source directory (not under `build/`) is enough after the build completed. What the build does is compile the Overviewer C extension.

Though I'm not sure if this fixes this error. The error seems familiar, I think I've seen it from someone using OS X before.

>Also, @CounterPillow, your profile website, should we be concerned?

Only a little.

**Comment by benjaminapetersen** [comment]
Ah, so I copied the wrong way. Ok cool, I'll copy overviewer.py out of /build and see what happens.

**Comment by CounterPillow** [comment]
There already should be an overviewer.py in the source directory. No copying of anything is needed.

**Comment by benjaminapetersen** [comment]
True, it is, plx excuse my fumbling around 😄 

Ok did the following:

```bash 
# find the saves
$ cd /path/to/minecraft/saves
# run the program 
$ ~/development/github/Minecraft-Overviewer/overviewer.py 'all biome 2000' ~/Desktop/OverviewerOutput/
#
# Same error as above, when I copied around some files
#
2018-01-10 09:48:39  Welcome to Minecraft Overviewer!
2018-01-10 09:48:39  Generating textures...
2018-01-10 09:48:39 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "~/development/github/Minecraft-Overviewer/overviewer.py", line 624, in <module>
    ret = main()
  File "~/development/github/Minecraft-Overviewer/overviewer.py", line 482, in main
    tex.generate()
  File "~/development/github/Minecraft-Overviewer/overviewer_core/textures.py", line 95, in generate
    self.biome_grass_texture = self.build_block(self.load_image_texture("assets/minecraft/textures/blocks/grass_top.png"), self.load_image_texture("assets/minecraft/textures/blocks/grass_side_overlay.png"))
  File "~/development/github/Minecraft-Overviewer/overviewer_core/textures.py", line 319, in load_image_texture
    img = self.load_image(filename)
  File "~/development/github/Minecraft-Overviewer/overviewer_core/textures.py", line 338, in load_image
    img = Image.open(buffer).convert("RGBA")
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 679, in convert
    self.load()
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 189, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 385, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder zip not available
```

**Comment by CounterPillow** [comment]
Judging from past issues, the solution for this apparently is to install Pillow from Homebrew instead, because PIL is broken on OS X for some reason. Make sure to then also set the `PIL_INCLUDE_DIR` to Pillow's Imaging.h etc. headers, and rebuild. (`./setup.py clean && ./setup.py build`)

**Comment by benjaminapetersen** [comment]
Homebrew is preferrable anyway, tho I wonder why its broken.  Ok, I'll give that a shot later & see if it ends up in a better place.
