### ISSUE TITLE
Error when rendering JPG map

### ISSUE THREAD

**Issue by AMGitsKriss** [overviewer/Minecraft-Overviewer#1428]
**IOError: cannot write mode RGBA as JPEG**

It's a fresh install, using an existing config on Windows. My guess is a deprecated function is being called in the plugin that was recently removed. Has this come up before?

```
2018-01-26 22:43:55  Preprocessing...
2018-01-26 22:45:48 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 624, in <module>
  File "overviewer.py", line 550, in main
  File "overviewer_core\assetmanager.py", line 84, in initialize
  File "overviewer_core\assetmanager.py", line 149, in _output_assets
  File "site-packages\PIL\Image.py", line 1893, in save
  File "site-packages\PIL\JpegImagePlugin.py", line 604, in _save
IOError: cannot write mode RGBA as JPEG
```

**Comment by DanielSpacek** [comment]
I have same problem, same errors.

Version is overviewer-win64-0.12.204.zip

**Comment by kevinwchang** [comment]
This seems to have started with Pillow 4.2.0 no longer allowing RGBA images to be saved as JPEG (as the error message shows); more info in python-pillow/Pillow#2609. I have a [commit](https://github.com/kevinwchang/Minecraft-Overviewer/commit/e996bd1e476ad6d52e5aa2b190076491b474d0ae) in branch [no-rgba-jpeg](/kevinwchang/Minecraft-Overviewer/tree/no-rgba-jpeg) where I tried explicitly converting them to RGB and that seems to work for me. If it looks ok to others, I can submit a pull request.

**Comment by CounterPillow** [comment]
@kevinwchang looks okay
