### ISSUE TITLE
Overviewer on IIS - White lines on block edges

### ISSUE THREAD

**Issue by p0wd3r** [overviewer/Minecraft-Overviewer#1452]
![capture](https://user-images.githubusercontent.com/5797238/39952576-fcfe2012-5556-11e8-99e5-34c25db57dd6.PNG)

Windows 2012 r2 running IIS.  I've tried using v12.215, v12.254 x64 and v12.254 x32

That specific render is done with the following config settings.

`
nice_night = [Base(), EdgeLines(opacity=0.5), SmoothLighting(night=True, color=True)]

renders["WorldNightNorth"] = {
        "world": "World",
        "title": "Night Time",
        "rendermode": nice_night,
        "dimension": "overworld",
        "markers": markerList,
        "manualpois": townList,
}
`
I made the "nice_night" (slightly brighter) because the same thing shows up with the default "smooth_night" and any other rendermode for night time, so I wanted to make sure I wasn't doing something wrong.  This also happens with cave renders, as well as pretty much any other mode, but is only visible when the block is dim.  I saw a similar issue (#1370 ) where he was able to resolve the issue with a pillow update, I don't know how I can do the same with IIS.

EDIT:
I forgot to mention, I've tried a few different texture packs, including the default one, and the issue remains.  :(

**Comment by CounterPillow** [comment]
This isn't an issue with the webserver, this looks more like it's an issue with you using an overviewer version older that 12.254. Please update to that, and then **completely rerender your map**.

**Comment by p0wd3r** [comment]
As I mentioned in the post, I've tried v12.215, v12.254x64, and v12.254x32.

Here is an output from the console.
**D:\MineCraft\overviewer-new>overviewer.exe -V
Minecraft Overviewer 0.12.254 (b9be8f8)
built on Sun May 06 18:00:52 2018
D:\MineCraft\overviewer-new>**

If there is another 12.254, I'm more than happy to try that one as well.

**Comment by p0wd3r** [comment]
I also made this simple config...

`worlds["p42 Home World"] = "D:\MineCraft\Worlds\MOSZSWYTIE\p42 Home World"
outputdir = "D:\wwwroot\mcmaps"
texturepath = "D:\\MineCraft\\overviewer\\textures\\"
world = "p42 Home World"

#nice_night = [Base(), EdgeLines(opacity=0.5), SmoothLighting(night=True, color=True)]

renders["p42HomeWorldNightNorth"] = {
        "world": "p42 Home World",
        "title": "Night Time",
        "rendermode": smooth_night,
        "dimension": "overworld",
}
`
Here's the result

![capture1](https://user-images.githubusercontent.com/5797238/39963541-2ff257f2-562b-11e8-92de-67ccf884f644.PNG)

**Comment by CounterPillow** [comment]
>As I mentioned in the post, I've tried v12.215, v12.254x64, and v12.254x32.

Yes, but did you completely re-render the map inbetween switching versions? With `--forcerender`?

**Comment by p0wd3r** [comment]
Yes, I also deleted all content in the output directory to make sure that nothing was polluting it.  It is a test map with little more than a first join to create it.  I'm also having troubles with markers, chests, signs, mob spawners, etc seem to not be found, but players and my customer town markers are working fine, but I'll open a separate thing about that.  I assume the marker issue is something I need to tweak in my config, but this line issue seems to be something I can't resolve.  :(

**Comment by DutchFlander** [comment]
Hi,

I used to render maps on debian only, so I have no idea how is it in windows, but after long-long searching I've find the cause of this annoying phenomena.
In linux the Pillow has to be downgraded!
The last version that could render the tiles properly with smooth rendering without any white lines was Pillow<3.1.2.

If you can downgrade it on windows, I'm sure it will solve your issue.

Kind regards,
Dutch

**Comment by p0wd3r** [comment]
Thank you for that, it matches what the other person was saying.  I found an old version of what I assumed to be Pillow (PIL._imaging.pyd, PIL._imagingft.pyd, and PIL._imagingtk.pyd) in an archive of overviewer-0.12.158.  After replacing those files, I get this error.
```
D:\MineCraft\overviewer>overviewer.exe --config=tacos.py
D:\MineCraft\overviewer\PIL\Image.py:82: RuntimeWarning: The _imaging extension
was built for another version of Pillow or PIL:
Core version: 4.0.0
Pillow version: 5.1.0
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\pip-install-pneg9z\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 396, in load_module
  File "overviewer_core\textures.py", line 25, in <module>
  File "c:\users\admini~1\appdata\local\temp\pip-install-pneg9z\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\PIL\Image.py", line 67, in <module>
ImportError: The _imaging extension was built for another version of Pillow or P
IL:
Core version: 4.0.0
Pillow version: 5.1.0

D:\MineCraft\overviewer>
```

I get a similar error when I try other versions.  Seems that Pillow is there, but since I didn't install Python, nor any extensions, I don't know how to fix that.  If that is indeed the issue, I assume it would have to be recompiled for Windows with the older Pillow in there? (not a programmer, pardon my simplification and use of buzz words)

**Comment by CounterPillow** [comment]
Pillow should no longer be downgraded, the bug should've been fixed in theory. You can safely ignore DutchFlandre's advice.

>I assume it would have to be recompiled for Windows with the older Pillow in there?

Yes, the ABI is different between these versions and you can't just copypaste files in there.

**Comment by DutchFlander** [comment]
CounterPillow, does this mean I should give a try to a new generation with pillow updated to the latest (5.1.0)?

**Comment by p0wd3r** [comment]
Figured as much, worth a shot though, if nothing else to get an error output.  hahaha

If you are willing to make a Windows package with the old version, I would be happy to test it.  If it is more work than it sounds, I'll understand if you didn't want to.  I can live with the dots, but an issue is an issue.  I'll keep poking it from my side though.  :)

**Comment by CounterPillow** [comment]
@DutchFlander 

>Should a separate ticket be opened for this issue?

No, because this isn't an Overviewer bug -- it's your build using headers of a newer Pillow, and a library version of an older Pillow, or the other way around, which leads to an ABI incompatibility which in turn leads to a segmentation fault.

**Comment by DutchFlander** [comment]
@CounterPillow 

> Try pointing `PIL_INCLUDE_DIR` to a copy of the 5.1.0 pillow headers.

Can you be more specific? I don't speak python unfortunately and I just managed to install, upgrade and downgrade the pillow using pip. Where this `PIL_INCLUDE_DIR `should be configured? I couldn't find it in the overviewer.py file, I guess, it is somewhere else.

Thanks in advance,
Dutch

**Comment by CounterPillow** [comment]
@DutchFlander it's an environment variable used during build.

First, clean your build directory:
```
./setup.py clean
```

Next, find where in your Pillow source download the `Imaging.h` and `ImPlatform.h` files are. It should be in `src/libImaging/`. Remember the absolute path to the location of those files.

Then, using that path, set the `PIL_INCLUDE_DIR` variable while building:
```
PIL_INCLUDE_DIR=/path/from/before/src/libImaging/ ./setup.py build
```

And you're done.
