### ISSUE TITLE
Segmentation fault on "Generating textures"

### ISSUE THREAD

**Issue by damn-simple-scripts** [overviewer/Minecraft-Overviewer#1463]
Hi,

I've troubles running overviewer.

My configuration:
```python
worlds["survival"] = "/opt/mc/world"

renders["normalrender"] = {
    "world": "survival",
    "title": "Normal Render of My World",
}

#renders["survivalday"] = {
#    "world": "survival",
#    "title": "Survival Daytime",
#    "rendermode": smooth_lighting,
#    "dimension": "overworld",
#}

#renders["survivalnight"] = {
#    "world": "survival",
#    "title": "Survival Nighttime",
#    "rendermode": smooth_night,
#    "dimension": "overworld",
#}

#renders["survivalnether"] = {
#    "world": "survival",
#    "title": "Survival Nether",
#    "rendermode": nether_smooth_lighting,
#    "dimension": "nether",
#}

outputdir = "/var/www/html/mc"
#texturepath = "/opt/mc/photo_realism_1.12.2.zip"
```

the script I use to invoke overviewer:
```bash
#!/bin/bash

#wget https://s3.amazonaws.com/Minecraft.Download/versions/1.12/1.12.jar -P ~/.minecraft/versions/1.12/

overviewer.py  --check-version
overviewer.py  --check-tiles -c /opt/mc/overviewer.conf -v
```

The output I resveive:
```
2018-06-18 20:44:40 W You are running Overviewer as root. It is recommended that you never do this, as it is dangerous for your system. If you are running into permission errors, fix your file/directory permissions instead. Overviewer does not need access to critical system resources and therefore does not require root access.
Currently running Minecraft Overviewer 0.12.267 (39d9dba)
Latest version of Minecraft Overviewer 0.12.267 (39d9dba)
See http://overviewer.org/downloads for more information
2018-06-18 20:44:41 W You are running Overviewer as root. It is recommended that you never do this, as it is dangerous for your system. If you are running into permission errors, fix your file/directory permissions instead. Overviewer does not need access to critical system resources and therefore does not require root access.
overviewer.py:342  10814 2018-06-18 20:44:41 INFO     Welcome to Minecraft Overviewer!
overviewer.py:343  10814 2018-06-18 20:44:41 DEBUG    Current log level: 10
overviewer.py:368  10814 2018-06-18 20:44:41 INFO     Checking all tiles for updates manually.
files.py:43        10814 2018-06-18 20:44:41 DEBUG    Detected that chmods work in '/var/www/html/mc'
files.py:59        10814 2018-06-18 20:44:41 DEBUG    Detected that overwriting renames work in '/var/www/html/mc'
assetmanager.py:61 10814 2018-06-18 20:44:41 DEBUG    Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 53, in __init__
    with open(config_loc) as c:
IOError: [Errno 2] No such file or directory: '/var/www/html/mc/overviewerConfig.js'

assetmanager.py:72 10814 2018-06-18 20:44:41 DEBUG    Preferred enoding set to: UTF-8
overviewer.py:462  10814 2018-06-18 20:44:41 DEBUG    Found the following render thing: OrderedDict([('manualpois', []), ('minzoom', 0), ('rerenderprob', 0.0), ('showlocationmarker', True), ('poititle', 'Markers'), ('title', 'Normal Render of My World'), ('markers', []), ('bgcolor', (26, 26, 26, 0)), ('showspawn', True), ('northdirection', 0), ('defaultzoom', 1), ('imgformat', 'png'), ('base', ''), ('world', '/opt/mc/world'), ('optimizeimg', []), ('imgquality', 95), ('overlay', []), ('rendermode', [<overviewer_core.rendermodes.Base object at 0x7f7be3c71a50>, <overviewer_core.rendermodes.EdgeLines object at 0x7f7be3c71ad0>]), ('dimension', ('default', 0)), ('renderchecks', 1), ('worldname_orig', 'survival')])
world.py:275       10814 2018-06-18 20:44:41 DEBUG    regiondir is '/opt/mc/world/region'
world.py:276       10814 2018-06-18 20:44:41 DEBUG    rel is 'region'
world.py:288       10814 2018-06-18 20:44:41 DEBUG    Scanning regions.  Type is None
world.py:549       10814 2018-06-18 20:44:41 DEBUG    regiondir is /opt/mc/world/region, has type None
world.py:301       10814 2018-06-18 20:44:41 DEBUG    Done scanning regions
overviewer.py:485  10814 2018-06-18 20:44:41 INFO     Generating textures...
./run_overviewer.sh: line 6: 10814 Segmentation fault      overviewer.py --check-tiles -c /opt/mc/overviewer.conf -v
```

the directory `/var/www/html/mc/` is empty! Ans since I'm currently running the script as root, permissions sould not be any issue.

After reading issue #1435 I run the programm again in gdb:
```
gdb python
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run /usr/bin/overviewer.py  --check-tiles -c /opt/mc/overviewer.conf -v
Starting program: /usr/bin/python /usr/bin/overviewer.py  --check-tiles -c /opt/mc/overviewer.conf -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2018-06-18 20:39:47 W You are running Overviewer as root. It is recommended that you never do this, as it is dangerous for your system. If you are running into permission errors, fix your file/directory permissions instead. Overviewer does not need access to critical system resources and therefore does not require root access.
overviewer.py:342  5559 2018-06-18 20:39:47 INFO     Welcome to Minecraft Overviewer!
overviewer.py:343  5559 2018-06-18 20:39:47 DEBUG    Current log level: 10
overviewer.py:368  5559 2018-06-18 20:39:47 INFO     Checking all tiles for updates manually.
files.py:43        5559 2018-06-18 20:39:47 DEBUG    Detected that chmods work in '/var/www/html/mc'
files.py:59        5559 2018-06-18 20:39:47 DEBUG    Detected that overwriting renames work in '/var/www/html/mc'
assetmanager.py:61 5559 2018-06-18 20:39:47 DEBUG    Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 53, in __init__
    with open(config_loc) as c:
IOError: [Errno 2] No such file or directory: '/var/www/html/mc/overviewerConfig.js'

assetmanager.py:72 5559 2018-06-18 20:39:47 DEBUG    Preferred enoding set to: UTF-8
overviewer.py:462  5559 2018-06-18 20:39:47 DEBUG    Found the following render thing: OrderedDict([('manualpois', []), ('minzoom', 0), ('rerenderprob', 0.0), ('showlocationmarker', True), ('poititle', 'Markers'), ('title', 'Normal Render of My World'), ('markers', []), ('bgcolor', (26, 26, 26, 0)), ('showspawn', True), ('northdirection', 0), ('defaultzoom', 1), ('imgformat', 'png'), ('base', ''), ('world', '/opt/mc/world'), ('optimizeimg', []), ('imgquality', 95), ('overlay', []), ('rendermode', [<overviewer_core.rendermodes.Base object at 0x7ffff16bda10>, <overviewer_core.rendermodes.EdgeLines object at 0x7ffff16bda90>]), ('dimension', ('default', 0)), ('renderchecks', 1), ('worldname_orig', 'survival')])
world.py:275       5559 2018-06-18 20:39:47 DEBUG    regiondir is '/opt/mc/world/region'
world.py:276       5559 2018-06-18 20:39:47 DEBUG    rel is 'region'
world.py:288       5559 2018-06-18 20:39:47 DEBUG    Scanning regions.  Type is None
world.py:549       5559 2018-06-18 20:39:47 DEBUG    regiondir is /opt/mc/world/region, has type None
world.py:301       5559 2018-06-18 20:39:47 DEBUG    Done scanning regions
overviewer.py:485  5559 2018-06-18 20:39:47 INFO     Generating textures...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff63c5900 in alpha_over_full () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
(gdb) gt
Undefined command: "gt".  Try "help".
(gdb) bt
#0  0x00007ffff63c5900 in alpha_over_full () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
#1  0x00007ffff63c5a88 in alpha_over_wrap () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
#2  0x000055555564901a in PyEval_EvalFrameEx ()
#3  0x000055555564dd72 in PyEval_EvalFrameEx ()
#4  0x000055555564dd72 in PyEval_EvalFrameEx ()
#5  0x00005555556468ca in PyEval_EvalCodeEx ()
#6  0x000055555564e7d3 in PyEval_EvalFrameEx ()
#7  0x00005555556468ca in PyEval_EvalCodeEx ()
#8  0x00005555556461e9 in PyEval_EvalCode ()
#9  0x0000555555676bdf in ?? ()
#10 0x0000555555671952 in PyRun_FileExFlags ()
#11 0x0000555555670dcd in PyRun_SimpleFileExFlags ()
#12 0x000055555562058b in Py_Main ()
#13 0x00007ffff7a05b97 in __libc_start_main (main=0x55555561fef0 <main>, argc=6, argv=0x7fffffffe198,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe188)
    at ../csu/libc-start.c:310
#14 0x000055555561fe0a in _start ()
```

I also tried specifiing the ressource-pack, did not work...

Some version-info to my system:
```
root@Ubuntu-1704-zesty-64-minimal ~/Downloads # uname -a
Linux Ubuntu-1704-zesty-64-minimal 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@Ubuntu-1704-zesty-64-minimal ~/Downloads # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

**Comment by damn-simple-scripts** [comment]
Solution found:
```
sudo pip install 'Pillow<4.3.0'
```
As suggested by SaintFenix in #1455

is a duplicate of #1455 #1449 and I think also #1423

sorry for all the fuzz, bute the issue I investigated, did not mention the command to resolve the problem.
