### ISSUE TITLE
minecraft113: genPOI fails on chunks without TileEntities tag

### ISSUE THREAD

**Issue by jobe1986** [overviewer/Minecraft-Overviewer#1480]
As per subject. Error that occurs as a result:
```
2018-09-15 20:41:09  Looking for entities in <RegionSet regiondir='/home/minecraft/server-backup/world/region'>
*******************************************************************************
2018-09-15 20:41:09 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/home/minecraft/overviewer/bin/overviewer.py", line 628, in <module>
    ret = main()
  File "/home/minecraft/overviewer/bin/overviewer.py", line 131, in main
    g.genPOI.main()
  File "/home/minecraft/overviewer/bin/overviewer_core/aux_files/genPOI.py", line 524, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/home/minecraft/overviewer/bin/overviewer_core/aux_files/genPOI.py", line 168, in handleEntities
    for poi in itertools.chain(data['TileEntities'], data['Entities']):
KeyError: 'TileEntities'
```

**Comment by Charlweed** [comment]
Is this bug counted against the branch in the review?

**Comment by jobe1986** [comment]
Well I am experiencing this issue with the minecraft113 branch of overviewer, and currently using the latest revision of said branch.

**Comment by mtoensing** [comment]
I get this error if I try that:
```

2018-11-02 20:19:52 W Skipping bad player dat file '._27f7c1b4-6874-4134-b71a-bc009f432dfe.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._da009055-f659-42d8-bc15-7afe00a03eb5.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._badf9c30-de6f-4d6c-a920-dffe32ba7b45.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._0c6d6590-312a-47cc-ac71-1beafc161d02.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._4bb7526d-1fae-4e13-8a34-db725f8c5157.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._1d42c171-e875-416c-8878-035aa73f781d.dat'
2018-11-02 20:19:53 W Skipping bad player dat file '._8d2bbbfa-1ccb-46ec-8ec0-235fef1870c4.dat'
2018-11-02 20:19:54 W Skipping bad player dat file '._db62f736-2382-4467-a708-cb9009cf017e.dat'
2018-11-02 20:19:54 W Unable to get player name for UUID 6c137f8a-f57e-3176-a96c-8340f9d830cd
2018-11-02 20:19:54 W Skipping bad player dat file '._c5ff2bdf-1fcf-4141-a39e-4ff77c9b6a82.dat'
2018-11-02 20:19:54 W Skipping bad player dat file '._9dcc1d41-b398-441b-b07a-d09268717165.dat'
Traceback (most recent call last):
  File "/tmp/overviewer/genPOI.py", line 567, in <module>
    main()
  File "/tmp/overviewer/genPOI.py", line 534, in main
    handlePlayers(worldpath, list(worldpath_filters), markers)
  File "/tmp/overviewer/genPOI.py", line 349, in handlePlayers
    if data['Dimension'] == dimension:
  File "/tmp/overviewer/genPOI.py", line 259, in __getitem__
    return super(PlayerDict, self).__getitem__(item)
KeyError: 'Dimension'
```

**Comment by CounterPillow** [comment]
@mtoensing 
If by "maintained" you mean "will anyone with write-access to the repository write a fix for this bug?" then the answer is a pretty resounding "no", because everyone with write access has stopped playing Minecraft years ago and is now busy doing more interesting things with their free time. That doesn't mean nobody's going to merge it if you submit a pull request, though.

That being said, I will continue to pay for the server running overviewer.org.

**Comment by CounterPillow** [comment]
Surprise! I lied, and went ahead and (maybe) fixed this anyway. This was a two line change, but I didn't test whether this fixes worlds that previously crashed. Could somebody in here try it out now with the latest minecraft113 branch who had it crash previously?

Should address both @jobe1986 and @mtoensing's backtraces.

**Comment by mtoensing** [comment]
I‘ll try!

**Comment by mtoensing** [comment]
Works! Thanks! 
![image](https://user-images.githubusercontent.com/136737/48675032-bcf84400-eb53-11e8-9604-994283c260a2.png)

**Comment by mtoensing** [comment]
But I needed to set the parameter --skip-scan to get this to work.

**Comment by mtoensing** [comment]
```
Step 14/14 : ENTRYPOINT ["/bin/bash", "-c","/tmp/overviewer/genPOI.py --config=/tmp/config/config.py"]
 ---> Using cache
 ---> 899927ed4de3
Successfully built 899927ed4de3
Successfully tagged overviewer113:latest
2018-11-18 18:39:09  Looking for entities in <RegionSet regiondir='/tmp/world/region'>
2018-11-18 18:39:09  Buckets has 20045 entries
2018-11-18 18:39:09  Buckets has 19192 entries
Traceback (most recent call last):
  File "/tmp/overviewer/genPOI.py", line 567, in <module>
    main()
  File "/tmp/overviewer/genPOI.py", line 524, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/tmp/overviewer/genPOI.py", line 200, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
overviewer_core.world.ChunkDoesntExist: Chunk -95,-115 doesn't exist

```

**Comment by CounterPillow** [comment]
There, this should fix it.

**Comment by mtoensing** [comment]
Does not work:

```
bob@8289cd23702f:/tmp/overviewer$ /tmp/overviewer/overviewer.py --config=/tmp/config/config.py --genpoi
2018-11-26 13:31:26  Looking for entities in <RegionSet regiondir='/tmp/world/region'>
2018-11-26 13:31:27  Buckets has 20045 entries
2018-11-26 13:31:27  Buckets has 19192 entries
2018-11-26 13:31:29 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/tmp/overviewer/overviewer.py", line 628, in <module>
    ret = main()
  File "/tmp/overviewer/overviewer.py", line 131, in main
    g.genPOI.main()
  File "/tmp/overviewer/overviewer_core/aux_files/genPOI.py", line 526, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/tmp/overviewer/overviewer_core/aux_files/genPOI.py", line 202, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'TileEntities'

```

**Comment by CounterPillow** [comment]
Okay, just pushed a fix for that.

**Comment by mtoensing** [comment]
```
bob@e729ccf41df0:/tmp/overviewer$ /tmp/overviewer/genPOI.py --config=/tmp/config/config.py
2018-11-26 14:15:49  Looking for entities in <RegionSet regiondir='/tmp/world/region'>
2018-11-26 14:15:49  Buckets has 20045 entries
2018-11-26 14:15:49  Buckets has 19192 entries
Traceback (most recent call last):
  File "/tmp/overviewer/genPOI.py", line 567, in <module>
    main()
  File "/tmp/overviewer/genPOI.py", line 524, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/tmp/overviewer/genPOI.py", line 200, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
overviewer_core.world.ChunkDoesntExist: Chunk -95,-115 doesn't exist
```

Still getting this. Did you miss a commit?

**Comment by CounterPillow** [comment]
That is the correct way to discard an exception. According to your line numbers, your issue is that you didn't actually update overviewer; you're running without my fixes.

**Comment by mtoensing** [comment]
isn't this the commit you pushed to fix this? https://github.com/overviewer/Minecraft-Overviewer/commit/38bc400b2fb87d9c2b581293d9cc4f86ee4b1979 I pulled the recent version of the 113 branch

**Comment by mtoensing** [comment]
Double checked. If this is the commit I definitely have the most recent branch minecraft113 pulled from the repository.

**Comment by CounterPillow** [comment]
If the version you're running were the one in that commit, handleEntities would fail on line 202, not 200.

**Comment by mtoensing** [comment]
This is the correct version, right? https://github.com/overviewer/Minecraft-Overviewer/blob/minecraft113/overviewer_core/aux_files/genPOI.py

**Comment by mtoensing** [comment]
Sorry, you are right. My fault. I used the wrong docker tag.

**Comment by mtoensing** [comment]
Hi, 

today I tried to generate POIs with the 113 Branch: 

`2019-01-17 18:15:26  Welcome to Minecraft Overviewer!
2019-01-17 18:15:26  Generating textures...
2019-01-17 18:16:10  Preprocessing...
2019-01-17 18:16:55  Rendering 0 total tiles.
100% [===============================================================================================] 0 0.00t/s Time: 00h 00m 00s

2019-01-17 18:16:55  Rendering complete!
2019-01-17 18:16:56  Your render has been written to '/tmp/export', open index.html to view it
2019-01-17 18:16:57  Looking for entities in <RegionSet regiondir='/tmp/world/world/region'>
2019-01-17 18:16:57  Buckets has 12845 entries
2019-01-17 18:16:57  Buckets has 12299 entries
2019-01-17 18:17:09  Found 0 markers in thread 102 so far at 250 chunks
Traceback (most recent call last):
  File "/tmp/overviewer/genPOI.py", line 569, in <module>
    main()
  File "/tmp/overviewer/genPOI.py", line 526, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/tmp/overviewer/genPOI.py", line 202, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'Items'`

Any idea? 

This is my config: 

`def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def chestFilter(poi):
    if poi['id'] == 'Chest':
        return "Chest with %d items" % len(poi['Items'])


thingsToMaker = [
    dict(name="Players", filterFunction=playerIcons),
    dict(name="PlayerSpawn", filterFunction=playerSpawns),
    dict(name="Signs", filterFunction=signFilter),
    dict(name="Chests", filterFunction=chestFilter),
]


renders["day"] = {
    'world': 'pudel',
    'title': 'Day',
    'rendermode': 'normal',
    "dimension": "overworld",
    'crop': (-200, -600, -100, -500),
    'markers': thingsToMaker
}`
