### ISSUE TITLE
Fails if Output is on a Samba Share

### ISSUE THREAD

**Issue by Enverex** [overviewer/Minecraft-Overviewer#1484]
Running on a Linux client with a mounted Samba share (a Linux server) causes the generator to throw an error.

```
[06:27:21] arcade@arcade ~/Games/Minecraft-ATM3 $ overviewer.py "Acai" /mnt/emerald/Web/http/mcmap/
2018-09-27 18:27:25  Welcome to Minecraft Overviewer!
2018-09-27 18:27:25 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 624, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 427, in main
    assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
  File "/usr/lib/python2.7/site-packages/overviewer_core/assetmanager.py", line 48, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "/usr/lib/python2.7/site-packages/overviewer_core/files.py", line 28, in get_fs_caps
    "rename_works": does_rename_work(dir_to_test)
  File "/usr/lib/python2.7/site-packages/overviewer_core/files.py", line 61, in does_rename_work
    open(f1.name, 'w').close()
  File "/usr/lib/python2.7/tempfile.py", line 440, in __exit__
    self.close()
  File "/usr/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
OSError: [Errno 2] No such file or directory: '/mnt/emerald/Web/http/mcmap/tmpMvkQBJ'
```

Works fine if I use a local folder instead. Permissions are fine on the share, I can (as this user) create, move, delete files and folders, etc.

**Comment by CounterPillow** [comment]
Interesting, looks like some sloppy code is running into a specific quirk of samba in this case.

We keep the filehandles of both temporary files open, but recreate one of them if the rename succeeds, before we then close that handle. In theory, this shouldn't fail. I don't even know why the second open call is calling into tempfile in `close()`.

**Comment by CounterPillow** [comment]
can you try this untested patch and tell me whether this fixes the issue?

```patch
diff --git a/overviewer_core/files.py b/overviewer_core/files.py
index 15647fe..ea68cb1 100644
--- a/overviewer_core/files.py
+++ b/overviewer_core/files.py
@@ -47,18 +47,22 @@ def does_chmod_work(dir_to_test):
     return chmod_works
 
 def does_rename_work(dir_to_test):
-    with tempfile.NamedTemporaryFile(dir=dir_to_test) as f1:
-        with tempfile.NamedTemporaryFile(dir=dir_to_test) as f2:
-            try:
-                os.rename(f1.name,f2.name)
-            except OSError:
-                renameworks = False
-                logging.debug("Detected that overwriting renames do NOT work in %r" % dir_to_test)
-            else:
-                renameworks = True
-                logging.debug("Detected that overwriting renames work in %r" % dir_to_test)
-                # re-make this file so it can be deleted without error
-                open(f1.name, 'w').close()
+    f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
+    f2 = tempfile.NamedTemporaryFile(dir=dir_to_test)
+    try:
+        os.rename(f1.name,f2.name)
+    except OSError:
+        renameworks = False
+        logging.debug("Detected that overwriting renames do NOT work in %r" % dir_to_test)
+    else:
+        renameworks = True
+        logging.debug("Detected that overwriting renames work in %r" % dir_to_test)
+    finally:
+        try:
+            f1.close()
+        except OSError:
+            pass
+        f2.close()
     return renameworks
 
 ## useful recursive copy, that ignores common OS cruft
```

**Comment by Enverex** [comment]
Still failing unfortunately.

```
[10:28:49] arcade@arcade ~/Games/Minecraft-ATM3 $ overviewer.py "Arceus" /mnt/emerald/Web/http/mcmap
2018-09-28 10:29:25  Welcome to Minecraft Overviewer!
2018-09-28 10:29:25 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 628, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 427, in main
    assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
  File "/usr/lib/python2.7/site-packages/overviewer_core/assetmanager.py", line 48, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "/usr/lib/python2.7/site-packages/overviewer_core/files.py", line 28, in get_fs_caps
    "rename_works": does_rename_work(dir_to_test)
  File "/usr/lib/python2.7/site-packages/overviewer_core/files.py", line 65, in does_rename_work
    f2.close()
  File "/usr/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
OSError: [Errno 2] No such file or directory: '/mnt/emerald/Web/http/mcmap/tmpBR9NEI'
```

**Comment by Enverex** [comment]
Seems unlikely; If I tell it to output to my NVMe drive (which when benched clocked in at ~2GB/s) it doesn't happen.

There's a lot of chatter on the Python forums that tempfile.py works differently depending on the OS and filesystem so it seems to be doing something a bit weird given that it's a network share and not a local disk. Apparently the files created by NamedTemporaryFile are automatically deleted in some instances and not others, so maybe some of the arguments for that function need to be set explicitly in case they're doing something different in different situations here (e.g. the second command being to auto-delete the file).

**Comment by cds133** [comment]
Just wanted to reseruct to let you know the issue persists. And the fix from Pillow and Enverex's tweak still seem to resolve it. Ubuntu 18.04, built from source.

**Comment by CounterPillow** [comment]
I've worked around this now in git master
