### ISSUE TITLE
Generating POI markers of signs and chests fails with KeyError: 'Items'

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1509]
Hi, 

today I tried to generate POIs with the 113 Branch: 

```shell
2019-01-17 18:15:26  Welcome to Minecraft Overviewer!
2019-01-17 18:15:26  Generating textures...
2019-01-17 18:16:10  Preprocessing...
2019-01-17 18:16:55  Rendering 0 total tiles.
100% [===============================================================================================] 0 0.00t/s Time: 00h 00m 00s

2019-01-17 18:16:55  Rendering complete!
2019-01-17 18:16:56  Your render has been written to '/tmp/export', open index.html to view it
2019-01-17 18:16:57  Looking for entities in <RegionSet regiondir='/tmp/world/world/region'>
2019-01-17 18:16:57  Buckets has 12845 entries
2019-01-17 18:16:57  Buckets has 12299 entries
2019-01-17 18:17:09  Found 0 markers in thread 102 so far at 250 chunks
Traceback (most recent call last):
  File "/tmp/overviewer/genPOI.py", line 569, in <module>
    main()
  File "/tmp/overviewer/genPOI.py", line 526, in main
    handleEntities(rset, config, options.config, list(rset_filters), markers)
  File "/tmp/overviewer/genPOI.py", line 202, in handleEntities
    results = pool.map(parseBucketChunks, ((buck, rset, filters) for buck in buckets))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'Items'`
```

Any idea? 

This is my config: 

```python
def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def chestFilter(poi):
    if poi['id'] == 'Chest':
        return "Chest with %d items" % len(poi['Items'])


thingsToMaker = [
    dict(name="Players", filterFunction=playerIcons),
    dict(name="PlayerSpawn", filterFunction=playerSpawns),
    dict(name="Signs", filterFunction=signFilter),
    dict(name="Chests", filterFunction=chestFilter),
]


renders["day"] = {
    'world': 'pudel',
    'title': 'Day',
    'rendermode': 'normal',
    "dimension": "overworld",
    'crop': (-200, -600, -100, -500),
    'markers': thingsToMaker
}`
```

**Comment by keithwissing** [comment]
It looks like generated chests that have not yet been opened do not have 'Items' yet.

``` python
def chestFilter(poi):
    if poi['id'] == "Chest" or poi['id'] == 'minecraft:chest':
        if 'Items' in poi:
            return "Chest with %d items" % len(poi['Items'])
        else:
            return 'Chest'

```
