### ISSUE TITLE
Oxipng not found

### ISSUE THREAD

**Issue by demosjarco** [overviewer/Minecraft-Overviewer#1525]
I have imported oxipng and setup the config correctly, it also used to work before (the version just before 0.13) but now it just won't start render because it can't find oxipng even though it is in the same folder as overviewer. This is running overviewer 0.13.6.

~~~~
overviewer --config=config.py --genpoi
2019-03-01 15:26:41 E An error was encountered with your configuration. See the info below.
Traceback (most recent call last):
  File "overviewer_core\aux_files\genPOI.py", line 462, in main
  File "overviewer_core\configParser.py", line 130, in get_validated_config
  File "overviewer_core\settingsValidators.py", line 340, in configDictValidator
  File "overviewer_core\settingsValidators.py", line 278, in v
  File "overviewer_core\settingsValidators.py", line 343, in configDictValidator
  File "overviewer_core\settingsValidators.py", line 166, in validateOptImg
  File "overviewer_core\optimizeimages.py", line 48, in check_availability
Exception: Optimization programs '['oxipng', 'oxipng.exe']' were not found!
~~~~

![image](https://user-images.githubusercontent.com/1209494/53670349-a88a1400-3c37-11e9-9723-69edf29100e6.png)
[config.py.txt](https://github.com/overviewer/Minecraft-Overviewer/files/2921310/config.py.txt)
(I named it .txt so github would allow upload)

**Comment by demosjarco** [comment]
woops wrong button

**Comment by CounterPillow** [comment]
I've tried to reproduce this and concluded it's not Overviewer's fault, but user error. The trick with placing oxipng into the same directory as overviewer.exe only works if you are running overviewer.exe from within its directory as the current working directory, e.g. `C:\Users\Bob\Desktop\overviewer>overviewer.exe -c "D:\myawesomeworld.py"`. If `oxipng.exe` is not within your current working directory, you'll need to add it to your `%PATH%` instead.

If you see a sentence in the docs telling you that throwing things next to overviewer.exe works in all cases, please let me know so I can correct them.
