### ISSUE TITLE
SkyLight Error?

### ISSUE THREAD

**Issue by astrolink2000** [overviewer/Minecraft-Overviewer#1546]
2019-03-21 23:30:12  Welcome to Minecraft Overviewer!
2019-03-21 23:30:12 W Unkown region type in 'C:\\Users\\Heath\\Desktop\\19w12b\\world\\DIM-1\\poi'
2019-03-21 23:30:12 W Unkown region type in 'C:\\Users\\Heath\\Desktop\\19w12b\\world\\DIM1\\poi'
2019-03-21 23:30:12 W Unkown region type in 'C:\\Users\\Heath\\Desktop\\19w12b\\world\\poi'
2019-03-21 23:30:12  Generating textures...
2019-03-21 23:30:20 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 637, in <module>
  File "overviewer.py", line 546, in main
  File "overviewer_core\world.py", line 218, in find_true_spawn
  File "overviewer_core\world.py", line 1210, in get_chunk
KeyError: 'SkyLight'

**Comment by CounterPillow** [comment]
The new snapshots are not yet supported.

**Comment by CounterPillow** [comment]
Fixed in bc322fa3e43eca493acb72e58e259e60926badd4
