### ISSUE TITLE
Error when installed read-only

### ISSUE THREAD

**Issue by lheckemann** [overviewer/Minecraft-Overviewer#1611]
I'm [packaging](https://github.com/NixOS/nixpkgs/pull/62949) overviewer in nixpkgs. Packages are installed read-only, as is usual when using sensible package managers. However, this seems to confuse Overviewer, as it copies the permissions on images like `signpost_icon.png` then later tries to overwrite them. As a hacky workaround, I've just [disabled copying permissions completely](https://github.com/NixOS/nixpkgs/pull/62949/commits/3644b8a873370b2ad87cc2954408acc3c0a67125), but a better way would be nice.

```
$ ./result/bin/overviewer.py ~/.minecraft/saves/New\ World/ ~/www
2019-07-12 21:12:00  Welcome to Minecraft Overviewer!
2019-07-12 21:12:00  Generating textures...
2019-07-12 21:12:09  Preprocessing...
2019-07-12 21:12:09 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/lib/python3.7/site-packages/overviewer_core/files.py", line 75, in mirror_dir
    shutil.copyfile(os.path.join(src, entry), os.path.join(dst, entry))
  File "/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/steam/www/signpost_icon.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/bin/.overviewer.py-wrapped", line 651, in <module>
    ret = main()
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/bin/.overviewer.py-wrapped", line 576, in main
    assetMrg.initialize(tilesets)
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/lib/python3.7/site-packages/overviewer_core/assetmanager.py", line 77, in initialize
    self._output_assets(tilesets, True)
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/lib/python3.7/site-packages/overviewer_core/assetmanager.py", line 160, in _output_assets
    self.output_noconfig()
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/lib/python3.7/site-packages/overviewer_core/assetmanager.py", line 168, in output_noconfig
    mirror_dir(global_assets, self.outputdir, capabilities=self.fs_caps)
  File "/nix/store/zhcavxl9ndplb3nwy6rkx4z6h40m9n8h-minecraft-overviewer-0.13.90/lib/python3.7/site-packages/overviewer_core/files.py", line 89, in mirror_dir
    shutil.copyfile(os.path.join(src, entry), os.path.join(dst, entry))
  File "/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/steam/www/signpost_icon.png'
```

**Comment by CounterPillow** [comment]
oh great now we have distros shipping outdated versions, can't wait for the bug reports this will generate

**Comment by lheckemann** [comment]
Awesome, thanks for the rapid fix! I'll change the bug report URL as you requested.
