### ISSUE TITLE
NumPy 1.17.0 breaks PyInstaller Windows builds

### ISSUE THREAD

**Issue by CounterPillow** [overviewer/Minecraft-Overviewer#1618]
With NumPy 1.17.0, Windows users get this nice traceback if they're trying to run our official builds:

```
>overviewer.exe
Traceback (most recent call last):
  File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\__init__.py", line 150, in <module>
  File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\random\__init__.py", line 180, in <module>
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ModuleNotFoundError: No module named 'numpy.random.common'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
```

This is likely relating to changes [in NumPy's random module done in 1.17.0](https://docs.scipy.org/doc/numpy/release.html#numpy-1-17-0-release-notes). Other users of PyInstaller [appear to be affected too](https://stackoverflow.com/questions/57264427/in-pyinstaller-why-wont-numpy-random-common-load-as-a-module).

I've submitted a temporary workaround in our build scripts in https://github.com/overviewer/Overviewer-Web/pull/37 to pin NumPy to 1.16.4 until this is either fixed upstream or we find a better workaround.

**Comment by CounterPillow** [comment]
Filed an issue with NumPy: https://github.com/numpy/numpy/issues/14163

**Comment by CounterPillow** [comment]
Worked around for now, NumPy workaround is being reviewed and this may be reported to PyInstaller from there on.
