### ISSUE TITLE
Error overviewer.py", line 650, in <module>

### ISSUE THREAD

**Issue by pardalsalcap** [overviewer/Minecraft-Overviewer#1626]
Hi, 
Posting this here just in case it helps.
I was just testing, and trying to learn how your aplication works.
The world I was trying to render is a new world that was just created for testing your aplication. Ia have just created the word and saved it.

I'm using a Mac OS Mojave up to date, Python 3.7.4, pip 19.2.2  and your latest source available

The command that i was running is:
 ./overviewer.py /Users/MYUSERNAME/Library/Application\ Support/minecraft/saves/test /Volumes/workingsd/minecraft/mapa/export/

This is the output...

2019-08-14 16:40:18  Welcome to Minecraft Overviewer!
2019-08-14 16:40:18  Generating textures...
2019-08-14 16:40:35  Preprocessing...
2019-08-14 16:40:40 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 650, in <module>
    ret = main()
  File "./overviewer.py", line 575, in main
    assetMrg.initialize(tilesets)
  File "/Volumes/workingsd/minecraft/mapa/overviewer/overviewer_core/assetmanager.py", line 76, in initialize
    self._output_assets(tilesets, True)
  File "/Volumes/workingsd/minecraft/mapa/overviewer/overviewer_core/assetmanager.py", line 160, in _output_assets
    self.output_noconfig()
  File "/Volumes/workingsd/minecraft/mapa/overviewer/overviewer_core/assetmanager.py", line 198, in output_noconfig
    fout.write(f.read())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

Am I missing something?

Thanks!

**Comment by CounterPillow** [comment]
Sounds like something corrupted your `/Volumes/workingsd/minecraft/mapa/overviewer/overviewer_core/data/js_src/overviewer.js`, maybe either due to a disk write error or an incomplete download of the Overviewer sources. Byte 37 should not be 0xb0.

**Comment by pardalsalcap** [comment]
Hi, thanks for your answer.
I have downloaded again the latest release and rebuild overviewer... everything looks good at this point. If I run ./overviewer.py it shows all the options:

`2019-08-15 01:16:25 E You must either specify --config or give me a world directory and output directory.
usage: 
overviewer.py [--rendermodes=...] [options] <World> <Output Dir>
overviewer.py --config=<config file> [options]

positional arguments:
  world                 Path or name of the world you want to render.
  output                Output directory for the rendered map.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Specify the config file to use.
  -p PROCS, --processes PROCS
                        The number of local worker processes to spawn.
                        Defaults to the number of CPU cores your computer has.
  --pid PID             Specify the pid file to use.
  --rendermodes RENDERMODES
                        If you're not using a config file, specify which
                        rendermodes to render with this option. This is a
                        comma-separated list.
  --forcerender         Force re-render the entire map.
  --check-tiles         Check each tile on disk and re-render old tiles.
  --no-tile-checks      Only render tiles that come from chunks that have
                        changed since the last render (the default).
  --check-terrain       Try to locate the texture files. Useful for debugging
                        texture problems.
  -V, --version         Display version information and then exits.
  --check-version       Fetch information about the latest version of
                        Overviewer.
  --update-web-assets   Update web assets. Will *not* render tiles or update
                        overviewerConfig.js.
  -q, --quiet           Print less output. You can specify this option
                        multiple times.
  -v, --verbose         Print more output. You can specify this option
                        multiple times.
  --simple-output       Use a simple output format, with no colors or progress
                        bars.

Other Scripts:
  These scripts may accept different arguments than the ones listed above.

  --genpoi              Run the genPOI script.
  --skip-scan           When running GenPOI, don't scan for entities.
  --skip-players        When running GenPOI, don't scan player data.

Detected saves:
World              | Playtime | Modified         | Path 
------------------ | -------- | ---------------- | ---- 
Liticraft          | 1431:08  | 2018-02-10 17:06 | /Users/danielcasasnovasbarber/Library/Application Support/minecraft/saves/Liticraft 
obsidiana-survival | 23:13    | 2016-07-29 18:36 | /Users/danielcasasnovasbarber/Library/Application Support/minecraft/saves/obsidiana-survival 
test               | 0:00     | 2019-08-15 01:15 | /Users/danielcasasnovasbarber/Library/Application Support/minecraft/saves/test `

I have compared the /Volumes/workingsd/minecraft/mapa/overviewer/overviewer_core/data/js_src/overviewer.js file with the one on your github repository and they are the same

If I run  ./overviewer.py "test" /Volumes/workingsd/minecraft/mapa/export/
It returns 

2019-08-15 01:18:39 E An error was encountered with your configuration.
2019-08-15 01:18:39 E No level.dat file in '/Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/test'. Are you sure you have the right path?

if I run ./overviewer.py /Users/danielcasasnovasbarber/Library/Application\ Support/minecraft/saves/test /Volumes/workingsd/minecraft/mapa/export/

2019-08-15 01:20:17  Welcome to Minecraft Overviewer!
2019-08-15 01:20:17  Generating textures...
2019-08-15 01:20:30  Preprocessing...
2019-08-15 01:20:33 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 650, in <module>
    ret = main()
  File "./overviewer.py", line 575, in main
    assetMrg.initialize(tilesets)
  File "/Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/assetmanager.py", line 76, in initialize
    self._output_assets(tilesets, True)
  File "/Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/assetmanager.py", line 160, in _output_assets
    self.output_noconfig()
  File "/Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/assetmanager.py", line 198, in output_noconfig
    fout.write(f.read())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

What do you think? I'm not an expert (do not asume to much) and maybe doing something wrong

Thanks in advanced

**Comment by CounterPillow** [comment]
- What does `sha1sum /Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/data/js_src/util.js` output?
- Are there any other files in `/Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/data/js_src` besides `overviewer.js` and `util.js`?

**Comment by pardalsalcap** [comment]
Hi,

MacBookdeDaniel:~ danielcasasnovasbarber$ sha1sum /Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/data/js_src/util.js
d4434615215171c8cfaa195295210e5380d1c684  /Volumes/workingsd/minecraft/mapa/Minecraft-Overviewer-0.14.64/overviewer_core/data/js_src/util.js

No, there are not any other files than the 2 files you said.

Thanks for your help

**Comment by CounterPillow** [comment]
Interesting, that sha1sum looks to be correct. This needs more investigating, preferably by someone else running macOS.

**Comment by pardalsalcap** [comment]
Thanks!
I'm on vacation now. At home I've got a windows pc, will give a try there when I go back.
I'll keep an eye on this tread to see if I can help, let me know if you need any testing done

**Comment by lomik31** [comment]
I think I've figured out what the problem is. If the overviewer folder is on a FAT disk, mac os creates duplicate files "._filename" For some reason Minecraft Overviewer tries to read them. I recommend cleaning the disk from "._" files manually or using BlueHarvest before starting the render
