### ISSUE TITLE
StructureOverlay for Pistons, Observer (Farms)

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1632]
Hi, 

we have a big problem on our server: The people are building farms and I don't know where they are. My idea is to mark groups of pistons, observers and so on on an overlay. I found this in the documentation for rails. 

http://docs.overviewer.org/en/latest/config/?highlight=rail#custom-rendermodes-and-rendermode-primitives

StructureOverlay(structures=[(((0, 0, 0, 66), (0, -1, 0, 4)), (255, 0, 0, 255)),
                             (((0, 0, 0, 27), (0, -1, 0, 4)), (0, 255, 0, 255))])

How do I find out which id pistons and observers have to mark them on the map. Maybe you have another idea or more blocks which indicate a farm?

**Comment by enaut** [comment]
I wrote that code. It was written for the old world format. The ids were the block ids given by minecraft back then. The code still works because overviewer simulates the block ids if I understood it correctly.

So if you are looking for the block ids you need to search for them in this file:
https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/src/mc_id.h

https://github.com/overviewer/Minecraft-Overviewer/blob/3498641d4ec68dc742cdff4e5cc4028b7bd3b630/overviewer_core/src/mc_id.h#L36-L45

I didn't try any of this but it should work and I hope that helps all the best.

**Comment by mtoensing** [comment]
@enaut Thank you! May I ask who the StructureOverlay works because the documentation does not give enough answers. 

I want to color pistons, sticky-pistons and observers in red. And it does matter what kind of block they have next to them. How does this work? 

```
StructureOverlay(structures=[
(((0, 0, 0, 29), (0, 0, 0, *)), (255, 0, 0, 255)),
(((0, 0, 0, 33), (0, , 0, *)), (255, 0, 0, 255)),
(((0, 0, 0, 34), (0, , 0, *)), (255, 0, 0, 255)),
(((0, 0, 0, 218), (0, , 0, *)), (255, 0, 0, 255))
])

```

This does not seem to work... I used the * for "any block"

**Comment by enaut** [comment]
If you just want to color those blocks in the overlay you only specify the blocks:

```
'rendermode': [ClearBase(),
            StructureOverlay(structures=[
				(((0, 0, 0, 29), ), (255, 0, 0, 255)),
				(((0, 0, 0, 33), ), (255, 0, 0, 255)),
				(((0, 0, 0, 34), ), (255, 0, 0, 255)),
				(((0, 0, 0, 218), ), (255, 0, 0, 255))
			]), EdgeLines()],
```
But that is actually what the minerals overlay is for! So you might want to need that the structure overlay is for mapping multiple blocks...

So you could want to color the block that is a cobblestone and has another cobbleston 15 blocks higher and another cobblestone in the x directory. Then you would write:
```
((0, 0, 0, 4), (0, 15, 0, 4), (1, 0, 0, 4), ), (255, 0, 0, 255))```

The list of blocks is extendable and you can add for example npc houses to make an overlay of npc houses. etc.

**Comment by mtoensing** [comment]
Ah, the mineral overlay is for coloring blocks without relative positions. I tried this and got that: 

```
# Railoverlay (mark all rails regardless of underlying blocks)
renders["rails"] = {
    'world': 'pudel',
    'title': 'Subway',
    "dimension": "overworld",
    'rendermode': [ClearBase(),
            StructureOverlay(structures=[
                    (66, (255, 0,   0, 255)),
                    (27, (0,   255, 0, 255)),
                    (28, (255, 255, 0, 255))
            ]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}

# Pistons, Sticky Pistons, ..... regardless of underlying blocks.
renders["farms"] = {
    'world': 'pudel',
    'title': 'Farms',
    "dimension": "overworld",
    'rendermode': [ClearBase(),
            StructureOverlay(structures=[
				(29, (255, 0, 0, 255)),
				(33, (255, 0, 0, 255)),
				(34, (255, 0, 0, 255)),
				(218, (255, 0, 0, 255))
			]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}

```

```
2019-08-20 17:46:18 E Could not render chunk -28,-44 for some reason. This is likely a render primitive option error.                           
2019-08-20 17:46:18 E Full error was:                                                                                                           
Traceback (most recent call last):                                                                                                              
  File "/tmp/overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile                                                           
    self.options['rendermode'], self.textures)                                                                                                  
TypeError: Failed to parse conditions                                                                                                           
2019-08-20 17:46:19 E Could not render chunk -28,-44 for some reason. This is likely a render primitive option error.                           
2019-08-20 17:46:19 E Full error was:                                                                                                           
Traceback (most recent call last):                                                                                                              
  File "/tmp/overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile                                                           
    self.options['rendermode'], self.textures)                                                                                                  
TypeError: Failed to parse conditions   
```

What am i doing wrong?

**Comment by mtoensing** [comment]
ok, I am not myself today: MineralOverlay and not Structure Overlay...

**Comment by mtoensing** [comment]
```
# Railoverlay
renders["rails"] = {
    'world': 'pudel',
    'title': 'Subway',
    "dimension": "overworld",
    'forcerender': True,
    'rendermode': [ClearBase(),
            MineralOverlay(minerals=[
                    (66, (255, 0,   0, 255)),
                    (27, (0,   255, 0, 255)),
                    (28, (255, 255, 0, 255))
            ]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}

# Pistons
renders["farms"] = {
    'world': 'pudel',
    'title': 'Farms',
    'forcerender': True,
    "dimension": "overworld",
    'rendermode': [ClearBase(),
            MineralOverlay(minerals=[
				(29, (255, 0, 0, 255)),
				(33, (255, 0, 0, 255)),
				(34, (255, 0, 0, 255)),
				(218, (255, 0, 0, 255))
			]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}
```

This is rendering now. I tell the world if works if the render is complete. Thank you!

**Comment by mtoensing** [comment]
No: 

```
2019-08-20 17:57:00 E Could not render chunk -28,-44 for some reason. This is likely a render primitive option error.     ] 0 0.00t/s eta ------
2019-08-20 17:57:00 E Full error was:                                                                                                           
Traceback (most recent call last):                                                                                                              
  File "/tmp/overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile                                                           
    self.options['rendermode'], self.textures)                                                                                                  
TypeError: argument 2 must be sequence of length 3, not 4                                                                                       
2019-08-20 17:57:00 E Could not render chunk -28,-44 for some reason. This is likely a render primitive option error.                           
2019-08-20 17:57:00 E Full error was:                                                                                                           
Traceback (most recent call last):                                                                                                              
  File "/tmp/overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile                                                           
    self.options['rendermode'], self.textures)                                                                                                  
TypeError: argument 2 must be sequence of length 3, not 4
```

**Comment by mtoensing** [comment]
next try: 
```

# Railoverlay
renders["rails"] = {
    'world': 'pudel',
    'title': 'Subway',
    "dimension": "overworld",
    'forcerender': True,
    'rendermode': [ClearBase(),
            MineralOverlay(minerals=[
                    (66, (255, 0, 0)),
                    (27, (255, 0, 0)),
                    (28, (255, 0, 0))
            ]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}

# Pistons
renders["farms"] = {
    'world': 'pudel',
    'title': 'Farms',
    'forcerender': True,
    "dimension": "overworld",
    'rendermode': [ClearBase(),
            MineralOverlay(minerals=[
				(29, (255, 0, 0)),
				(33, (255, 0, 0)),
				(34, (255, 0, 0)),
				(218, (255, 0, 0))
			]), EdgeLines()],
    "overlay": ["day_complete"],
    'crop': my_crop,
}

```

**Comment by mtoensing** [comment]
works! Thank you!

**Comment by mtoensing** [comment]
@enaut =( It seemed to work. But the real render result is shifted to the left by 1000 blocks: 

https://mc.marc.tv/iso/#/-119/64/-541/-5/pudel%20-%20overworld/day_complete_smooth

![image](https://user-images.githubusercontent.com/136737/63380452-d9e9ce00-c396-11e9-9712-96985033d33f.png)

**Comment by mtoensing** [comment]
Reopended

**Comment by mtoensing** [comment]
I used cropped layers. My fault
