### ISSUE TITLE
MC v1.15 fails while rendering other northdirection

### ISSUE THREAD

**Issue by chrko** [overviewer/Minecraft-Overviewer#1683]
Rendering a world with an other northdirection, e.g.:
```python
renders['overworld_smooth_lr'] = {
        'title': 'Overworld smooth lr',
        'rendermode': 'smooth_lighting',
        'northdirection': 'lower-right',
        }
```

the rendering currently fails in https://github.com/overviewer/Minecraft-Overviewer/blob/268938a70680a8e7a62406ee52b2edc0b653a608/overviewer_core/world.py#L1614 with the following exception(s):

```
2019-12-11 11:38:33 E Could not render chunk -41,-105 for some reason. This is likely a render primitive option error.                                                                                    ] 208 67.73t/s eta 00h 21m 27s
2019-12-11 11:38:33 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'NoneType' object has no attribute 'swapaxes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marvcraft/overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/home/marvcraft/overviewer/overviewer_core/world.py", line 1614, in get_chunk
    biomes = numpy.swapaxes(section['Biomes'], 0, 1)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 585, in swapaxes
    return _wrapfunc(a, 'swapaxes', axis1, axis2)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
numpy.AxisError: axis1: axis 0 is out of bounds for array of dimension 0
```

**Comment by CounterPillow** [comment]
\o/ I broke things

Will try to get around to looking into this tonight-ish

**Comment by CounterPillow** [comment]
Please let me know if the commit I just made does indeed fix this for you.

**Comment by chrko** [comment]
@CounterPillow works again :)
