### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by ischtar** [overviewer/Minecraft-Overviewer#1685]
Hi y'all.

I use the map since Minecraft Version 1.12 and the last rendering was with 1.14. Since yesterday I've the 1.15 minecraftserver. 
Today I've installed the newest version of Overviewer(Minecraft Overviewer unknown (unknown)
built on Wed Dec 11 14:05:20 2019) and tried to render my map. Python3 is installed on my debian system and the texture pack 1.14 (and 1.15) is downloaded and defined in the config file too.  

With both texturejars, I get the following error: 

tileset.py:1105    28958 2019-12-11 15:33:35 ERROR    Could not render chunk -47,-53 for some reason. This is likely a render primitive option error.                                                                                                                         
tileset.py:1106    28958 2019-12-11 15:33:35 ERROR    Full error was:
Traceback (most recent call last):
  File "/var/www/vhosts/railmap15/railmap/Overviewer201912/Minecraft-Overviewer-master/overviewer_core/tileset.py", line 1093, in _render_rendertile                                                                                                                          
    self.options['rendermode'], self.textures)
  File "/var/www/vhosts/railmap15/railmap/Overviewer201912/Minecraft-Overviewer-master/overviewer_core/world.py", line 1729, in get_chunk                                                                                                                                     
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/var/www/vhosts/railmap15/railmap/Overviewer201912/Minecraft-Overviewer-master/overviewer_core/world.py", line 1549, in get_chunk                                                                                                                                     
    return self._r.get_chunk(x,z)
  File "/var/www/vhosts/railmap15/railmap/Overviewer201912/Minecraft-Overviewer-master/overviewer_core/world.py", line 1390, in get_chunk                                                                                                                                     
    section['Biomes'] = biome_giver.get_biome(section["Y"])
  File "/var/www/vhosts/railmap15/railmap/Overviewer201912/Minecraft-Overviewer-master/overviewer_core/biome.py", line 40, in get_biome
    return self.biomes[y_level // 4]
IndexError: list index out of range

What could that be? 

Thanks, for the map! Love it

**Comment by CounterPillow** [comment]
>What could that be?

Mojang being Mojang. Apparently you can have 17 Y levels instead of just 16 but you only have 4 biome levels so that's another fun special case to add to the code, which I just did, so this should be fixed if you update Overviewer. Thanks for reporting this. (And thanks to demosjarco on discord for reporting this as well with a sample file.)

**Comment by ischtar** [comment]
Thank you so much and sorry that I didn't attached a sample file.

**Comment by CounterPillow** [comment]
No problem, we don't have an issue template asking for one and it can be hard finding which specific file is needed, so usually I just ask for one when I need one. This time someone else just had one handy already :)

**Comment by ischtar** [comment]
It worked fine! :)
