### ISSUE TITLE
New Error running overviewer Cannot reshape array (MC15.1)

### ISSUE THREAD

**Issue by Tirpitz93** [overviewer/Minecraft-Overviewer#1703]
First noticed this after updating to 15.1, probably related but cant say for sure.

```
2019-12-28 17:32:33 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 559, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 219, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1369, in get_chunk
    biomes = biomes.reshape((16,16))
ValueError: cannot reshape array of size 1024 into shape (16,16)
```

**Comment by Tirpitz93** [comment]
ignore me, when building from source, and selecting correct textures this works fine.
