### ISSUE TITLE
genPOI: 'CroppedRegionSet' object has no attribute 'regiondir'

### ISSUE THREAD

**Issue by jobe1986** [overviewer/Minecraft-Overviewer#1706]
When running genPOI with cropped regions defined the following error occurs:

```
*******************************************************************************
2020-01-03 08:52:52 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/home/simplanet/overviewer/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/home/simplanet/overviewer/bin/overviewer.py", line 168, in main
    g.genPOI.main()
  File "/home/simplanet/overviewer/bin/overviewer_core/aux_files/genPOI.py", line 548, in main
    sfilters = sorted(filters, key=keyfunc)
  File "/home/simplanet/overviewer/bin/overviewer_core/world.py", line 888, in __lt__
    return self.regiondir < other.regiondir
AttributeError: 'CroppedRegionSet' object has no attribute 'regiondir'
```

**Comment by CounterPillow** [comment]
Fixed by #1720, thanks for reporting it.
