### ISSUE TITLE
Sorry I put up this issue before but I closed it by mistake, I have no idea what the error message means

### ISSUE THREAD

**Issue by jeff-11** [overviewer/Minecraft-Overviewer#1714]
I've got no idea what this means but I'm pretty sure I ran everything correctly.

2020-01-25 10:35:00 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 482, in main
KeyError: 'C:\\Users\\Lazlo\\AppData\\Local\\Packages\\Microsoft.MinecraftUWP_8wekyb3d8bbwe\\LocalState\\games\\com.mojang\\minecraftWorlds\\Earth 2.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "overviewer.py", line 650, in <module>
  File "overviewer.py", line 485, in main
  File "overviewer_core\world.py", line 102, in __init__
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 199, in read_all
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 463, in read
  File "gzip.py", line 411, in _read_gzip_header
OSError: Not a gzipped file (b'\x08\x00')

**Comment by chungy** [comment]
Overviewer only supports Java Edition, but you're trying to render a Bedrock Edition world. This won't work.

**Comment by jeff-11** [comment]
oh ok
some dude said he got it to work on bedrock so thats why I was trying

**Comment by chungy** [comment]
He was either lying or used another program to convert it to a Java Edition world first :)

**Comment by jeff-11** [comment]
thats what I'm gonna try to do now, cause I originally converted the world from java to bedrock
