### ISSUE TITLE
Overviewer does not start

### ISSUE THREAD

**Issue by thrusty66** [overviewer/Minecraft-Overviewer#1718]
Hi, I have a Minecraft Bedrock (Alpha) server running. Now I'm trying to generate a map with Overviewer for some time. Unfortunately I can't get it to work.
When starting Overviewer I get the following errors. Unfortunately I also have too little knowledge to be able to do anything with this issue.

`2020-02-04 16:49:16 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 482, in main
    w = worldcache[render['world']]
KeyError: '/home/ingo/minecraft/worlds/Bedrock level'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./overviewer.py", line 650, in <module>
    ret = main()
  File "./overviewer.py", line 485, in main
    w = world.World(render['world'])
  File "/home/ingo/Minecraft-Overviewer/overviewer_core/world.py", line 102, in __init__
    data = nbt.load(os.path.join(self.worlddir, "level.dat"))[1]['Data']
  File "/home/ingo/Minecraft-Overviewer/overviewer_core/nbt.py", line 31, in wrapper
    return func(fileobj, *args)
  File "/home/ingo/Minecraft-Overviewer/overviewer_core/nbt.py", line 40, in load
    return NBTFileReader(fileobj).read_all()
  File "/home/ingo/Minecraft-Overviewer/overviewer_core/nbt.py", line 199, in read_all
    tagtype = ord(self._file.read(1))
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\x08\x00')

`

**Comment by CounterPillow** [comment]
We don't support bedrock edition, sorry.

**Comment by thrusty66** [comment]
Does the Overviewer only work with the Java version?

**Comment by chungy** [comment]
Yes, Java Edition only.
