### ISSUE TITLE
genPOI: TypeError Exception

### ISSUE THREAD

**Issue by jobe1986** [overviewer/Minecraft-Overviewer#1722]
Whilst running genPOI the following exception occurred:

```
2020-02-11 10:06:21 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/simplanet/overviewer/bin/overviewer_core/aux_files/genPOI.py", line 131, in parseBucketChunks
    result = ff(poi)
  File "/home/simplanet/overviewer/overviewer.conf", line 121, in animalIcons
    b = (poi['Variant'] / 256) & 0xFF
TypeError: unsupported operand type(s) for &: 'float' and 'int'
"""
```

**Comment by CounterPillow** [comment]
The problem here is your config file. the `Variant` field of the poi is likely straight from Minecraft, and was changed to a float instead of an int. Python doesn't allow you to binary-and a float and an int.

Please post your full config file.

**Comment by jobe1986** [comment]
My bad, didn't read the file name. sorry for the time wasted.
