### ISSUE TITLE
Crash after preprocessing

### ISSUE THREAD

**Issue by Anagastes** [overviewer/Minecraft-Overviewer#1731]
I've recently got these bugs in the current version for Debian.

Any idea why?

overviewer.py --version                                                                                                                                                                                
Minecraft Overviewer 0.15.26 (9895fe8)
built on Wed Feb 19 14:09:58 2020

```python
2020-02-23 19:22:05  Preprocessing...
2020-02-23 19:25:37 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 52, in render_all
    self.setup_tilesets(tilesetlist)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 325, in setup_tilesets
    self.manager.set_tilesets(tilesets)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 200, in set_tilesets
    data[0] = self.tilesets
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 228, in serve_client
    request = recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __new__() missing 2 required positional arguments: 'lang' and 'tkey'
---------------------------------------------------------------------------
Process MultiprocessingDispatcherProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 716, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process MultiprocessingDispatcherProcess-2:
Process MultiprocessingDispatcherProcess-3:
Process MultiprocessingDispatcherProcess-4:
Process MultiprocessingDispatcherProcess-6:
Process MultiprocessingDispatcherProcess-10:
Process MultiprocessingDispatcherProcess-7:
Process MultiprocessingDispatcherProcess-8:
Process MultiprocessingDispatcherProcess-11:
Process MultiprocessingDispatcherProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
Process MultiprocessingDispatcherProcess-13:
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process MultiprocessingDispatcherProcess-14:
Traceback (most recent call last):
Process MultiprocessingDispatcherProcess-15:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
EOFError
EOFError
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
EOFError
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
Process MultiprocessingDispatcherProcess-16:
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
Process MultiprocessingDispatcherProcess-9:
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
EOFError
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process MultiprocessingDispatcherProcess-17:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

Here my conf file

```
  import os
  
  outputdir = "//home/mc/dungeon-rendered-smooth-jpg-80/"
  texturepath = "/home/mc/sphax115_128x.zip"
  
  worlds["Dungeon"] = "/home/mc/minecraft/worlds/Dungeon/"
  worlds["SkyWorld"] = "/home/mc/minecraft/worlds/paradise/"
  worlds["Hauptwelt"] = "/home/mc/minecraft/worlds/world_old/"
  worlds["Unterwelt"] = "/home/mc/minecraft/worlds/world_old_nether/"
  
  renders["Fliegende-Inseln"] = {
      "world": "SkyWorld",
      "title": 'Our "Paradise"',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": smooth_lighting,
  }
  
  renders["smooth-lighting"] = {
      "world": "Dungeon",
      "title": 'Our "Dungeon"',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": smooth_lighting,
  }
  
  renders["hauptwelt"] = {
      "world": "Hauptwelt",
      "title": 'Hauptwelt',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": "smooth_night",
  }
  
  renders["world_old_nether"] = {
      "world": "Unterwelt",
      "title": 'Der Nether',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": nether,
  }
```

**Comment by mikroskeem** [comment]
Can you try older commit? 51efdbaa4e79763a58c09fbda2155bcb2f346298 for example?

**Comment by Bobcat00** [comment]
I'm getting what appears to be the same error with 0.15.26
https://pastebin.com/mzcvqHi5

0.15.25 works fine.

**Comment by stx-git** [comment]
I also started getting a crash after preprocessing after upgrading to 0.15.26.  I rolled back to 0.15.25 and Overviewer is running normally again.  Server version is Ubuntu 16.04 LTS.

**Comment by Anagastes** [comment]
> Can you try older commit? [51efdba](https://github.com/overviewer/Minecraft-Overviewer/commit/51efdbaa4e79763a58c09fbda2155bcb2f346298) for example?

Same issue

```python
2020-02-28 18:17:05  Welcome to Minecraft Overviewer!
2020-02-28 18:17:05  Generating textures...
2020-02-28 18:17:29  Preprocessing...
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./build/scripts-3.5/overviewer.py", line 650, in <module>
    ret = main()
  File "./build/scripts-3.5/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 52, in render_all
    self.setup_tilesets(tilesetlist)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 325, in setup_tilesets
    self.manager.set_tilesets(tilesets)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 200, in set_tilesets
    data[0] = self.tilesets
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 228, in serve_client
    request = recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __new__() missing 2 required positional arguments: 'lang' and 'tkey'
---------------------------------------------------------------------------
Process MultiprocessingDispatcherProcess-3:
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
EOFError
```

**Comment by ColeMundus** [comment]
Same issue here as well rolling back to .15 does NOT fix the issue for me

**Comment by CounterPillow** [comment]
I've reverted the offending commit in 0.15.27 so if you're using 0.15.27 or later it should be working fine again. Fuck Python.

>Same issue here as well rolling back to .15 does NOT fix the issue for me

then you did it wrong

**Comment by Anagastes** [comment]
> I've reverted the offending commit in 0.15.27 so if you're using 0.15.27 or later it should be working fine again. Fuck Python.
> 
> > Same issue here as well rolling back to .15 does NOT fix the issue for me
> 
> then you did it wrong

New Build with python3.5 on debian 9.

./build/scripts-3.5/overviewer.py --version                                                                                                                                                           
Minecraft Overviewer 0.15.27 (e5ec41f)
built on Wed Feb 19 14:09:58 2020

All old Output-Files deletet an complete new run.

Same issue. Im sorry... but I dont know how why.

My config-file.

```json
  import os
  
  processes = 2
  outputdir = "/var/customers/webs/andre/www/mc/dungeon-rendered-smooth-jpg-80/"
  texturepath = "/var/customers/webs/andre/www/mc/sphax115_128x.zip"
  
  worlds["Dungeon"] = "/var/customers/webs/andre/www/mc/minecraft/worlds/Dungeon/"
  worlds["SkyWorld"] = "/var/customers/webs/andre/www/mc/minecraft/worlds/paradise/"
  worlds["Hauptwelt"] = "/var/customers/webs/andre/www/mc/minecraft/worlds/world_old/"
  worlds["Unterwelt"] = "/var/customers/webs/andre/www/mc/minecraft/worlds/world_old_nether/"
  
  renders["Fliegende-Inseln"] = {
      "world": "SkyWorld",
      "title": 'Our "Paradise"',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": smooth_lighting,
  }
  
  renders["smooth-lighting"] = {
      "world": "Dungeon",
      "title": 'Our "Dungeon"',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": smooth_lighting,
  }
  
  renders["hauptwelt"] = {
      "world": "Hauptwelt",
      "title": 'Hauptwelt',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": "smooth_night",
  }
  
  renders["world_old_nether"] = {
      "world": "Unterwelt",
      "title": 'Der Nether',
      "imgformat": "jpg",
      "imgquality": "80",
      "rendermode": nether,
  }
```

```python
2020-03-03 13:14:26  Welcome to Minecraft Overviewer!
2020-03-03 13:14:26  Generating textures...
2020-03-03 13:14:49  Preprocessing...
2020-03-03 13:18:21 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./build/scripts-3.5/overviewer.py", line 650, in <module>
    ret = main()
  File "./build/scripts-3.5/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 52, in render_all
    self.setup_tilesets(tilesetlist)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 325, in setup_tilesets
    self.manager.set_tilesets(tilesets)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 200, in set_tilesets
    data[0] = self.tilesets
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 228, in serve_client
    request = recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __new__() missing 2 required positional arguments: 'lang' and 'tkey'
---------------------------------------------------------------------------
Process MultiprocessingDispatcherProcess-2:
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "<string>", line 2, in get
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
EOFError
```

**Comment by CounterPillow** [comment]
>`/usr/lib/python3.5/dist-packages/`

You have an installed overviewer version in /usr/lib, but are running `./build/scripts-3.5/overviewer.py`. The version output of `./build/scripts-3.5/overviewer.py` will be of the `build/scripts-3.5/overviewer.py` file, but it can still load the `/usr/lib` version of the overviewer_core module (another reason why python sucks), can you verify for me that your system-wide overviewer installation in /usr/lib also is of the version you think that it is?

**Comment by Anagastes** [comment]
> > `/usr/lib/python3.5/dist-packages/`
> 
> You have an installed overviewer version in /usr/lib, but are running `./build/scripts-3.5/overviewer.py`. The version output of `./build/scripts-3.5/overviewer.py` will be of the `build/scripts-3.5/overviewer.py` file, but it can still load the `/usr/lib` version of the overviewer_core module (another reason why python sucks), can you verify for me that your system-wide overviewer installation in /usr/lib also is of the version you think that it is?

Thanks a lot. There really were remnants of an old Debian version from the repository.

I am truly sorry. Now it works again!
