### ISSUE TITLE
[Windows] queue.Full or PermissionError; Race Condition?

### ISSUE THREAD

**Issue by DragonDev1906** [overviewer/Minecraft-Overviewer#1732]
I think I've found a race condition. Reason: I'm getting different exceptions on the same system without changing anything.

System:
CPU: Ryzen 1600x
GPU: GTX 660TI
RAM: 32GB
OS: Windows
Python Version: 3.7.2
Pillow: 7.0.0
numpy: 3.1.5
commit: 9895fe875b5016d71a99d96bcf7576a0ff6e7296 (HEAD) (additionally tested with a commit 15 commits behind)

I guess the different errors come from execution order of the threads and the first one get's printed and stopps the process.

Unfortunatly I don't know why I'm getting a queue.Full or PermissionError in the first place.

All Errors seem to be comming from the following line: https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/dispatcher.py#L249

```
2020-02-27 22:25:44  Preprocessing...
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
queue.Full
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
queue.Full
2020-02-27 22:25:46  Rendered 0 of 2137.  0% complete.  ETA: ------
2020-02-27 22:25:46 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 650, in <module>
    ret = main()
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 81, in render_all
    observer.add(self._dispatch_jobs())
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 107, in _dispatch_jobs
    finished_jobs += self.dispatch(tileset, workitem)
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 334, in dispatch
    self.job_queue.put((self.manager.tileset_version, tileset_index, workitem), False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
PermissionError: [WinError 5] Zugriff verweigert
```

```
2020-02-27 22:30:25  Preprocessing...
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
queue.Full
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
queue.Full
2020-02-27 22:30:27  Rendered 0 of 2137.  0% complete.  ETA: ------
2020-02-27 22:30:27 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 650, in <module>
    ret = main()
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 81, in render_all
    observer.add(self._dispatch_jobs())
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 107, in _dispatch_jobs
    finished_jobs += self.dispatch(tileset, workitem)
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 334, in dispatch
    self.job_queue.put((self.manager.tileset_version, tileset_index, workitem), False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
queue.Full
```
```
2020-02-27 22:34:09  Preprocessing...
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
PermissionError: [WinError 5] Zugriff verweigert
Process MultiprocessingDispatcherProcess-3:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 249, in run
    self.result_queue.put(None, False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
PermissionError: [WinError 5] Zugriff verweigert
2020-02-27 22:34:11  Rendered 0 of 2137.  0% complete.  ETA: ------
2020-02-27 22:34:11 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 650, in <module>
    ret = main()
  File "C:/Users/Jens/Documents/projects/Minecraft-Overviewer/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 81, in render_all
    observer.add(self._dispatch_jobs())
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 107, in _dispatch_jobs
    finished_jobs += self.dispatch(tileset, workitem)
  File "C:\Users\Jens\Documents\projects\Minecraft-Overviewer\overviewer_core\dispatcher.py", line 334, in dispatch
    self.job_queue.put((self.manager.tileset_version, tileset_index, workitem), False)
  File "<string>", line 2, in put
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
PermissionError: [WinError 5] Zugriff verweigert

```

**Comment by DragonDev1906** [comment]
Something was wrong with my pycharm / python installation
