### ISSUE TITLE
NameError: name 'WinDLL' is not defined

### ISSUE THREAD

**Issue by jmb05** [overviewer/Minecraft-Overviewer#1743]
When trying to build overviewer from source on my Ubuntu 18.04.4 LTS Server I get the following error message:
![error2](https://user-images.githubusercontent.com/53855936/77909690-12874980-728e-11ea-98e1-f69958560703.PNG)
 `buildTraceback (most recent call last):
  File "setup.py", line 31, in <module>
    import py2exe
  File "/usr/local/lib/python3.6/dist-packages/py2exe/__init__.py", line 9, in <module>
    patch_distutils()
  File "/usr/local/lib/python3.6/dist-packages/py2exe/patch_distutils.py", line 68, in patch_distutils
    from . import distutils_buildexe
  File "/usr/local/lib/python3.6/dist-packages/py2exe/distutils_buildexe.py", line 91, in <module>
    from . import runtime
  File "/usr/local/lib/python3.6/dist-packages/py2exe/runtime.py", line 3, in <module>
    from .dllfinder import Scanner, pydll
  File "/usr/local/lib/python3.6/dist-packages/py2exe/dllfinder.py", line 5, in <module>
    from . import _wapi
  File "/usr/local/lib/python3.6/dist-packages/py2exe/_wapi.py", line 4, in <module>
    _kernel32 = WinDLL("kernel32")
NameError: name 'WinDLL' is not defined
`
the message hints to me that it is trying to use modules that are only available on Windows... 
What am I doing wrong?

**Comment by CounterPillow** [comment]
You have some strange version of py2exe in `/usr/local/lib`, potentially because you installed it through pip. Try removing it.

**Comment by CounterPillow** [comment]
Also yes, looks like py2exe is a Windows-only thing, so I'm not sure how you have this installed on Linux.
