### ISSUE TITLE
Render without trees?

### ISSUE THREAD

**Issue by teeruhmesoo** [overviewer/Minecraft-Overviewer#1751]
I'm trying to figure out if it possible to render a map without the trees so I can see the terrain. Is there a way to not render the trees, or perhaps a way to tell it not to render certain blocks (leaves, logs, whatever)?

**Comment by Auron956** [comment]
You can prevent particular blocks from rendering using the Hide rendermode primitive, which is documented [here](http://docs.overviewer.org/en/latest/config/#the-rendermode-primitives). For hiding logs & leaves, you can use ```Hide(blocks = [17, 18, 162])```, where 17 is the ID for oak, spruce, birch & jungle logs, 162 is acacia & dark oak logs, and 18 is all leaves.

If you're already using a custom rendermode you can add this primitive to the end, or if you're using a built-in rendermode you can find the definition [here](http://docs.overviewer.org/en/latest/config/#built-in-rendermodes) and then add the primitive to the end. For example, the rendermode that's equivalent to the built-in ```smooth_lighting``` with hidden trees/leaves would be ```[Base(), EdgeLines(), SmoothLighting(), Hide(blocks = [17, 18, 162])]```.

**Comment by teeruhmesoo** [comment]
> You can prevent particular blocks from rendering using the Hide rendermode primitive, which is documented [here](http://docs.overviewer.org/en/latest/config/#the-rendermode-primitives). For hiding logs & leaves, you can use `Hide(blocks = [17, 18, 162])`, where 17 is the ID for oak, spruce, birch & jungle logs, 162 is acacia & dark oak logs, and 18 is all leaves.
> 
> If you're already using a custom rendermode you can add this primitive to the end, or if you're using a built-in rendermode you can find the definition [here](http://docs.overviewer.org/en/latest/config/#built-in-rendermodes) and then add the primitive to the end. For example, the rendermode that's equivalent to the built-in `smooth_lighting` with hidden trees/leaves would be `[Base(), EdgeLines(), SmoothLighting(), Hide(blocks = [17, 18, 162])]`.

Thank you so much that was incredibly helpful! Is there somewhere that shows all of the possible things I can do with Overviewer? I checked the documentation before my original post but didn't see anything about excluding blocks so now I'm wondering what else can I do that isn't in the documentation?

**Comment by Auron956** [comment]
As far as I know the official documentation is the most complete source for that, I'm not aware of any undocumented features. If looking to alter the appearance of the map I'd have thought it best to review the sections concerning [the configuration file](http://docs.overviewer.org/en/latest/config/) (in particular [rendermodes](http://docs.overviewer.org/en/latest/config/#custom-rendermodes-and-rendermode-primitives)) as well as [signs and markers](http://docs.overviewer.org/en/latest/signs/).

**Comment by teeruhmesoo** [comment]
> As far as I know the official documentation is the most complete source for that, I'm not aware of any undocumented features. If looking to alter the appearance of the map I'd have thought it best to review the sections concerning [the configuration file](http://docs.overviewer.org/en/latest/config/) (in particular [rendermodes](http://docs.overviewer.org/en/latest/config/#custom-rendermodes-and-rendermode-primitives)) as well as [signs and markers](http://docs.overviewer.org/en/latest/signs/).

Hmm I must've missed it when I read through it last night. It was a lot to take in all at once so a few times I just skimmed but I'll give it a thorough read and see what cool stuff I can do.

**Comment by teeruhmesoo** [comment]
So I wasn't able to sit down and give it a go the past few days, but I finally got around to trying to render without trees and I seem to have hit a wall. I'm trying to make a config file but every time it gets to the rendermodes line I get an invalid syntax error and I'm not really sure what I'm doing wrong https://pastebin.com/1EJ5z36F  I don't have much experience with stuff like this, I'm just learning as I go.

**Comment by Auron956** [comment]
Okay, a few things here:
- For rendermode either a pre-defined list or your own list of primitives is specified, not both, so `smooth_lighting = ` should be removed
- The last line of a render definition shouldn't have a comma at the end

In other words, the line defining rendermode should be: `"rendermode": [Base(), EdgeLines(), SmoothLighting(), Hide(blocks = [17, 18, 162])]`

**Comment by teeruhmesoo** [comment]
> 
> 
> Okay, a few things here:
> 
>     * For rendermode either a pre-defined list or your own list of primitives is specified, not both, so `smooth_lighting = ` should be removed
> 
>     * The last line of a render definition shouldn't have a comma at the end
> 
> 
> In other words, the line defining rendermode should be: `"rendermode": [Base(), EdgeLines(), SmoothLighting(), Hide(blocks = [17, 18, 162])]`

It worked! You're the best, thank you so much!

**Comment by teeruhmesoo** [comment]
Okay, once more I have to ask for assistance.  I really do appreciate all the help so far and I'm trying to learn from what you've shown me so I took what you told me to do and tried to apply it to the smoothlighting bit by changing the strength because I wanted to see how the shadows would look at various levels and if they would disappear completely if set to 0 which would be useful when hiding trees.  Anyway, https://pastebin.com/93Hwi2D9 is my current config file showing the 4 different renders I'm attempting, each from a different angle and each with different smoothlighting strength but this keeps happening:

> C:\Users\Ashley\Downloads\SC4\Fallout\overviewer-0.15.30>overviewer.exe --config
> =c:\users\ashley\desktop\configtest1.txt
> 2020-04-21 03:23:24  Welcome to Minecraft Overviewer!
> 2020-04-21 03:23:24  Generating textures...
> 2020-04-21 03:23:39  Generating textures...
> 2020-04-21 03:23:53  Generating textures...
> 2020-04-21 03:24:08  Generating textures...
> 2020-04-21 03:24:23  Preprocessing...
> 2020-04-21 03:25:32  Rendered 0 of 23206.  0% complete.  ETA: ------
> ERROR:root:Could not render chunk 17,-19 for some reason. This is likely a rende
> r primitive option error.
> ERROR:root:Full error was:
> Traceback (most recent call last):
>   File "overviewer_core\tileset.py", line 1093, in _render_rendertile
> TypeError: rendermode option "strength" has incorrect type (☺)
> ERROR:root:Could not render chunk 17,-19 for some reason. This is likely a rende
> r primitive option error.
> ERROR:root:Full error was:
> Traceback (most recent call last):
>   File "overviewer_core\tileset.py", line 1093, in _render_rendertile
> TypeError: rendermode option "strength" has incorrect type (☺)
> ERROR:root:Could not render chunk 17,-19 for some reason. This is likely a rende
> r primitive option error.
> ERROR:root:Full error was:
> Traceback (most recent call last):
>   File "overviewer_core\tileset.py", line 1093, in _render_rendertile
> TypeError: rendermode option "strength" has incorrect type (☺)
> ERROR:root:Could not render chunk 18,-18 for some reason. This is likely a rende
> r primitive option error.
> ERROR:root:Full error was:
> Traceback (most recent call last):
>   File "overviewer_core\tileset.py", line 1093, in _render_rendertile
> TypeError: rendermode option "strength" has incorrect type (☺)
> 2020-04-21 03:35:10  Interrupted by user. Aborting.

I really have no idea what's going on, ~unless the only strength options available are 1, 0.5, and 0.0.~ This isn't the case, I just reran it with just those options and had the same result, so clearly I'm doing something wrong but I have absolutely no idea what.

**Comment by DragonDev1906** [comment]
> Okay so I solved the problem on my own, I removed the [ and ] brackets from around the strength values and that did the trick, I guess I only need those when putting a sequence of numbers like with hide?

That is correct. The config file is a python script and if you write something (or a list) in square brackets [ ] it will result in a list. The strength option only expects one number and because of that the type has to by a number. 

Since it is a python script you can always write python code and look at what you will get. Having a list of strength values doesn't make much sense, which is why you don't need the square brackets for this option.
```
# This can be used to check what type a value is
print(type([5]))    # list
print(type(5))    # int
```
