### ISSUE TITLE
No such file or directory: 'markersDB.js'

### ISSUE THREAD

**Issue by Rektroth** [overviewer/Minecraft-Overviewer#1758]
Overviewer had been working fine until I used the flag --genpoi.

It scans for markers and then throws this error when trying to write them to markersDB.js:

```
This is the error that occured:
Traceback (most recent call last):
  File "overviewer/overviewer.py", line 659, in <module>
    ret = main()
  File "overviewer/overviewer.py", line 168, in main
    g.genPOI.main()
  File "/var/mc/overviewer/overviewer_core/aux_files/genPOI.py", line 599, in main
    with open(os.path.join(destdir, "markersDB.js"), "w") as output:
FileNotFoundError: [Errno 2] No such file or directory: '/var/mc/public_html/markersDB.js'
```

Not surprised the file's not there... it's supposed to make it...?

**Comment by fflnvb** [comment]
@Rektroth did you find a solution?
