### ISSUE TITLE
 compatibility issue with JustEnoughIDs-1.0.3-55

### ISSUE THREAD

**Issue by Unrealized** [overviewer/Minecraft-Overviewer#1784]
My world is created on version 1.12.2 modified. I tried several launch options.
Launched from under Windows and ubuntu. I tried to render overworld and nether. In all cases, I got the same error:

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 559, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1449, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1263, in _get_blockdata_v113
    translated_blocks[i], translated_data[i] = self._get_block(key)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 902, in _get_block
    key = palette_entry['Name']
TypeError: 'int' object is not subscriptable

My config below:
worlds["AMP3"] = "/minecraft/server/AMP3/"

renders["survivalday"] = {
    "world": "AMP3",
    "title": "smoth_light",
    "rendermode": smooth_lighting,
    "dimension": "DIM-1",
}

outputdir = "/minecraft/overviewer/maps"
texturepath = "/minecraft/1.15.jar"

**Comment by Unrealized** [comment]
Generated the world on 1.12.2 without mods. Render works. Apparently a compatibility issue with one of the mods.
There is no idea what mode the problem is. I'll try to sort through everything.

**Comment by Unrealized** [comment]
Problem with JustEnoughIDs-1.0.3-55

**Comment by CounterPillow** [comment]
Overviewer does not support modded worlds, and this is also not a support forum for whatever mods you're running.
