### ISSUE TITLE
Linux Build/Compile Failure on Block-Model Branch (iRath96)

### ISSUE THREAD

**Issue by Droon99-Developer** [overviewer/Minecraft-Overviewer#1785]
Upon attempted build (Ubuntu Server) The following error occurs
```creating build/temp.linux-x86_64-3.5/overviewer_core/src/primitives
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/home/droon/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c overviewer_core/src/main.c -o build/temp.linux-x86_64-3.5/overviewer_core/src/main.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/home/droon/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c overviewer_core/src/composite.c -o build/temp.linux-x86_64-3.5/overviewer_core/src/composite.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/home/droon/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c overviewer_core/src/iterate.c -o build/temp.linux-x86_64-3.5/overviewer_core/src/iterate.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
overviewer_core/src/iterate.c: In function ‘lookup_blockid’:
overviewer_core/src/iterate.c:42:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
     mc_block_t blockid = PyLong_AsLong(tmp);
     ^
cc1: some warnings being treated as errors
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Failed to build Overviewer!
Please review the errors printed above and the build instructions
at <http://docs.overviewer.org/en/latest/building/>.  If you are
still having build problems, file an incident on the github tracker
or find us in IRC.
```
Master builds perfectly successfully, but obviously does not have the benefit of the 1.16 blocks

**Comment by iRath96** [comment]
Thanks for reporting this, I have just pushed a fix that should resolve this.
I have also enabled "Issues" for my fork, so when there are any other problems you can post them directly on my repository (this way I get notifications).

Let me know if my fix works for you (if it does, please close this issue).

**Comment by CounterPillow** [comment]
Please report issues to the appropriate repository
