### ISSUE TITLE
Crash when rendering

### ISSUE THREAD

**Issue by Gaz492** [overviewer/Minecraft-Overviewer#1789]
Overviewer will crash when rendering if you manually build the current version on github with the following.

`2020-06-24 20:42:55 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/root/overviewer/overviewer.py", line 650, in <module>
    ret = main()
  File "/root/overviewer/overviewer.py", line 575, in main
    assetMrg.initialize(tilesets)
  File "/root/overviewer/overviewer_core/assetmanager.py", line 76, in initialize
    self._output_assets(tilesets, True)
  File "/root/overviewer/overviewer_core/assetmanager.py", line 160, in _output_assets
    self.output_noconfig()
  File "/root/overviewer/overviewer_core/assetmanager.py", line 182, in output_noconfig
    os.symlink("markers", "icons", target_is_directory=True, dir_fd=od_fd)
FileExistsError: [Errno 17] File exists: 'markers' -> 'icons'`

Seems to be related to line 177>184 in the changed made in this commit https://github.com/overviewer/Minecraft-Overviewer/commit/cadb24a01595ef529aee26dadd7bb8a63024e360#diff-b57e59f5a7f5ec2c9902b74b5f7d1d00

**Comment by CounterPillow** [comment]
oh jeez I didn't consider what would happen if an old dir was rendered into that didn't have the symlink yet. One sec, I'll fix it.
