### ISSUE TITLE
Crash while Preprocessing

### ISSUE THREAD

**Issue by 5h4rk1337** [overviewer/Minecraft-Overviewer#1790]
I updated my Server to 1.16. After that, Overviewer is not able to render my map anymore.
Tried it with a fresh build from source and a fresh rerender of my map, but i always get this result.
![Bildschirmfoto 2020-06-25 um 10 06 17](https://user-images.githubusercontent.com/31519324/85681473-9a34f680-b6cb-11ea-8e44-e9f05fdfabf3.png)

2020-06-25 09:32:18  Preprocessing...
2020-06-25 09:37:28 E Could not render chunk -1,-38 for some reason. This is likely a render primitive option error.
2020-06-25 09:37:28 E Could not render chunk -1,-38 for some reason. This is likely a render primitive option error.
2020-06-25 09:37:28 E Full error was:
Traceback (most recent call last):
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1658, in get_chunk
    chunk_data = dict(super(RotatedRegionSet, self).get_chunk(x,z))
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1783, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1354, in get_chunk
    data = region.load_chunk(x, z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/nbt.py", line 295, in load_chunk
    header = self._file.read(5)
OSError: [Errno 5] Input/output error
2020-06-25 09:37:28 E Full error was:
Traceback (most recent call last):
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1658, in get_chunk
    chunk_data = dict(super(RotatedRegionSet, self).get_chunk(x,z))
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1783, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1354, in get_chunk
    data = region.load_chunk(x, z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/nbt.py", line 295, in load_chunk
    header = self._file.read(5)
OSError: [Errno 5] Input/output error
2020-06-25 09:37:36 E Could not render chunk -393,-437 for some reason. This is likely a render primitive option error.
2020-06-25 09:37:36 E Full error was:
Traceback (most recent call last):
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1783, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1354, in get_chunk
    data = region.load_chunk(x, z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/nbt.py", line 295, in load_chunk
    header = self._file.read(5)
OSError: [Errno 5] Input/output error
2020-06-25 09:37:40 E Could not render chunk -393,-437 for some reason. This is likely a render primitive option error.
2020-06-25 09:37:40 E Full error was:
Traceback (most recent call last):
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1783, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1598, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1354, in get_chunk
    data = region.load_chunk(x, z)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/nbt.py", line 295, in load_chunk
    header = self._file.read(5)
OSError: [Errno 5] Input/output error

**Comment by CounterPillow** [comment]
Doesn't appear to be related to Overviewer or 1.16 at all, but rather seems like a dying disk or a messed up OS block layer or what have you.

**Comment by 5h4rk1337** [comment]
I run Ubuntu Server 18.04.4 LTS

My HDDs smart is OK.
fsck could also find no issues. 

Minecraft 1.6.1 runs perfectly well with my World. Only Overviewer seems to dislike this save game.

**Comment by CounterPillow** [comment]
I've added some code to also retry on I/O failures, which also means that failing to read a chunk due to I/O errors is not a fatal error anymore; if it fails too many times, it'll simply skip the chunk.

I still don't really see how this could be related to anything specific to Overviewer at all though.

**Comment by CounterPillow** [comment]
As an aside note, the precise file it struggles on would probably be `r.-1.-2.mca`
