### ISSUE TITLE
Crash after preprocessing

### ISSUE THREAD

**Issue by MAX-XiaoKui** [overviewer/Minecraft-Overviewer#1815]
I've recently got these bugs in the current version for CentOS.
Minecraft Overviewer 0.15.86
````python
2020-07-24 23:21:56  Preprocessing...
Process MultiprocessingDispatcherProcess-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/site-packages/overviewer_core/dispatcher.py", line 252, in run
    job = self.job_queue.get(True, timeout)
  File "<string>", line 2, in get
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
*******************************************************************************
2020-07-24 23:23:21 E An error has occurred. This may be a bug. Please let us know!
>See http://docs.overviewer.org/en/latest/index.html#help

>This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 583, in main
    dispatch.render_all(tilesets, config['observer'])
  File "/usr/lib64/python3.6/site-packages/overviewer_core/dispatcher.py", line 52, in render_all
    self.setup_tilesets(tilesetlist)
  File "/usr/lib64/python3.6/site-packages/overviewer_core/dispatcher.py", line 325, in setup_tilesets
    self.manager.set_tilesets(tilesets)
  File "/usr/lib64/python3.6/site-packages/overviewer_core/dispatcher.py", line 200, in set_tilesets
    data[0] = self.tilesets
  File "<string>", line 2, in __setitem__
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
````
Here my conf file
````python
worlds["主世界"] = "/www/wwwroot/BlueMap/world"
worlds["下界"] = "/www/wwwroot/BlueMap/world"
worlds["末地"] = "/www/wwwroot/BlueMap/world"

renders["worldday"] = {
    "world": "主世界",
    "title": "skimit生存-overworld-白天",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

renders["worldnight"] = {
    "world": "主世界",
    "title": "skimit生存-overworld-夜晚",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

renders["nether"] = {
    "world": "下界",
    "title": "skimit生存-nether",
    "rendermode": nether_smooth_lighting,
    "dimension": "nether",
}

renders["end"] = {
    "world": "末地",
    "title": "skimit生存-end",
    "rendermode": smooth_lighting,
    "dimension": "end",
}

outputdir = "out"
````
I tried to reinstall it but it crashed again.It works well on Windows.

**Comment by CounterPillow** [comment]
Unfortunately that output does not contain enough information to debug this. Does it also crash with `-p1`? If so, please provide the output of that.

**Comment by MAX-XiaoKui** [comment]
it reports an error and then renders.
````python
*******************************************************************************
2020-07-28 20:24:17 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:17 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/0/1/2/1/0.png
*******************************************************************************
2020-07-28 20:24:17 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:17 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/0/1/2/1/1.png
*******************************************************************************
2020-07-28 20:24:17 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:17 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/0/1/2/1/2.png
*******************************************************************************
2020-07-28 20:24:17 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:17 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/0/1/3/0/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/0/2/0/0/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/0/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/0/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/0/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/0/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/1/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/1/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/1/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/1/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/2/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/2/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/2/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/2/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/3/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/3/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/3/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/1/3/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/0/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/0/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/0/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/0/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/1/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/1/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/1/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/1/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/2/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/2/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/2/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/2/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/3/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/3/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/3/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/0/3/3/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/0/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/0/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/0/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/0/3.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/1/0.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/1/1.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/1/2.png
*******************************************************************************
2020-07-28 20:24:18 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
*******************************************************************************
2020-07-28 20:24:18 W Tile was: /www/wwwroot/Overviewer/out/end/3/1/0/1/2/1/1/3.png
2020-07-28 20:24:24  Rendered 1500 of 96960.  1% complete.  ETA: 06h 11m 31s
2020-07-28 20:24:52  Rendered 1600 of 96960.  1% complete.  ETA: 06h 15m 46s
2020-07-28 20:25:26  Rendered 1700 of 96960.  1% complete.  ETA: 06h 25m 30s
2020-07-28 20:27:20  Rendered 1800 of 96960.  1% complete.  ETA: 07h 44m 24s
2020-07-28 20:27:45  Rendered 1900 of 96960.  1% complete.  ETA: 07h 39m 54s
2020-07-28 20:28:06  Rendered 2000 of 96960.  2% complete.  ETA: 07h 33m 18s
2020-07-28 20:28:29  Rendered 2100 of 96960.  2% complete.  ETA: 07h 28m 20s
2020-07-28 20:29:25  Rendered 2200 of 96960.  2% complete.  ETA: 07h 47m 50s
2020-07-28 20:30:03  Rendered 2300 of 96960.  2% complete.  ETA: 07h 53m 19s
````

**Comment by CounterPillow** [comment]
Okay, does it still work with `-p2`?

**Comment by MAX-XiaoKui** [comment]
> Okay, does it still work with `-p2`?

````python
*******************************************************************************
2020-07-29 22:16:09 W You are running Overviewer as root. It is recommended that you never do this, as it is dangerous for your system. If you are running into permission errors, fix your file/directory permissions instead. Overviewer does not need access to critical system resources and therefore does not require root access.
2020-07-29 22:16:10  Welcome to Minecraft Overviewer version 0.15.86 (3282791)!
2020-07-29 22:16:12  Generating textures...
*******************************************************************************
2020-07-29 22:16:54 W The last render for 'worldday' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
*******************************************************************************
2020-07-29 22:16:54 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
*******************************************************************************
2020-07-29 22:16:55 W The last render for 'worldnight' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
*******************************************************************************
2020-07-29 22:16:55 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
*******************************************************************************
2020-07-29 22:16:57 W The last render for 'nether' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
*******************************************************************************
2020-07-29 22:16:57 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
*******************************************************************************
2020-07-29 22:16:57 W The last render for 'end' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
*******************************************************************************
2020-07-29 22:16:57 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
2020-07-29 22:16:57  Preprocessing...
*******************************************************************************
2020-07-29 22:23:40 E An error has occurred. This may be a bug. Please let us know!
>See http://docs.overviewer.org/en/latest/index.html#help

>This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 582, in main
    local_procs=config['processes'])
  File "/usr/lib64/python3.6/site-packages/overviewer_core/dispatcher.py", line 294, in __init__
    self.manager.start()
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 513, in start
    self._process.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
>OSError: [Errno 12] Cannot allocate memory
````

**Comment by CounterPillow** [comment]
how much RAM do you have in this system, and how much of it is free when you're running it?

Also please never run as root
