### ISSUE TITLE
Generating Points of Interest hangs after all threads are done.

### ISSUE THREAD

**Issue by ToastyBreadMan** [overviewer/Minecraft-Overviewer#1817]
I have been having a problem that after all the entities are scanned by the `--genpoi` option, the process never terminates.  
It seems to me that the new POI's found are being written to disk, but this only happens after I interrupt the process with SIGINT.

World config:
```
global escape
from html import escape

def signPoiFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        if poi['Text1'] == '-=Poi=-':
            return escape("\n" + poi['Text2'] + "\n" + poi['Text3'] + "\n" + poi['Text4'])
        else:
            return None


worlds["Overworld"] = "/opt/minecraft/fabric/world"

renders['world_day'] = {
        'world': 'Overworld',
        'title': 'Overworld',
        'rendermode': 'smooth_lighting',
        'markers': [dict(name='Points of Interest', filterFunction=signPoiFilter, icon="markers/marker_location.png")],
}

outputdir = "/var/www/html/"
texturepath = "/opt/minecraft/overviewer/textures/"
```

Sample output:
```
2020-07-28 16:30:17  Searching renders: ['world_day']
2020-07-28 16:30:17  Will search 1 region sets using 1 filters
2020-07-28 16:30:17  Calling handleEntities for <RegionSet regiondir='/opt/minecraft/fabric/world/region'> with 1 filters
2020-07-28 16:30:17  Looking for entities in <RegionSet regiondir='/opt/minecraft/fabric/world/region'>...
2020-07-28 16:30:17  Buckets has 113935 entries.
2020-07-28 16:30:17  Buckets has 114625 entries.
2020-07-28 16:35:15  All the threads completed.
2020-07-28 16:35:15  Done.
^CException ignored in: <Finalize object, dead>
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 689, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 674, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt:
2020-07-28 16:40:08  Done handling POIs
2020-07-28 16:40:08  Writing out javascript files
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
2020-07-28 16:40:08  Done
```

This only happens occasionally, so I think there may be a race condition somewhere handling the threads.  
I have been able to replicate the hang using both the `--genpoi` option and the separate `genPOI.py` script.  

I am using the latest build as of this post [08e8c21](https://github.com/overviewer/Minecraft-Overviewer/commit/08e8c21d0c70f79a8935cd746a2ae72d98bf8d9f).

**Comment by CounterPillow** [comment]
`Pool.map()` should block until all threads are finished, so I'm not super sure what's going on here. That function is as far as I can see the only place where we both initiate and join parallel execution. According to the Python documentation, ["It blocks until the result is ready."](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map).

**Comment by Esvandiary** [comment]
Just a +1 that I've been hitting this as well for the last month or so at least. I'm investigating now, but as in the original report it doesn't seem to happen consistently (I'm failing to make it happen while manually running `genPOI.py`, but I have a map that generates once an hour and that seems to hit it fairly regularly). Will put a PR in if I figure out what's going on.

**Comment by Esvandiary** [comment]
Managed to get a bit more info on where this is happening (for me at least) - it appears to be returning from the call to `handleEntities` where it hangs. Log output (I added a few entries to see where we were getting to):

```
2020-08-28 20:06:34  Will search 2 region sets using 14 filters
2020-08-28 20:06:34  Calling handleEntities for <RegionSet regiondir='/home/minecraft/worldtmp/0v0/region'> with 12 filters
2020-08-28 20:06:34  Looking for entities in <RegionSet regiondir='/home/minecraft/worldtmp/0v0/region'>...
2020-08-28 20:06:35  Buckets has 127622 entries.
2020-08-28 20:06:35  Buckets has 128108 entries.
2020-08-28 20:06:35  parseBucketChunks: starting, thread 3488477
2020-08-28 20:06:35  parseBucketChunks: starting, thread 3488478
2020-08-28 20:09:01  parseBucketChunks: returning, thread 3488478
2020-08-28 20:09:02  parseBucketChunks: returning, thread 3488477
2020-08-28 20:09:02  All the threads completed.
2020-08-28 20:09:02  Done.
2020-08-28 20:09:02  Back from handleEntities
2020-08-28 20:09:02  Calling handleEntities for <RegionSet regiondir='/home/minecraft/worldtmp/0v0/DIM-1/region'> with 2 filters
2020-08-28 20:09:02  Looking for entities in <RegionSet regiondir='/home/minecraft/worldtmp/0v0/DIM-1/region'>...
2020-08-28 20:09:02  Buckets has 1296 entries.
2020-08-28 20:09:02  Buckets has 1295 entries.
2020-08-28 20:09:02  parseBucketChunks: starting, thread 3488526
2020-08-28 20:09:02  parseBucketChunks: starting, thread 3488527
2020-08-28 20:09:03  parseBucketChunks: returning, thread 3488527
2020-08-28 20:09:03  parseBucketChunks: returning, thread 3488526
2020-08-28 20:09:03  All the threads completed.
2020-08-28 20:09:03  Done.
```
The next line after that was `Terminated` when I killed the processes today (~12 hours later).

On the "successful" region, we get through everything, log `Done.` (literally the last line in `handleEntities`), return and then log `Back from handleEntities` which I added directly after the call to it. On the one that hangs, exactly the same thing happens, and we even get to `Done.`, but then we apparently never manage to return from that function.

This could _maybe_ because it's attempting to tear down the `Pool` (since it's gone out of scope and GC can take it when it likes) but we haven't called `pool.close()` & `pool.join()`? In theory the docs seem to indicate that it's not mandatory to do so, but I've seen a few anecdotes online of odd behaviour (not dissimilar to what we're seeing) that can happen if they're omitted.

I've just added `pool.close()` and `pool.join()` before logging that all threads are completed. I'll continue to let the map generate hourly as normal and see if I hit it again... I'm happy to wait and see if this fixes it, but if you think it'd be good to add the `close`/`join` combo as good practice regardless then I can put a PR in now.

**Comment by Esvandiary** [comment]
Just an update to say that with the `close`/`join` change I haven't seen a hang in the last four days, which is much longer than I'd normally have expected it to last... So hopefully this PR fixes it.

**Comment by Esvandiary** [comment]
Still haven't seen this issue after ~4 weeks with the change in #1845 :)
