### ISSUE TITLE
The documentation doesn't contain info about bedrock or java version supported.

### ISSUE THREAD

**Issue by vejinnovem** [overviewer/Minecraft-Overviewer#1841]
I'm not sure if there is something with my computer or if this program won't work with my bedrock edition.
If it works with bedrock edition I have a strange problem with overviewer:

D:\MCTOOLS\overviewer-0.16.3>overviewer.exe "D:/MCTOOLS/Retrogralnia" "D:/MCTOOLS/verviewedone"
2020-08-25 14:59:57  Welcome to Minecraft Overviewer version 0.16.3 (4c0a69d)!
2020-08-25 14:59:57 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 485, in main
KeyError: 'D:\\MCTOOLS\\Retrogralnia'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 488, in main
  File "overviewer_core\world.py", line 103, in __init__
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 199, in read_all
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 463, in read
  File "gzip.py", line 411, in _read_gzip_header
OSError: Not a gzipped file (b'\x08\x00')

[I am extremely sorry if I posted something wrong. Github is a not well-known place for me]

**Comment by CounterPillow** [comment]
Added a note in the docs that we only support Java Edition worlds, thanks for letting us know of this omission.
