### ISSUE TITLE
Crop rendering of adjacent selections

### ISSUE THREAD

**Issue by RossosHEX** [overviewer/Minecraft-Overviewer#1848]
Greetings.

I am experiencing zigzag cropping on adjacent crop sections.

`:~/applications/minecraftmap/Minecraft-Overviewer$ ./overviewer.py --config=/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt --processes=1 --forcerender`
```
2020-09-11 15:28:11  Welcome to Minecraft Overviewer version 0.16.4 (91ea874)!
2020-09-11 15:28:11  Forcerender mode activated. ALL tiles will be rendered.
2020-09-11 15:28:11  Generating textures...
2020-09-11 15:28:24  Preprocessing...
2020-09-11 15:28:25  Rendering 2417 total tiles.
 98% [================================================================= ] 2392 7.93t/s eta 00h 00m 03s
2020-09-11 15:33:27  Rendering complete!
```

![overviewer-zigzags](https://user-images.githubusercontent.com/8318353/92927116-c730b400-f445-11ea-9b98-d6bb13482a41.jpg)

I've tried playing with --tiles-check and --forcerender to no avail.
Map update behavior options:  rerenderprob and renderchecks are giving me "not defined" errors.

`:~/applications/minecraftmap/Minecraft-Overviewer$ ./overviewer.py --config=/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt --processes=1`
```
2020-09-11 14:53:51 E NameError parsing '/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt'.
2020-09-11 14:53:51 E The traceback below will tell you which line referenced the non-existent variable.
2020-09-11 14:53:51 E Partial traceback:
Traceback (most recent call last):
  File "/home/-redacted-/applications/minecraftmap/Minecraft-Overviewer/overviewer_core/config_parser.py", line 86, in parse
    rendermodes.__dict__, self._config_state)
  File "/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt", line 25, in <module>
    renderchecks: 1,
NameError: name 'renderchecks' is not defined
```

`:~/applications/minecraftmap/Minecraft-Overviewer$ ./overviewer.py --config=/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt --processes=1`
```
2020-09-11 14:54:13 E NameError parsing '/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt'.
2020-09-11 14:54:13 E The traceback below will tell you which line referenced the non-existent variable.

2020-09-11 14:54:13 E Partial traceback:
Traceback (most recent call last):
  File "/home/-redacted-/applications/minecraftmap/Minecraft-Overviewer/overviewer_core/config_parser.py", line 86, in parse
    rendermodes.__dict__, self._config_state)
  File "/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt", line 24, in <module>
    rerenderprob: 1.0,
NameError: name 'rerenderprob' is not defined
```

--check-tiles gives me an excessive amount of tiles ( ~43k) to check/render with a lot of warning items.
results in even more random croppings and tile renders (picture after the code quote).

`:~/applications/minecraftmap/Minecraft-Overviewer$ ./overviewer.py --config=/home/-redacted-/applications/minecraftmap/renders/insist-config-light.txt --processes=1 --check-tiles`
```
2020-09-11 15:56:05  Welcome to Minecraft Overviewer version 0.16.4 (91ea874)!
2020-09-11 15:56:05  Checking all tiles for updates manually.
2020-09-11 15:56:05  Generating textures...
2020-09-11 15:56:18  Preprocessing...
2020-09-11 15:56:19  Rendering 43690 total tiles.
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/0/3/2.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/0/3/3.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/2/1/0.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/2/1/1.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/2/1/2.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/3/0/0.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/0/3/3/0/1.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/2/0.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/2/1.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/2/2.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/2/3.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/3/2.png
2020-09-11 15:56:27 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:27 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/1/2/2/3/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/0/0.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/0/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/0/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/1/0.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/1/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/1/2.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/1/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/2/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/2/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/3/0.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/3/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/3/2.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/0/3/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/0/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/0/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/1/0.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/1/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/1/2.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/1/3.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/2/1.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/3/0.png
2020-09-11 15:56:55 W I found a tile with a more recent modification time than any of its chunks. This can happen when a tile has been modified with an outside program, or by a copy utility that doesn't preserve mtimes. Overviewer uses the filesystem's mtimes to determine which tiles need rendering and which don't, so it's important to preserve the mtimes Overviewer sets. Please see our FAQ page on docs.overviewer.org or ask us in IRC for more information.
2020-09-11 15:56:55 W Tile was: /home/-redacted-/applications/minecraftmap/renders/insist_light/normalrendernw/2/1/3/0/2/3/1.png
100% [==========================================================] 43690.0 1210.32t/s Time: 00h 00m 36s
2020-09-11 15:56:55  Rendering complete!
2020-09-11 15:56:55  Your render has been written to '/home/-redacted-/applications/minecraftmap/renders/insist_light', open index.html to view it.
```

![afterchecktiles](https://user-images.githubusercontent.com/8318353/92929027-9605b300-f448-11ea-996f-0ebbbf614891.jpg)

--forcerender reverts everything back to the first image.

Any suggestions very much appreciated.

render config file attached: 
[insist-config-light.txt](https://github.com/overviewer/Minecraft-Overviewer/files/5209200/insist-config-light.txt)

minor: can't get multi-thread to word, crashes everytime, forced to use --processes=1

**Comment by RossosHEX** [comment]
Consider the following config file:

```
renders["normalrendernw"] = {
    "world": "INSIST",
    "title": "INSIST by Day NW",
    "dimension": "overworld",
    #"rendermode": smooth_lighting,
    "rendermode": normal,
    #"rendermode": my_rendermode,
    'crop': [
			(-5944, -1341, 3265, 6683), # one giant piece
			(-1537, -38159, -945, -37570), # portal hub
			(-727, -36054, -108, -35219), # modern city 
			(18057, 12973, 19973, 15298), # storage++ (farms too)
			(-3310, -10190, -2835, -9753), # spawn island
			(-8008, -24322, -6548, -23388), # steampunk+
			#(78385, 53711, 79009, 54175), # guest heaven
			],
    'northdirection': "upper-right",
    #"optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "showspawn": False,
    #'forcerender': True,
    'manualpois':[
			{'id':'Location','x':18503,'y':70,'z':13322,'name':'Insist Storage'},
			{'id':'Location','x':-1102,'y':70,'z':-37917,'name':'Insist HUB'},

			{'id':'Location','x':-4256,'y':70,'z':2794,'name':'Oriental Kingdom'},
			{'id':'Location','x':306,'y':70,'z':-162,'name':'0die\'s House'},
			#{'id':'Location','x':1051,'y':70,'z':406,'name':'0die\'s Landing'},
			{'id':'Location','x':64,'y':70,'z':552,'name':'Birch Town'},
			{'id':'Location','x':-5062,'y':70,'z':4265,'name':'Desert Farms'},
			{'id':'Location','x':-4015,'y':70,'z':5775,'name':'Desert Kingdom'},
			{'id':'Location','x':231,'y':70,'z':519,'name':'Drakisath'},
			{'id':'Location','x':-181,'y':70,'z':130,'name':'Fantasy Forest'},
			{'id':'Location','x':-1217,'y':70,'z':1775,'name':'Guardian Farm'},
			{'id':'Location','x':368,'y':70,'z':267,'name':'Hobbiton'},
			{'id':'Location','x':-1629,'y':70,'z':3315,'name':'Industrial Zone'},
			{'id':'Location','x':-5530,'y':70,'z':3611,'name':'Iron Farm'},
			{'id':'Location','x':-4316,'y':70,'z':4328,'name':'Jungle kingdom'},
			{'id':'Location','x':568,'y':70,'z':364,'name':'Miner\'s Town'},
			{'id':'Location','x':-1109,'y':70,'z':-37734,'name':'Modern City'},
			{'id':'Location','x':-3072,'y':70,'z':1872,'name':'WaterCity9'},
			{'id':'Location','x':18089,'y':70,'z':15080,'name':'Pillager Farm'},
			{'id':'Location','x':19639,'y':70,'z':13498,'name':'Pillager Outpost'},
			{'id':'Location','x':-494,'y':70,'z':514,'name':'Pirate\'s Cove'},
			{'id':'Location','x':20,'y':70,'z':643,'name':'Porktown'},
			{'id':'Location','x':1571,'y':70,'z':469,'name':'Ravine Town Anniversary'},
			{'id':'Location','x':104,'y':70,'z':154,'name':'Wiarton'},
			{'id':'Location','x':1924,'y':70,'z':-1211,'name':'Viking Kingdom'},
			{'id':'Location','x':-221,'y':70,'z':-186,'name':'Villagers'},
			{'id':'Location','x':-5076,'y':70,'z':5047,'name':'Western Kingdom'},
			{'id':'Location','x':-6449,'y':70,'z':-500,'name':'Swamp Kingdom'},
			{'id':'Location','x':-3002,'y':70,'z':-9952,'name':'Spawn Island'},
			{'id':'Location','x':1600,'y':70,'z':145,'name':'Surki\'s Graveyard'},
			{'id':'Location','x':-7826,'y':70,'z':-22633,'name':'Witch Farm'},
			{'id':'Location','x':-6914,'y':70,'z':-24080,'name':'SteamPunk'},
			{'id':'Location','x':3004,'y':70,'z':6441,'name':'Dwarven Kingdom'},
			{'id':'Location','x':1349,'y':70,'z':1402,'name':'Ice Kingdom'},
			#{'id':'Location','x':78667,'y':70,'z':54000,'name':'Guest Heaven'},
                   ],
    'markers': [dict(name="Locations", filterFunction=townFilter, showIconInLegend=True, icon="poi.png") ],
}
```

![Screenshot from 2020-09-13 15-46-15](https://user-images.githubusercontent.com/8318353/93018519-f0ce1480-f5d8-11ea-8b00-3da3cf62a94e.png)

![Screenshot from 2020-09-13 15-46-40e](https://user-images.githubusercontent.com/8318353/93018487-bebcb280-f5d8-11ea-8e59-6b996f6dbf02.png)

Should I just avoid using the Crop feature at present?
It would seem I am getting the max zoom at -1 on the main continent, and the screen at max is just black.
And I am getting max zoom at -2 on that Spawn island in pictures. Zoom -1 and Max are just blank.
Zoom inconsistencies, that would explain the markers not matching. Markers appear to render on correct locations on x-z, it's the map that is being skewed. I am speculating wrong zoom level renders.
Trying to render one solid crop atm to double check.

**Comment by RossosHEX** [comment]
Config:
```
"rendermode": normal,
    #"rendermode": my_rendermode,
    'crop': [
			#(-5944, -1341, 3265, 6683), # one giant piece
			#(-1537, -38159, -945, -37570), # portal hub
			#(-727, -36054, -108, -35219), # modern city 
			#(18057, 12973, 19973, 15298), # storage++ (farms too)
			#(-3310, -10190, -2835, -9753), # spawn island
			#(-8008, -24322, -6548, -23388), # steampunk+
			#(78385, 53711, 79009, 54175), # guest heaven
			(-8008,-38159,20000,15298), # all at once
			],
    'northdirection': "upper-right",
```

`:~/applications/minecraftmap/Minecraft-Overviewer_IncredibleHolg-PR1839$ ./overviewer.py --config=/home/-redacted-/applications/minecraftmap/renders/insist-config-full.txt`
```
2020-09-13 15:41:15  Welcome to Minecraft Overviewer version 0.16.8 (d23fdb1)!
2020-09-13 15:41:15  Generating textures...
2020-09-13 15:41:31  Preprocessing...
2020-09-13 15:42:15  Rendering 62797 total tiles.
 99% [=============================================================== ] 62782 13.02t/s eta 00h 00m 01s
2020-09-13 17:02:38  Rendering complete!
2020-09-13 17:02:39  Your render has been written to '/home/-redacted-/applications/minecraftmap/renders/insist_single', open index.html to view it.
```

Produced the following (including running it with --genpoi):

![Screenshot from 2020-09-13 17-12-01](https://user-images.githubusercontent.com/8318353/93020223-8c18b700-f5e4-11ea-9b42-f2bab515ea5d.png)


The segments of the map appear scaled right and at the right locations, every zoom level is populated and consistent across the map. All POIs are right on targets.

I still wish to utilize the crop function of multiple segments in the future. At present it seems the crop function confuses the zoom levels going through multiple crop selections.

Looking forward to further updates!

**Comment by Auron956** [comment]
Hi there, as far as I can tell #1850 should resolve both of the crop related issues outlined here.

Specifically on the issue with all crop zones within a render not necessarily using the same number of zoom levels:
- Here is a [render using the current Overviewer master branch](https://map.auron.co.uk/devel-crop-master/#/-51/64/-83/-6/C2%20-%20overworld/C2-UL), where the leftmost crop zone is incorrectly sized relative to the other crop zone & disappears when zoomed in as far as possible.
- Here is [the same render generated using the PR mentioned above](https://map.auron.co.uk/devel-crop-test/#/-51/64/-83/-6/C2%20-%20overworld/C2-UL), where both crop zones are now rendered at the same zoom level.

**Comment by RossosHEX** [comment]
Thank you for your reply.
The first example is exactly what I am getting with the master and the #1839 (already have 1.16 roofs all over the map)
Definitely gonna try and render #1850 with my original config with multiple crop zones. Cheers.
