### ISSUE TITLE
KeyError: 'Player' when generating POI

### ISSUE THREAD

**Issue by jaydenmilne** [overviewer/Minecraft-Overviewer#1853]
### Problem
Can't run `--genpoi` on my world. As far as I remember this exact config worked earlier, although I may be mistaken. If I run `--genpoi --skip-players` it works as expected. Haven't been able to try this on another word, may be specific to mine. Let me know how I can help, I can test a patch if you have one or point me to where I should look if its an easy fix.

### Stacktrace
```
2020-09-24 20:47:11 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/local/bin/overviewer.py", line 653, in <module>
    ret = main()
  File "/usr/local/bin/overviewer.py", line 168, in main
    g.genPOI.main()
  File "/usr/local/lib/python3.6/dist-packages/overviewer_core/aux_files/genPOI.py", line 599, in main
    handlePlayers(worldpath, list(worldpath_filters), markers)
  File "/usr/local/lib/python3.6/dist-packages/overviewer_core/aux_files/genPOI.py", line 328, in handlePlayers
    data = data['Data']['Player']
KeyError: 'Player'
```

### Config: 

```python
global escape
from cgi import escape

worlds = {
    "Main": "/opt/mc/all_biomes",
    "Nether": "/opt/mc/all_biomes_nether",
    "The End": "/opt/mc/all_biomes_the_end"
}

def playerIcons(poi):
    if poi['id'] == "PlayerSpawn":
        # poi['icon'] = "icons/marker_home.png" 
        poi['icon'] = "https://overviewer.org/avatar/%s" % poi['EntityId']
        return poi['EntityId']

def signFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        if len(poi["Text1"]) == 0 or poi["Text1"][0] != "!":
            return

        return "\n".join(map(escape, [poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']]))

renders = {
    "day": {
        "world": "Main",
        "title": "Day",
        "defaultzoom": 15,
        "minzoom": 15,
        "northdirection": "upper-right",
        "markers": [dict(name="Spawns", filterFunction=playerIcons), dict(name="Signs", filterFunction=signFilter)],
        "rendermode": "smooth_lighting",
    },
    "day2": {
        "world": "Main",
        "title": "Day Rotated",
        "defaultzoom": 15,
        "minzoom": 15,
        "markers": [dict(name="Spawns", filterFunction=playerIcons), dict(name="Signs", filterFunction=signFilter)],
        "rendermode": "smooth_lighting",
    },
    "night": {
        "world": "Main",
        "title": "Night",
        "defaultzoom": 15,
        "minzoom": 15,
        "northdirection": "upper-right",
        "markers": [dict(name="Spawns", filterFunction=playerIcons), dict(name="Signs", filterFunction=signFilter)],
        "rendermode": "smooth_night",
    },
    "night2": {
        "world": "Main",
        "title": "Night Rotated",
        "defaultzoom": 15,
        "minzoom": 15,
        "markers": [dict(name="Spawns", filterFunction=playerIcons), dict(name="Signs", filterFunction=signFilter)],
        "rendermode": "smooth_night",
    },

    "nether": {
        "world": "Nether",
        "title": "Nether Upper Left",
        "rendermode": "nether",
        "markers": [dict(name="Signs", filterFunction=signFilter)],
        "northdirection": "upper-left"
    },
    "nether-up-right": {
        "world": "Nether",
        "title": "Nether Upper Right",
        "rendermode": "nether",
        "markers": [dict(name="Signs", filterFunction=signFilter)],
        "northdirection": "upper-right"
    },
    "nether-low-left": {
        "world": "Nether",
        "title": "Nether Lower Left",
        "rendermode": "nether",
        "markers": [dict(name="Signs", filterFunction=signFilter)],
        "northdirection": "lower-left"
    
    },
    "nether-low-right": {
        "world": "Nether",
        "title": "Nether Lower Right",
        "rendermode": "nether",
        "markers": [dict(name="Signs", filterFunction=signFilter)],
        "northdirection": "lower-right"
    },
}


outputdir = "*snip*"
processes = 4
```

### Version:
 (built myself, can't remember why I was having issues with the packaged ones)
```
$ /usr/local/bin/overviewer.py --version
Minecraft Overviewer 0.16.5 (01ed588)
built on Thu Sep 24 20:45:51 2020
```

**Comment by GuusDeGisMan** [comment]
Had the same issue as you, @jaydenmille. My server runs Spigot, and as such it has the "seperate world files" per dimension property. It would seem that, by looking at the code, overviewer loops through the playerdirs, and then makes the determination wether it's a singleplayer or multiplayer world by looking if a folder "playerdata" exists. If it decides it's singleplayer, it looks at level.dat for playerdata, if not: it uses the GUID dat files in the playerdata file. Naturally on spigot there's no playerdata in level.dat for the other dimensions, so somewhere around there it crashes (assuming those are singleplayer dimensions, if only... my gold rates would be much better).

My "have time" workaround for now would be to determine on a per-render level wether it's multiplayer or not and render just ONE playerdata directory (in the folder associated to the dimension marked overworld). For me, for now, the dirty workaround was:

copy the playerdata folder to each and every subfolder... and just... euh... take that in account if I ever need to restore the backup from which I have the map generated...

**Comment by alecrux** [comment]
I can confirm @GuusDeGisMan 's dirty workaround works like a charm on spigot or paper where world files are located in different directories.
FYI, until there's a fix for this, the overviewer section of my script will look like this:
```
cp -r /mnt/minecraft/minecraft-server/world/playerdata/ /mnt/minecraft/minecraft-server/world_nether/
cp -r /mnt/minecraft/minecraft-server/world/playerdata/ /mnt/minecraft/minecraft-server/world_the_end
/mnt/minecraft/minecraft-overviewer/overviewer.py --config=/mnt/minecraft/minecraft-overviewer/config-file.txt
/mnt/minecraft/minecraft-overviewer/overviewer.py --config=/mnt/minecraft/minecraft-overviewer/config-file.txt --genpoi
rm -rf /mnt/minecraft/minecraft-server/world_nether/playerdata/
rm -rf /mnt/minecraft/minecraft-server/world_the_end/playerdata/
```

**Comment by jaydenmilne** [comment]
Going to second @GuusDeGisMan 's dirty workaround, that fixed it for me with a Paper server. It seems that overviewer will follow symlinks though, so a slightly less dirty workaround is to just add a link
```
ln -s /opt/mc/world/playerdata /opt/mc/world_nether/playerdata
ln -s /opt/mc/world/playerdata /opt/mc/world_the_end/playerdata
```

Not sure if this will mess anything up - I don't think that Paper will use the extra folders. There was a `playerdata` folder in my end directory but it was empty

**Comment by divadsn** [comment]
It might be a solution if we could define those seperate worlds as on world with dimensions, like in #1862.

Then Overviewer would look for the playerdata folder inside the main folder only.
