### ISSUE TITLE
Overviewer fails to compile numpy

### ISSUE THREAD

**Issue by Eli-Tarrago** [overviewer/Minecraft-Overviewer#1871]
Raspberry Pi 4B
Debian 10.6
Kernel: 5.4.72-v7l+

libatlas-base-dev is installed.
I also attempted:
pip3 uninstall numpy  # remove previously installed version
apt install python3-numpy

Git branch is master.

To same result.

```
python3 setup.py build
running build
running build_py
copying overviewer_core/overviewer_version.py -> build/lib.linux-armv7l-3.7/overviewer_core
running build_ext
building 'overviewer_core.c_overviewer' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.7m -c overviewer_core/src/main.c -o build/temp.linux-armv7l-3.7/overviewer_core/src/main.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
In file included from overviewer_core/src/main.c:18:
overviewer_core/src/overviewer.h:40:10: fatal error: Imaging.h: No such file or directory
 #include <Imaging.h>
          ^~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

Failed to build Overviewer!
Please review the errors printed above and the build instructions
at <http://docs.overviewer.org/en/latest/building/>.  If you are
still having build problems, file an incident on the github tracker
or find us in IRC.

**Comment by CounterPillow** [comment]
This is not related to numpy, but PIL/Pillow. On Ubuntu, you'll want to install `python3-pil`.
