### ISSUE TITLE
Crash right at the end of the process

### ISSUE THREAD

**Issue by wolfen351** [overviewer/Minecraft-Overviewer#1874]
2020-11-23 21:40:17  Looking for entities in <overviewer_core.world.CroppedRegionSet object at 0x7f3f52012be0>...
2020-11-23 21:40:18  Buckets has 97158 entries.
2020-11-23 21:40:18  Buckets has 97319 entries.
2020-11-23 21:40:18  Buckets has 96173 entries.
2020-11-23 21:43:55  All the threads completed.
2020-11-23 21:43:55  Done.
2020-11-23 21:43:55  Initialized an empty UUID cache.
*******************************************************************************
2020-11-23 21:44:03 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/MOV/overviewer_core/nbt.py", line 199, in read_all
    tagtype = ord(self._file.read(1))
TypeError: ord() expected a character, but string of length 0 found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./overviewer.py", line 653, in <module>
    ret = main()
  File "./overviewer.py", line 168, in main
    g.genPOI.main()
  File "/MOV/overviewer_core/aux_files/genPOI.py", line 599, in main
    handlePlayers(worldpath, list(worldpath_filters), markers)
  File "/MOV/overviewer_core/aux_files/genPOI.py", line 325, in handlePlayers
    data = PlayerDict(nbt.load(os.path.join(playerdir, playerfile))[1])
  File "/MOV/overviewer_core/nbt.py", line 31, in wrapper
    return func(fileobj, *args)
  File "/MOV/overviewer_core/nbt.py", line 40, in load
    return NBTFileReader(fileobj).read_all()
  File "/MOV/overviewer_core/nbt.py", line 207, in read_all
    raise CorruptNBTError("could not parse nbt: %s" % (str(e),))
overviewer_core.nbt.CorruptNBTError: could not parse nbt: ord() expected a character, but string of length 0 found
*******************************************************************************

**Comment by LeadMagnet** [comment]
Can you upload the config file you're using?

**Comment by wolfen351** [comment]
Here is the config - but I don't think it's a config error - I think its an empty player.dat file:

```import os

worlds["world"] = "/data/world"
outputdir = "/mc-map-data"

########### POI ###################################

def playerIcons(poi):
        if poi['id'] == 'Player':
                poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
                return "Last known location for %s" % poi['EntityId']

def signFilter(poi):
        if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
                text = "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']]);
                if (not text.isspace()):
                    return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def chestFilter(poi):
        if poi['id'] == 'Chest':
                return "Chest with %d items" % len(poi['Items'])
                
def spawnerFilter(poi):
        if poi['id'] == 'minecraft:mob_spawner':
                poi['icon'] = "https://mcmap.wolfen.za.net/markers/marker_base_plain.svg"
                return "Mob Spawner: %s" % poi['SpawnData']['id'];

def endPortalFilter(poi):
        if poi['id'] == 'minecraft:end_portal':
                poi['icon'] = "https://mcmap.wolfen.za.net/markers/marker_base_plain.svg"
                return "End Portal";


########### Render Configs ########################

nether_smooth = [Base(), EdgeLines(), Nether(), Depth(max=127), SmoothLighting(strength=0.6)]
nether_roof = [Base(), EdgeLines(), Depth(min=127), SmoothLighting(strength=0.6)]  
end_smooth = [Base(), EdgeLines(), SmoothLighting(strength=0.85, night=True)]
end_smooth_day = [Base(), EdgeLines(), SmoothLighting(strength=0.25)]
caves_lit = [Base(), EdgeLines(), Cave(only_lit=True)]
drained = [Base(), EdgeLines(), Hide(blocks=[8,9,10,11])]

############ Renders ###############################
 
renders["overworld_day"] = {
    "world":        "world",
    "title":        "Overworld (day)",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       smooth_lighting,
    "dimension":        "overworld",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}

renders["overworld_day_rotated"] = {
    "world":        "world",
    "title":        "Overworld (day-rotated)",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       smooth_lighting,
    "dimension":        "overworld",
    'northdirection': "lower-right",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}

renders["overworld_drained"] = {
    "world":        "world",
    "title":        "Overworld (drained)",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       drained,
    "dimension":        "overworld",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}
 
renders["overworld_night"] = {
    "world":        "world",
    "title":        "Overworld (night)",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       smooth_night,
    "dimension":        "overworld",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}

renders["overworld_caves"] = {
        	'world': "world",
        	'title': "Overworld (caves)",
            "crop": (-150000, -150000, 150000, 150000),
        	"rendermode": caves_lit,
        	"dimension": "overworld",
            'markers': [dict(name="All Signs", filterFunction=signFilter), 
                        dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}

renders["overworld_caves_rotated"] = {
        	'world': "world",
        	'title': "Overworld (caves-rotated)",
            "crop": (-150000, -150000, 150000, 150000),
        	"rendermode": caves_lit,
        	"dimension": "overworld",
            'northdirection': "lower-right",
            'markers': [dict(name="All Signs", filterFunction=signFilter), 
                        dict(name="Players",   filterFunction=playerIcons),
                dict(name="Spawners",   filterFunction=spawnerFilter)
                ]
}

 
renders["nether_smooth"] = {
    "world":        "world",
    "title":        "Nether",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       nether_smooth,
    "dimension":        "nether",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons)]
}

renders["nether_roof"] = {
    "world":        "world",
    "title":        "Nether (roof)",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       nether_roof,
    "dimension":        "nether",
    'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons)]
}
 
renders["end_lit"] = {
    "world":        "world",
    "title":        "End",
    "crop": (-150000, -150000, 150000, 150000),
    "rendermode":       end_smooth_day,
    "dimension":        "end",
   'markers': [dict(name="All Signs", filterFunction=signFilter), 
                dict(name="Players",   filterFunction=playerIcons),
                dict(name="End Portal",   filterFunction=endPortalFilter)]
}```

**Comment by wolfen351** [comment]
Ok, confirmed, removing the 0 byte `world/playerdata/{guid}-{longnumber}.dat` file fixed the issue
