### ISSUE TITLE
Error on Rendering Minecraft Map

### ISSUE THREAD

**Issue by Showtaim** [overviewer/Minecraft-Overviewer#1884]
Hi, i can not run your overviewmap.exe on windows.
If i define the world by name it doesnt find it and if I define it by its path it htrows this exception:

2020-12-16 14:40:36  Welcome to Minecraft Overviewer version 0.16.10 (074a7d2)!
2020-12-16 14:40:36 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help
This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 485, in main
KeyError: 'C:\\Users\\Schol\\AppData\\Roaming\\.minecraft\\saves\\ProjectA'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 488, in main
  File "overviewer_core\world.py", line 103, in __init__
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 199, in read_all
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 463, in read
  File "gzip.py", line 411, in _read_gzip_header
OSError: Not a gzipped file (b'\x

I would be happy if you could help me out.

MFG Showtaim

**Comment by mcfandw** [comment]
Can you post the part of your configuration file where you're defining `world_path`, `texturepath`, `outputdir`, and `worlds`?
