### ISSUE TITLE
Can't get overviewer-0.16.10 to run

### ISSUE THREAD

**Issue by p14082003** [overviewer/Minecraft-Overviewer#1892]
I get the following error:

 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "numpy\__init__.py", line 305, in <module>
  File "numpy\__init__.py", line 302, in _win_os_check
RuntimeError: The current Numpy installation ('C:\\Users\\Pedro\\Desktop\\overviewer-0.16.10\\numpy\\__init__.pyc') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set

What can be done about this?

**Comment by CounterPillow** [comment]
Download a newer version of overviewer, this has been fixed.
