### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by RSXEnthusiast** [overviewer/Minecraft-Overviewer#1946]
This is my first time ever using Amulet, so I might just be making a stupid mistake, but I can't open any of my worlds in the 3D Editor without getting a console output very similar to this:

```
2021-06-09 20:32:23,992 - amulet_core - INFO - Loading level C:\Users\joelk\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\flts
2021-06-09 20:32:53,892 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2021-06-09 20:32:54,329 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 132, in _page_change
  File "amulet_map_editor\programs\edit\edit.py", line 51, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 94, in setup
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 99, in _setup
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 178, in _setup
  File "amulet_map_editor\api\opengl\resource_pack\resource_pack.py", line 101, in setup
ValueError: max() arg is an empty sequence
```

I've tried opening bedrock worlds back to 1.15.x, as well as 1.17.x, as well as Java worlds, same error every time. The GUI freezes on "Creating texture atlas" every time. I've also tried deleting Amulet and re-un-zipping it for a fresh install, same issue. I tried using the Amulet beta. I've also tried using the program on a different computer entirely, still no dice. I looked at issue #762 and issue #873 and found nothing helpful there, besides that the issue is still open, even though #762 was opened 9 years ago.

Please let me know if you need anything else, or if there's anything else I could try to remedy the issue, thanks!

Logs:

[amulet_core.log](https://github.com/overviewer/Minecraft-Overviewer/files/6628206/amulet_core.log)
[minecraft_model_reader.log](https://github.com/overviewer/Minecraft-Overviewer/files/6628208/minecraft_model_reader.log)
[pymctranslate.log](https://github.com/overviewer/Minecraft-Overviewer/files/6628209/pymctranslate.log)

**Comment by RSXEnthusiast** [comment]
Dammit, wrong repository.
