### ISSUE TITLE
Error on running Overviewer on 1.17.1

### ISSUE THREAD

**Issue by Jolemu** [overviewer/Minecraft-Overviewer#1964]
Initialy the 1.17 Map Renderd with Overviewer 0.17.33 but 3 Renders after changing to 1.17.1, the Renderer produces the following Exeption:

```
This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 485, in main
KeyError: 'F:\\world'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "overviewer_core\nbt.py", line 199, in read_all
TypeError: ord() expected a character, but string of length 0 found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 491, in main
  File "overviewer.py", line 488, in main
  File "overviewer_core\world.py", line 103, in __init__
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 207, in read_all
overviewer_core.nbt.CorruptNBTError: could not parse nbt: ord() expected a character, but string of length 0 found
```

I tested the following Versions of the Overviewer getting the same Massage:

- overviewer-0.15.28
- overviewer-0.16.12
- overviewer-0.17.29
- overviewer-0.17.33
- overviewer-0.17.34
- overviewer-0.17.39

**Comment by CounterPillow** [comment]
How big is the world, and are you willing to share it so that I can debug this further?

**Comment by Jolemu** [comment]
The World Folder size is 334MB and packed (zip) around 235MB.
I would be happy to share it.

On which way do you want to receive the File?

**Comment by CounterPillow** [comment]
Hi, please upload it here, we can then see it and download it: https://overviewer.org/uploader/

**Comment by Jolemu** [comment]
Hi, I uploaded the File.

Thanks for the fast response.

**Comment by CounterPillow** [comment]
Hello,

your level.dat is corrupt. It's 0 bytes in size. There's nothing overviewer can really do about this.
