### ISSUE TITLE
KeyError: 'Level' when rendering chunks

### ISSUE THREAD

**Issue by jaydenmilne** [overviewer/Minecraft-Overviewer#1975]
Currently unable to render my nether level with version 0.17.39 (2402e41) (built from source). It is crashing with the following stacktrace:

```
2021-08-30 20:25:24 E Could not render chunk -7,-41 for some reason. This is likely a render primitive option error.
2021-08-30 20:25:24 E Full error was:
Traceback (most recent call last):
  File "/home/jayden/src/Minecraft-Overviewer/overviewer_core/tileset.py", line 1091, in _render_rendertile
    c_overviewer.render_loop(
  File "/home/jayden/src/Minecraft-Overviewer/overviewer_core/world.py", line 2040, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/home/jayden/src/Minecraft-Overviewer/overviewer_core/world.py", line 1855, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/jayden/src/Minecraft-Overviewer/overviewer_core/world.py", line 1639, in get_chunk
    level = data[1]['Level']
```

This is happening with several chunks. [Here is the full log](https://pastebin.com/hD9sRFmK). I added some `print` to print the `data` object in word.py :: get_chunk, you'll see that in the log. The printed dict is at the end of this issue.

I don't know much about save formats, but I did notice that according to NBTExplorer, that chunk does have a  `Level` key
![image](https://user-images.githubusercontent.com/7662768/131432886-740c2a8e-d68d-4188-8c8c-54134ef39d32.png)

[Here is the (paper) world save]( https://drive.google.com/file/d/1P1tnlYJYdOYI94ENV1xorDvkeivaLS96/view?usp=sharing )

This is on a Paper server. I recently updated to 1.17 and did a `--forceUpgrade`, which I'm not sure does anything anymore. I wasn't paying close enough attention to notice if it broke right around this change, and I realized my daily backups weren't running either (😅) so I can't roll back the save.

Anyway, not sure where to go from here. I tried loading that chunk and saving it again, didn't work.

```
(
    "",
    {
        "DataVersion": 2730,
        "Position": (-7, 25),
        "Entities": [
            {
                "Paper.SpawnReason": "DEFAULT",
                "DeathTime": 0,
                "Bukkit.updateLevel": 2,
                "LeftHanded": 0,
                "OnGround": 1,
                "AbsorptionAmount": 0.0,
                "AgeLocked": 0,
                "Attributes": [
                    {
                        "Name": "minecraft:generic.follow_range",
                        "Modifiers": [
                            {
                                "Name": "Random spawn bonus",
                                "Amount": -0.007796644803279473,
                                "Operation": 1,
                                "UUID": (
                                    529279158,
                                    2136231899,
                                    -1403107466,
                                    -804648353,
                                ),
                            }
                        ],
                        "Base": 16.0,
                    },
                    {
                        "Name": "minecraft:generic.movement_speed",
                        "Base": 0.17499999701976776,
                    },
                    {"Name": "minecraft:generic.max_health", "Base": 20.0},
                ],
                "Invulnerable": 0,
                "Brain": {"memories": {}},
                "Paper.Origin": [-106.0, 31.0, 412.0],
                "Saddle": 0,
                "Age": 0,
                "Bukkit.Aware": 1,
                "HandDropChances": [0.08500000089406967, 0.08500000089406967],
                "ArmorDropChances": [
                    0.08500000089406967,
                    0.08500000089406967,
                    0.08500000089406967,
                    0.08500000089406967,
                ],
                "Rotation": [185.63052368164062, 0.0],
                "HurtByTimestamp": 0,
                "ForcedAge": 0,
                "WorldUUIDMost": -3588324100773361484,
                "ArmorItems": [{}, {}, {}, {}],
                "Air": 300,
                "HandItems": [{}, {}],
                "UUID": (1182513104, -860077839, -1421357912, 1867273722),
                "Paper.OriginWorld": (-835471811, -93435724, -1780871159, -626871333),
                "Spigot.ticksLived": 46320,
                "InLove": 0,
                "Motion": [0.0, -0.0784000015258789, 0.0],
                "FallDistance": 0.0,
                "WorldUUIDLeast": -7648783382626520101,
                "id": "minecraft:strider",
                "Pos": [-100.59068983548312, 31.5, 413.41988014905496],
                "Fire": 0,
                "CanPickUpLoot": 0,
                "Health": 20.0,
                "HurtTime": 0,
                "FallFlying": 0,
                "PersistenceRequired": 1,
                "PortalCooldown": 0,
            }
        ],
    },
)
```

**Comment by WHSMinecraft** [comment]
I'm experiencing the same issue with Overviewer version 0.17.39 (b941c53). Renders work fine with the overworld, but nether and end give the same errors as @jaydenmilne: https://pastebin.com/Hxv4qhpx. I'm also using Paper (1.17.1 #249).
The issue persists even with a freshly generated world using the same version.

**Comment by urda** [comment]
I also encountered this, using the latest source and local build I get the following:

```
2021-12-03 03:16:23  Welcome to Minecraft Overviewer version 0.17.0 (1beb579)!
*******************************************************************************
2021-12-03 03:16:23 W Unknown region type in '/render/meta/world/urdaworld_2021/entities'
*******************************************************************************
2021-12-03 03:16:23 W Unknown region type in '/render/meta/world/urdaworld_2021/DIM-1/entities'
*******************************************************************************
2021-12-03 03:16:23 W Unknown region type in '/render/meta/world/urdaworld_2021/DIM1/entities'
2021-12-03 03:16:23  Generating textures...
*******************************************************************************
2021-12-03 03:16:34 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/urda/overviewer/bin/overviewer.py", line 653, in <module>
    ret = main()
  File "/urda/overviewer/bin/overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/urda/overviewer/src/overviewer/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/urda/overviewer/src/overviewer/overviewer_core/world.py", line 1500, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'
```

**Comment by urda** [comment]
Attaching a verbose log output, and my config to this comment.

# VERBOSE LOGS

[render.log](https://github.com/overviewer/Minecraft-Overviewer/files/7646620/render.log)

# CONFIG

```python
worlds["Urda World"] = "/render/meta/world/urdaworld_2021"

outputdir = "/render/render.minecraft.urda.com"
texturepath = "/urda/overviewer/data/jars/1.18.jar"


processes = 1


def baseFilter(poi):
    if poi['id'] == 'player_goto':
        return poi['name']

def common_pois(poi):
    if poi['id'] == 'commons':
        return poi['name']

base_markers = [
    { 'name': 'goto:admr_ackbar', 'id': 'player_goto', 'x': '-215',  'y': '79',  'z': '-726' },
    { 'name': 'goto:kmwood11',    'id': 'player_goto', 'x': '261',   'y': '94',  'z': '-273' },
    { 'name': 'goto:urda',        'id': 'player_goto', 'x': '-95',   'y': '211', 'z': '-449' },
    { 'name': 'goto:beach_house', 'id': 'commons',     'x': '-6578', 'y': '69',  'z': '88' },
    { 'name': 'goto:sunflower',   'id': 'commons',     'x': '-3789', 'y': '75',  'z': '-18701' },
    { 'name': 'goto:reflections', 'id': 'commons',     'x': '-1299', 'y': '79',  'z': '516' },
]

render_markers = [
    dict(
        name="GOTOs",
        filterFunction=baseFilter,
        icon="icons/marker_tower.png",
        checked=True,
        createInfoWindow=False,
    ),
    dict(
        name="Commons",
        filterFunction=common_pois,
        icon="icons/marker_mine_red.png",
        checked=True,
        createInfoWindow=False,
    ),
]

renders["survival-northeast-day"] = {
    "world": "Urda World",
    "title": "Northeast",
    "dimension": "overworld",
    "rendermode": smooth_lighting,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "upper-left",
}

renders["survival-northeast-night"] = {
    "world": "Urda World",
    "title": "Northeast (Night)",
    "dimension": "overworld",
    "rendermode": smooth_night,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "upper-left",
}

renders["survival-northwest-day"] = {
    "world": "Urda World",
    "title": "Northwest",
    "dimension": "overworld",
    "rendermode": smooth_lighting,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "upper-right",
}

renders["survival-northwest-night"] = {
    "world": "Urda World",
    "title": "Northwest (Night)",
    "dimension": "overworld",
    "rendermode": smooth_night,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "upper-right",
}

renders["survival-southeast-day"] = {
    "world": "Urda World",
    "title": "Southeast",
    "dimension": "overworld",
    "rendermode": smooth_lighting,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "lower-left",
}

renders["survival-southeast-night"] = {
    "world": "Urda World",
    "title": "Southeast (Night)",
    "dimension": "overworld",
    "rendermode": smooth_night,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "lower-left",
}

renders["survival-southwest-day"] = {
    "world": "Urda World",
    "title": "Southwest",
    "dimension": "overworld",
    "rendermode": smooth_lighting,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "lower-right",
}

renders["survival-southwest-night"] = {
    "world": "Urda World",
    "title": "Southwest (Night)",
    "dimension": "overworld",
    "rendermode": smooth_night,
    "manualpois": base_markers,
    "markers": render_markers,
    "northdirection": "lower-right",
}

renders["nether-survival-northeast"] = {
    "world": "Urda World",
    "title": "Nether Northeast",
    "dimension": "nether",
    "rendermode": nether,
    "northdirection": "upper-left",
}

renders["nether-survival-northwest"] = {
    "world": "Urda World",
    "title": "Nether Northwest",
    "dimension": "nether",
    "rendermode": nether,
    "northdirection": "upper-right",
}

renders["nether-survival-southeast"] = {
    "world": "Urda World",
    "title": "Nether Southeast",
    "dimension": "nether",
    "rendermode": nether,
    "northdirection": "lower-left",
}

renders["nether-survival-southwest"] = {
    "world": "Urda World",
    "title": "Nether Southwest",
    "dimension": "nether",
    "rendermode": nether,
    "northdirection": "lower-right",
}
```

**Comment by CounterPillow** [comment]
@urda 

> 2021-12-03 03:16:23  Welcome to Minecraft Overviewer version 0.17.0 (1beb579)!

That's not the latest source.

**Comment by urda** [comment]
> @urda 
> 
> 
> 
> > 2021-12-03 03:16:23  Welcome to Minecraft Overviewer version 0.17.0 (1beb579)!
> 
> 
> 
> That's not the latest source.

I'm using your latest published tag Release 0.17.0:

https://github.com/overviewer/Minecraft-Overviewer/releases/tag/v0.17.0

Which matches the commit ID in log.

Which commit or tag would you like me to try?

**Comment by CounterPillow** [comment]
I would like you to try the latest commit in master, which is what you should always be using, not the git tags.

**Comment by urda** [comment]
@CounterPillow understood, was just working off the "releases" I had.

I have performed the following:

```
# cd to to local "https://github.com/overviewer/Minecraft-Overviewer.git" repo

$ git checkout master
$ git pull

$ git show -n 1

commit a5b36f568f85a0e1fd4af13edab347f73c759dc3 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2402e41 f6ee2cf
Author: Nicolas F <ovdev@fratti.ch>
Date:   Thu Dec 2 18:58:19 2021 +0100

    Merge PR #1990 from 26/master

    Add compatibility for 21w39a and 21w43a snapshots

python3 setup.py build

(... build lines ...)
running build_scripts
copying and adjusting overviewer.py -> build/scripts-3.8

Build Complete
```

I then restarted my overviewer runner and waited to reach the render step (I didn't catch I failed to send my verbose flag, so hopefully the following output just works haha):

```
[2021-12-03 17:12:00] (7397) --- Remove backup zip file...
[2021-12-03 17:12:00] (7397) --- Render world map...
2021-12-03 17:12:01  Welcome to Minecraft Overviewer version 0.17.41 (a5b36f5)!
2021-12-03 17:12:01  Generating textures...
2021-12-03 17:12:19  Generating textures...
2021-12-03 17:12:36  Generating textures...
2021-12-03 17:12:53  Generating textures...
2021-12-03 17:13:12  Preprocessing...
2021-12-03 17:13:45  Rendered 0 of 105047.  0% complete.  ETA: ------
2021-12-03 17:13:49  Rendered 10 of 105047.  0% complete.  ETA: 11h 21m 01s
2021-12-03 17:13:53  Rendered 20 of 105047.  0% complete.  ETA: 10h 55m 21s
2021-12-03 17:13:56  Rendered 30 of 105047.  0% complete.  ETA: 10h 34m 03s
```

I'll report back when the render completes

**Comment by urda** [comment]
FYI the build was totally fine, so I guess we'll stick with this commit until we see a new release?

```
2021-12-03 22:25:32  Rendered 104900 of 105047.  99% complete.  ETA: 00h 00m 26s
2021-12-03 22:25:33  Rendered 105000 of 105047.  99% complete.  ETA: 00h 00m 08s
2021-12-03 22:25:34  Rendered 105047 of 105047.  100% complete.  Time: 05h 11m 48s
2021-12-03 22:25:34  Your render has been written to '/render/render.minecraft.urda.com', open index.html to view it.
```

**Comment by CounterPillow** [comment]
You should always stick with the latest commit. The git tags serve only to tell people when they need to upgrade their texture pack.

**Comment by urda** [comment]
> You should always stick with the latest commit. The git tags serve only to tell people when they need to upgrade their texture pack.

So is master basically production-stable? Just trying to update my run books.

**Comment by CounterPillow** [comment]
Yes, and always has been.

**Comment by urda** [comment]
> Yes, and always has been. It's what our builds on our website are built from.

Ok thanks for clarifying my misunderstanding here.

**Comment by beulette** [comment]
Sorry to re-open, but I still have the same issue, running the 0.17.45 (5807fda) on a 1.18.1 server on Ubuntu : 

```
$ overviewer.py "ServerWorld" --conf=/home/overviewer/conf --forceRender
2021-12-13 14:05:59  Welcome to Minecraft Overviewer version 0.17.45 (5807fda)!
2021-12-13 14:05:59  Generating textures...
2021-12-13 14:06:24 W The last render for 'normalrender' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
2021-12-13 14:06:24 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
2021-12-13 14:06:24  The unfinished render was a --forcerender. Rerendering any tiles older than 12/11/21 04:20:28.
2021-12-13 14:06:25 W The last render for 'survivalnether' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
2021-12-13 14:06:25 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
2021-12-13 14:06:25  The unfinished render was a --forcerender. Rerendering any tiles older than 12/11/21 04:20:31.
2021-12-13 14:06:25 W The last render for 'survivalender' didn't finish. I'll be scanning all the tiles to make sure everything's up to date.
2021-12-13 14:06:25 W The total tile count will be (possibly wildly) inaccurate, because I don't know how many tiles need rendering. I'll be checking them as I go.
2021-12-13 14:06:25  The unfinished render was a --forcerender. Rerendering any tiles older than 12/11/21 04:20:31.
2021-12-13 14:06:26  Preprocessing...
2021-12-13 14:08:35  Rendering 96468991 total tiles.
2021-12-13 14:19:58 E Could not render chunk -512,-1168 for some reason. This is likely a render primitive option error.                                     ] 28819 42.28t/s eta 633h 36m 45s
2021-12-13 14:19:58 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 2082, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1897, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1675, in get_chunk
    chunk_data = chunk_data['Level']
KeyError: 'Level'
2021-12-13 14:19:58 E Could not render chunk -512,-1168 for some reason. This is likely a render primitive option error.                                     ] 28845 42.26t/s eta 633h 58m 52s
2021-12-13 14:19:58 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 2082, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1897, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1675, in get_chunk
    chunk_data = chunk_data['Level']
KeyError: 'Level'
2021-12-13 14:19:59 E Could not render chunk -512,-1168 for some reason. This is likely a render primitive option error.
2021-12-13 14:19:59 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 2082, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1897, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1675, in get_chunk
    chunk_data = chunk_data['Level']
KeyError: 'Level'
2021-12-13 14:20:01 E Could not render chunk -512,-1168 for some reason. This is likely a render primitive option error.
2021-12-13 14:20:01 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 2082, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1897, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1675, in get_chunk
    chunk_data = chunk_data['Level']
KeyError: 'Level'
```

**Comment by mys3lf** [comment]
Hi everybody, 

same error here. I have the java server version running on Ubuntu. The original version of the server was 1.17. and I recently upgraded it to 1.18. . I use the current docker version of marctv/minecraft-overviewer.

**Comment by CounterPillow** [comment]
Hi,

please open a separate issue for the KeyError: 'Level' traceback that still happens with current versions.

Thank you

**Comment by mys3lf** [comment]
I have to apologize. My used docker image (https://hub.docker.com/r/marctv/minecraft-overviewer) had an old version included. The current version works.

**Comment by beulette** [comment]
After investigation actual MCA was used to delete some chunks. And the result was some artefact chunks, almost empty, that produced bugs in the script.
I deleted the region files and everything works fine now ;-)
