### ISSUE TITLE
Overviewer error when trying to render map.

### ISSUE THREAD

**Issue by dr-atuti** [overviewer/Minecraft-Overviewer#1980]
2021-09-12 07:12:57 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 562, in main
  File "overviewer_core\world.py", line 221, in find_true_spawn
  File "overviewer_core\world.py", line 1666, in get_chunk
  File "overviewer_core\biome.py", line 37, in reshape_biome_data
overviewer_core.biome.BiomeException: Can't reshape a biome of length 2048

I am not very good with code or anything like this so I really don't know what the issue is or especially how to fix it.

**Comment by CounterPillow** [comment]
What version is your overviewer, and what version is the world you're running it on?

**Comment by dr-atuti** [comment]
> What version is your overviewer, and what version is the world you're running it on?

-Overviewer-0.17.39
-Minecraft 1.17.1
