### ISSUE TITLE
Errors with new install

### ISSUE THREAD

**Issue by DreamThief** [overviewer/Minecraft-Overviewer#2069]
New MC install, 1.19.2 , Ubuntu 20.05.3 LTS

```
2022-09-29 01:20:02  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2022-09-29 01:20:02  Generating textures...
2022-09-29 01:20:15 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 653, in <module>
    ret = main()
  File "./overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/root/Minecraft-Overviewer/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/root/Minecraft-Overviewer/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'
```

**Comment by CounterPillow** [comment]
> Overviewer version 0.17.39

please update, this has likely already been fixed
