### ISSUE TITLE
Overviewer 0.19.9 with Minecraft 1.18.2 world

### ISSUE THREAD

**Issue by sethborg** [overviewer/Minecraft-Overviewer#2071]
This is a very old world from 2011 that has been updated to each patch throughout the years.

Error:

```
2022-10-01 12:38:23  Rendered 1958 of 2773.  70% complete.  ETA: 00h 00m 46s
ERROR:root:Could not render chunk 58,129 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1107, in _render_rendertile
  File "overviewer_core\world.py", line 2078, in get_chunk
  File "overviewer_core\world.py", line 1893, in get_chunk
  File "overviewer_core\world.py", line 1749, in get_chunk
  File "overviewer_core\world.py", line 1532, in _get_blockdata_v118
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Here's that block of code in world.py around line 1532 with the second to last line being line 1532:

```
        # Turn the BlockStates array into a 16x16x16 numpy matrix of shorts.
        blocks = numpy.empty((4096,), dtype=numpy.uint16)
        data = numpy.empty((4096,), dtype=numpy.uint8)
        block_states = longarray_unpacker(block_states_data, 4096, num_palette_entries)
        blocks[:] = translated_blocks[block_states]
        data[:] = translated_data[block_states]
```

Seems to be some issue reading the 1.18.2 blocks? Is there any way overviewer can be made to skip chunks with issues and keep rendering rather than hang?

**Comment by ajh123** [comment]
The main README states ..
> PLEASE NOTE: Overviewer is currently unmaintained. PRs will not be merged and issues will not be addressed. The website and repository will remain online and accessible.

Instead please use the new working (“successor”) version of Overviewer supporting 1.20 worlds and textures.
https://github.com/GregoryAM-SP/The-Minecraft-Overviewer
