### ISSUE TITLE
`NameError: name 'os' is not defined` from within config file

### ISSUE THREAD

**Issue by Warpten** [overviewer/Minecraft-Overviewer#2074]
Given this config file
```python
import os

foo = os.getenv('OVWR_FOO')

worlds['word'] = "blah/blah/blah" # CHANGEME
renders['world'] = {
  'world': 'world',
  'title': 'world',
  'rendermode': 'smooth-lighting',
  'dimension': 'overworld'
}

outputdir = "" # CHANGEME
```

And running it
```sh
export OVWR_FOO="yep"
./overviewer.py --config=../config-overview.py
```

I get:
```
2022-12-02 15:56:58 E NameError parsing '../config-overview.py'.
2022-12-02 15:56:58 E The traceback below will tell you which line referenced the non-existent variable.

2022-12-02 15:56:58 E Partial traceback:
Traceback (most recent call last):
  File "overviewer/overviewer_core/config_parser.py", line 85, in parse
    exec(compile(settings_file_handle.read(), settings_file, 'exec'),
  File "../config-overview.py", line 113, in <module>
    ServerAnnouncer(20)
  File "../config-overview.py", line 58, in __init__
    target_handle = "/proc/%s/fd/0" % os.environ['OVERVIEWER_ANNOUNCER_PID'].strip()
NameError: name 'os' is not defined
```

(The log is slightly different than the example because I wrote a semi-custom observer that sends messages with `tellraw` instead of `say`)

System: Ubuntu 22.04
Python: 3.10.6

**Comment by Warpten** [comment]
user error, typical
