### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded"  since upgrading to 1.19.3

### ISSUE THREAD

**Issue by BenKennish** [overviewer/Minecraft-Overviewer#2076]
I upgraded Minecraft to 1.19.3 and overviewer will no longer render my world...

```
overviewer.py:371  6256 2022-12-12 02:11:58 INFO     Welcome to Minecraft Overviewer version 0.19.44 (cabcdf9)!
overviewer.py:504  6256 2022-12-12 02:11:58 INFO     Generating textures...
*******************************************************************************
overviewer.py:663  6256 2022-12-12 02:12:20 ERROR    An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/opt/minecraft/server/../tools/overviewer/overviewer.py", line 653, in <module>
    ret = main()
  File "/opt/minecraft/server/../tools/overviewer/overviewer.py", line 505, in main
    tex.generate()
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 145, in generate
    tex = texgen(self, blockid, data)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1218, in func_wrapper
    return func(texobj, blockid, data)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1257, in inner_block
    return self.build_block_from_model(name)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 940, in build_block_from_model
    self.draw_blockface(img, elem, colmodel, blockstate, modelname, 'north')
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 969, in draw_blockface
    texture = self.build_texture(direction, elem, colmodel, blockstate, modelname, facing)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1061, in build_texture
    elem['faces'][textureface]['texture'], data['textures']).copy()
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1186, in find_texture_from_model
    return self.find_texture_from_model(textureset[face[1:]], textureset)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1186, in find_texture_from_model
    return self.find_texture_from_model(textureset[face[1:]], textureset)
  File "/opt/minecraft/tools/overviewer/overviewer_core/textures.py", line 1186, in find_texture_from_model
    return self.find_texture_from_model(textureset[face[1:]], textureset)
  [Previous line repeated 989 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by BenKennish** [comment]
How would i go about trying to debug this?  I cannot render a world map anymore and the players on my server are missing being able to view one 😢

Is overviewer working on 1.19.3 worlds for anyone else?

**Comment by BenKennish** [comment]
See #2046  - i was using a fork that has a bug with 1.19.3
