### ISSUE TITLE
File not found : x86_64-linux-gnu-gcc While building from Source

### ISSUE THREAD

**Issue by S70RM7R00P3R** [overviewer/Minecraft-Overviewer#2079]
I am getting following errors when trying to build from source:

```running build
running build_py
copying overviewer_core/overviewer_version.py -> build/lib.linux-x86_64-3.9/overviewer_core
running build_ext
building 'overviewer_core.c_overviewer' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.9 -c overviewer_core/src/Draw.c -o build/temp.linux-x86_64-3.9/overviewer_core/src/Draw.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement -O3 -std=gnu99
Traceback (most recent call last):
  File "/usr/lib/python3.9/distutils/spawn.py", line 75, in spawn
    proc = subprocess.Popen(cmd, env=env)
FileNotFoundError: [Errno 2] No such file or directory: 'x86_64-linux-gnu-gcc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/louis/overviewer/Minecraft-Overviewer/setup.py", line 300, in run
    build.run(self)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed: No such file or directory

Failed to build Overviewer!
Please review the errors printed above and the build instructions
at <http://docs.overviewer.org/en/latest/building/>.  If you are
still having build problems, file an incident on the github tracker
or find us in IRC.```

**Comment by vilhok** [comment]
Do you have `gcc` installed for compiling the C-parts? Did you follow the guide properly? http://docs.overviewer.org/en/latest/building/

**Comment by S70RM7R00P3R** [comment]
> Do you have `gcc` installed for compiling the C-parts? Did you follow the guide properly? http://docs.overviewer.org/en/latest/building/

That fixed the issue. Thanks a lot! :)
