### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by SashaPro22** [overviewer/Minecraft-Overviewer#2097]
Hi! Can me help pls error:
2023-08-19 15:21:33 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 653, in <module>
    ret = main()
  File "./overviewer.py", line 505, in main
    tex.generate()
  File "/root/Minecraft-Overviewer/overviewer_core/textures.py", line 134, in generate
    self.biome_grass_texture = self.build_block(self.load_image_texture("assets/minecraft/textures/block/grass_block_top.png"), self.load_image_texture("assets/minecraft/textures/block/grass_block_side_overlay.png"))
  File "/root/Minecraft-Overviewer/overviewer_core/textures.py", line 578, in build_block
    top = self.transform_image_top(top)
  File "/root/Minecraft-Overviewer/overviewer_core/textures.py", line 474, in transform_image_top
    img = img.resize((17, 17), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by CounterPillow** [comment]
no, I've already told you on IRC that the project is unmaintained.

**Comment by SashaPro22** [comment]
I really need this card and I count on the support of knowledgeable people

> no, I've already told you on IRC that the project is unmaintained.

**Comment by dafvid** [comment]
Hi
Had the same issue. Pillow 10 has removed ANTIALIAS. Downgrade to Pillow 9.5.0 fixes this.

**Comment by SashaPro22** [comment]
> Hi Had the same issue. Pillow 10 has removed ANTIALIAS. Downgrade to Pillow 9.5.0 fixes this.

Where will it need to be changed? in overviewer.py ?

**Comment by dafvid** [comment]
> > Hi Had the same issue. Pillow 10 has removed ANTIALIAS. Downgrade to Pillow 9.5.0 fixes this.
> 
> 
> 
> Where will it need to be changed? in overviewer.py ?

Try pip install Pillow==9.5.0

**Comment by dafvid** [comment]
You also need to build overviewer with the Pillow 9.5.0 header files if you're building from source

**Comment by Gregory-AM** [comment]
@SashaPro22, you can use the successor version of [The Minecraft Overviewer](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer). It fixes Antialiasing issues, and renders 1.20 worlds.

**Comment by SashaPro22** [comment]
> You also need to build overviewer with the Pillow 9.5.0 header files if you're building from source

I did it on your advice and one mistake went away, but the second one didn't:
This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 653, in <module>
    ret = main()
  File "./overviewer.py", line 505, in main
    tex.generate()
  File "/home/mup/overviewer_core/textures.py", line 142, in generate
    tex = texgen(self, blockid, data)
  File "/home/mup/overviewer_core/textures.py", line 860, in func_wrapper
    return func(texobj, blockid, data)
  File "/home/mup/overviewer_core/textures.py", line 4072, in repeater
    ImageDraw.Draw(torch).rectangle((0,24,10,15),outline=(0,0,0,0),fill=(0,0,0,0))
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageDraw.py", line 294, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: y1 must be greater than or equal to y0

**Comment by Gregory-AM** [comment]
@SashaPro22 
Haha 😆
I remember when I first started working on Overviewer and this was the *first* issue.

ImageDraw.Draw(torch).rectangle((0,15,10,24),outline=(0,0,0,0),fill=(0,0,0,0))

**Comment by Gregory-AM** [comment]
> > @SashaPro22, you can use the successor version of [The Minecraft Overviewer](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer). It fixes Antialiasing issues, and renders 1.20 worlds.
> 
> How to run this version in linux?

You have to build it from source.
