### ISSUE TITLE
genPOI TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by gouldcwilliam** [overviewer/Minecraft-Overviewer#2102]
This is the error that occurred:
Traceback (most recent call last):
  File "/home/red/overviewer/overviewer.py", line 662, in <module>
    ret = main()
  File "/home/red/overviewer/overviewer.py", line 168, in main
    g.genPOI.main()
  File "/home/red/The-Minecraft-Overviewer/overviewer_core/aux_files/genPOI.py", line 576, in main
    erset = w.get_regionset(render['dimension'][1] + '/entities')
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by gouldcwilliam** [comment]
I was able genpoi a couple of times but now it gives this error

**Comment by gouldcwilliam** [comment]
So, i was using the version that you get when using git clone blah blah. That version after building didn't work. I downloaded the zip version from the download page and used that. It then started working
