### ISSUE TITLE
An error has occurred. This may be a bug. Please let us know!

### ISSUE THREAD

**Issue by LOTUS19971128** [overviewer/Minecraft-Overviewer#2104]
I'll just report it for now.
If there's anything I can do, please let me know.

2024-11-09 07:58:33 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 485, in main
KeyError: 'D:\\home\\minecraft\\bedrock-server-1.21.43.01\\worlds\\Bedrock level'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 488, in main
  File "overviewer_core\world.py", line 103, in __init__
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 199, in read_all
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 463, in read
  File "gzip.py", line 411, in _read_gzip_header
OSError: Not a gzipped file (b'\n\x00')

**Comment by JoKoMax** [comment]
i have the same error on my sev tech ages server

**Comment by JoshuaMarti** [comment]
Would I be right to guess this is a Bedrock edition world? If so, you'll need to convert it to Java Edition before Overviewer can make the map.
